// Code generated by "go run ./internal/generate/modules gen". DO NOT EDIT.
// Source: modules/workshop/module.yaml

package backend

import (
	"encoding/json"

	"github.com/jj-link/local-model-works/internal/moduleapi"
)

// descriptor is this module's frozen manifest.
var descriptor = moduleapi.Descriptor{APIVersion: "localmodelworks/v1alpha1", Kind: "Module", ID: "workshop", Title: "Workshop", Route: "/workshop", Nav: moduleapi.Nav{Label: "Workshop", Order: 45, Icon: "workshop"}, SettingsSchema: json.RawMessage("{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"additionalProperties\":false,\"properties\":{},\"type\":\"object\"}"), Capabilities: []string{"nodes.read", "fabrics.read", "deployments.read"}}
