// Package backend provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backend

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateFabricRequestTransport.
const (
	CreateFabricRequestTransportRoce CreateFabricRequestTransport = "roce"
	CreateFabricRequestTransportTcp  CreateFabricRequestTransport = "tcp"
)

// Valid indicates whether the value is a known member of the CreateFabricRequestTransport enum.
func (e CreateFabricRequestTransport) Valid() bool {
	switch e {
	case CreateFabricRequestTransportRoce:
		return true
	case CreateFabricRequestTransportTcp:
		return true
	default:
		return false
	}
}

// Defines values for DiagnosticSeverity.
const (
	DiagnosticSeverityError   DiagnosticSeverity = "error"
	DiagnosticSeverityInfo    DiagnosticSeverity = "info"
	DiagnosticSeverityWarning DiagnosticSeverity = "warning"
)

// Valid indicates whether the value is a known member of the DiagnosticSeverity enum.
func (e DiagnosticSeverity) Valid() bool {
	switch e {
	case DiagnosticSeverityError:
		return true
	case DiagnosticSeverityInfo:
		return true
	case DiagnosticSeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for FabricState.
const (
	Incomplete FabricState = "incomplete"
	Ok         FabricState = "ok"
)

// Valid indicates whether the value is a known member of the FabricState enum.
func (e FabricState) Valid() bool {
	switch e {
	case Incomplete:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for FabricTransport.
const (
	FabricTransportRoce FabricTransport = "roce"
	FabricTransportTcp  FabricTransport = "tcp"
)

// Valid indicates whether the value is a known member of the FabricTransport enum.
func (e FabricTransport) Valid() bool {
	switch e {
	case FabricTransportRoce:
		return true
	case FabricTransportTcp:
		return true
	default:
		return false
	}
}

// Defines values for NodeStatus.
const (
	Degraded NodeStatus = "degraded"
	Offline  NodeStatus = "offline"
	Online   NodeStatus = "online"
	Pending  NodeStatus = "pending"
)

// Valid indicates whether the value is a known member of the NodeStatus enum.
func (e NodeStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Offline:
		return true
	case Online:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for GetNodeTelemetryParamsResolution.
const (
	N1m GetNodeTelemetryParamsResolution = "1m"
	N5s GetNodeTelemetryParamsResolution = "5s"
)

// Valid indicates whether the value is a known member of the GetNodeTelemetryParamsResolution enum.
func (e GetNodeTelemetryParamsResolution) Valid() bool {
	switch e {
	case N1m:
		return true
	case N5s:
		return true
	default:
		return false
	}
}

// Accelerator defines model for Accelerator.
type Accelerator struct {
	// Architecture e.g. sm_120, gfx1201
	Architecture *string   `json:"architecture,omitempty"`
	Features     *[]string `json:"features,omitempty"`
	Index        int       `json:"index"`
	MemoryBytes  int64     `json:"memory_bytes"`
	Name         string    `json:"name"`
	Uuid         string    `json:"uuid"`

	// Vendor Vendor-neutral capability field, e.g. nvidia, amd, intel
	Vendor string `json:"vendor"`
}

// CacheRoot defines model for CacheRoot.
type CacheRoot struct {
	Backend      string    `json:"backend"`
	Path         string    `json:"path"`
	Repositories *[]string `json:"repositories,omitempty"`

	// Writable Probed by the node agent through its own mount namespace. False means artifact fetches into this root will fail until the root is added to the agent service ReadWritePaths.
	Writable *bool `json:"writable,omitempty"`
}

// CertificateInfo defines model for CertificateInfo.
type CertificateInfo struct {
	ExpiresAt time.Time  `json:"expires_at"`
	NotBefore *time.Time `json:"not_before,omitempty"`
	Serial    *string    `json:"serial,omitempty"`
}

// CreateFabricRequest defines model for CreateFabricRequest.
type CreateFabricRequest struct {
	// Bindings Node-specific transport wiring in member/rank order
	Bindings []FabricBinding `json:"bindings"`

	// Members Ordered node IDs; index is the fabric rank
	Members   []string                     `json:"members"`
	Name      string                       `json:"name"`
	Transport CreateFabricRequestTransport `json:"transport"`
}

// CreateFabricRequestTransport defines model for CreateFabricRequest.Transport.
type CreateFabricRequestTransport string

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Code     string             `json:"code"`
	Message  string             `json:"message"`
	Resource *string            `json:"resource,omitempty"`
	Severity DiagnosticSeverity `json:"severity"`
}

// DiagnosticSeverity defines model for Diagnostic.Severity.
type DiagnosticSeverity string

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable error code, e.g. node.occupied, plan.incompatible
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Fabric defines model for Fabric.
type Fabric struct {
	Bindings    []FabricBinding    `json:"bindings"`
	Diagnostics *[]Diagnostic      `json:"diagnostics,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Members     []string           `json:"members"`
	Name        string             `json:"name"`
	State       FabricState        `json:"state"`
	Transport   FabricTransport    `json:"transport"`

	// Version ETag for optimistic concurrency
	Version *string `json:"version,omitempty"`
}

// FabricState defines model for Fabric.State.
type FabricState string

// FabricTransport defines model for Fabric.Transport.
type FabricTransport string

// FabricBinding defines model for FabricBinding.
type FabricBinding struct {
	Address       string             `json:"address"`
	GidIndex      *int               `json:"gid_index,omitempty"`
	InterfaceName string             `json:"interface_name"`
	NodeId        openapi_types.UUID `json:"node_id"`
	RdmaDevice    *string            `json:"rdma_device,omitempty"`
}

// Inventory defines model for Inventory.
type Inventory struct {
	Accelerators *[]Accelerator `json:"accelerators,omitempty"`
	Arch         string         `json:"arch"`
	CacheRoots   *[]CacheRoot   `json:"cache_roots,omitempty"`
	Docker       struct {
		ApiVersion *string `json:"api_version,omitempty"`
		Ok         bool    `json:"ok"`
		Version    string  `json:"version"`
	} `json:"docker"`
	Hostname    string              `json:"hostname"`
	Interfaces  *[]NetworkInterface `json:"interfaces,omitempty"`
	Os          string              `json:"os"`
	PeerListen  *string             `json:"peer_listen,omitempty"`
	RdmaDevices *[]RdmaDevice       `json:"rdma_devices,omitempty"`
}

// NetworkInterface defines model for NetworkInterface.
type NetworkInterface struct {
	Addresses []string `json:"addresses"`
	LinkMbps  *int     `json:"link_mbps,omitempty"`
	Mtu       *int     `json:"mtu,omitempty"`
	Name      string   `json:"name"`
}

// Node defines model for Node.
type Node struct {
	AgentVersion         *string            `json:"agent_version,omitempty"`
	CertificateExpiresAt *time.Time         `json:"certificate_expires_at,omitempty"`
	CreatedAt            time.Time          `json:"created_at"`
	Diagnostics          *[]Diagnostic      `json:"diagnostics,omitempty"`
	DisplayName          string             `json:"display_name"`
	Id                   openapi_types.UUID `json:"id"`
	Inventory            *Inventory         `json:"inventory,omitempty"`
	Labels               *map[string]string `json:"labels,omitempty"`
	LastHeartbeat        *time.Time         `json:"last_heartbeat,omitempty"`
	Status               NodeStatus         `json:"status"`
}

// NodePayload defines model for NodePayload.
type NodePayload struct {
	Accelerators *[]struct {
		Index            *int   `json:"index,omitempty"`
		MemoryTotalBytes *int64 `json:"memory_total_bytes,omitempty"`
		MemoryUsedBytes  *int64 `json:"memory_used_bytes,omitempty"`
		PowerLimitMw     *int64 `json:"power_limit_mw,omitempty"`
		PowerMw          *int64 `json:"power_mw,omitempty"`
		Processes        *[]struct {
			Name               *string `json:"name,omitempty"`
			Pid                *int64  `json:"pid,omitempty"`
			UsedGpuMemoryBytes *int64  `json:"used_gpu_memory_bytes,omitempty"`
		} `json:"processes,omitempty"`
		TemperatureC       *int64    `json:"temperature_c,omitempty"`
		ThrottleReasons    *[]string `json:"throttle_reasons,omitempty"`
		UtilizationPercent *int64    `json:"utilization_percent,omitempty"`
	} `json:"accelerators,omitempty"`
	Cpu *struct {
		Cores        *int64 `json:"cores,omitempty"`
		Load1        *int64 `json:"load1,omitempty"`
		UsagePercent *int64 `json:"usage_percent,omitempty"`
	} `json:"cpu,omitempty"`
	Filesystems *[]struct {
		MountPath  *string `json:"mount_path,omitempty"`
		TotalBytes *int64  `json:"total_bytes,omitempty"`
		UsedBytes  *int64  `json:"used_bytes,omitempty"`
	} `json:"filesystems,omitempty"`
	Memory *struct {
		SwapTotalBytes *int64 `json:"swap_total_bytes,omitempty"`
		SwapUsedBytes  *int64 `json:"swap_used_bytes,omitempty"`
		Swappiness     *int32 `json:"swappiness,omitempty"`
		TotalBytes     *int64 `json:"total_bytes,omitempty"`
		UsedBytes      *int64 `json:"used_bytes,omitempty"`
	} `json:"memory,omitempty"`
	Network *struct {
		Interfaces *[]struct {
			Name             *string `json:"name,omitempty"`
			RxBytesPerSecond *int64  `json:"rx_bytes_per_second,omitempty"`
			TxBytesPerSecond *int64  `json:"tx_bytes_per_second,omitempty"`
		} `json:"interfaces,omitempty"`
		RxBytes          *int64 `json:"rx_bytes,omitempty"`
		RxBytesPerSecond *int64 `json:"rx_bytes_per_second,omitempty"`
		TxBytes          *int64 `json:"tx_bytes,omitempty"`
		TxBytesPerSecond *int64 `json:"tx_bytes_per_second,omitempty"`
	} `json:"network,omitempty"`
	UptimeSeconds *int64 `json:"uptime_seconds,omitempty"`
}

// NodeStatus defines model for NodeStatus.
type NodeStatus string

// NodeTelemetrySample defines model for NodeTelemetrySample.
type NodeTelemetrySample struct {
	NodeId  openapi_types.UUID `json:"node_id"`
	Payload NodePayload        `json:"payload"`
	Ts      int64              `json:"ts"`
}

// RdmaDevice defines model for RdmaDevice.
type RdmaDevice struct {
	Name              string    `json:"name"`
	NetworkInterfaces *[]string `json:"network_interfaces,omitempty"`
	Ports             []struct {
		Gids         *[]RdmaGID `json:"gids,omitempty"`
		LinkRateGbps *int       `json:"link_rate_gbps,omitempty"`
		Name         *string    `json:"name,omitempty"`
		State        *string    `json:"state,omitempty"`
	} `json:"ports"`
	Vendor *string `json:"vendor,omitempty"`
}

// RdmaGID defines model for RdmaGID.
type RdmaGID struct {
	Index int     `json:"index"`
	Type  *string `json:"type,omitempty"`
	Value string  `json:"value"`
}

// UpdateNodeRequest defines model for UpdateNodeRequest.
type UpdateNodeRequest struct {
	DisplayName string             `json:"display_name"`
	Labels      *map[string]string `json:"labels,omitempty"`
}

// ID defines model for ID.
type ID = string

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// CreateFabricParams defines parameters for CreateFabric.
type CreateFabricParams struct {
	IfMatch *string `json:"If-Match,omitempty"`
}

// DeleteFabricParams defines parameters for DeleteFabric.
type DeleteFabricParams struct {
	IfMatch string `json:"If-Match"`
}

// UpdateFabricParams defines parameters for UpdateFabric.
type UpdateFabricParams struct {
	IfMatch string `json:"If-Match"`
}

// GetNodeTelemetryParams defines parameters for GetNodeTelemetry.
type GetNodeTelemetryParams struct {
	Resolution *GetNodeTelemetryParamsResolution `form:"resolution,omitempty" json:"resolution,omitempty"`
	From       *int64                            `form:"from,omitempty" json:"from,omitempty"`
	To         *int64                            `form:"to,omitempty" json:"to,omitempty"`
	Limit      *int                              `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetNodeTelemetryParamsResolution defines parameters for GetNodeTelemetry.
type GetNodeTelemetryParamsResolution string

// CreateFabricJSONRequestBody defines body for CreateFabric for application/json ContentType.
type CreateFabricJSONRequestBody = CreateFabricRequest

// UpdateFabricJSONRequestBody defines body for UpdateFabric for application/json ContentType.
type UpdateFabricJSONRequestBody = CreateFabricRequest

// UpdateNodeJSONRequestBody defines body for UpdateNode for application/json ContentType.
type UpdateNodeJSONRequestBody = UpdateNodeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /fabrics)
	ListFabrics(w http.ResponseWriter, r *http.Request)

	// (POST /fabrics)
	CreateFabric(w http.ResponseWriter, r *http.Request, params CreateFabricParams)

	// (DELETE /fabrics/{id})
	DeleteFabric(w http.ResponseWriter, r *http.Request, id ID, params DeleteFabricParams)

	// (GET /fabrics/{id})
	GetFabric(w http.ResponseWriter, r *http.Request, id ID)

	// (PUT /fabrics/{id})
	UpdateFabric(w http.ResponseWriter, r *http.Request, id ID, params UpdateFabricParams)

	// (GET /nodes)
	ListNodes(w http.ResponseWriter, r *http.Request)
	// ListNodeTelemetry Latest typed telemetry sample per node
	// (GET /nodes/telemetry)
	ListNodeTelemetry(w http.ResponseWriter, r *http.Request)

	// (GET /nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id ID)
	// UpdateNode Set display name and labels
	// (PUT /nodes/{id})
	UpdateNode(w http.ResponseWriter, r *http.Request, id ID)
	// ApproveNode Approve a pending node's reported inventory
	// (POST /nodes/{id}/approve)
	ApproveNode(w http.ResponseWriter, r *http.Request, id ID)
	// RotateNodeCertificate Issue a fresh 90-day client certificate for the node
	// (POST /nodes/{id}/rotate-certificate)
	RotateNodeCertificate(w http.ResponseWriter, r *http.Request, id ID)

	// (GET /nodes/{id}/telemetry)
	GetNodeTelemetry(w http.ResponseWriter, r *http.Request, id ID, params GetNodeTelemetryParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /fabrics)
func (_ Unimplemented) ListFabrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /fabrics)
func (_ Unimplemented) CreateFabric(w http.ResponseWriter, r *http.Request, params CreateFabricParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /fabrics/{id})
func (_ Unimplemented) DeleteFabric(w http.ResponseWriter, r *http.Request, id ID, params DeleteFabricParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /fabrics/{id})
func (_ Unimplemented) GetFabric(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /fabrics/{id})
func (_ Unimplemented) UpdateFabric(w http.ResponseWriter, r *http.Request, id ID, params UpdateFabricParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /nodes)
func (_ Unimplemented) ListNodes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListNodeTelemetry Latest typed telemetry sample per node
// (GET /nodes/telemetry)
func (_ Unimplemented) ListNodeTelemetry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /nodes/{id})
func (_ Unimplemented) GetNode(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateNode Set display name and labels
// (PUT /nodes/{id})
func (_ Unimplemented) UpdateNode(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApproveNode Approve a pending node's reported inventory
// (POST /nodes/{id}/approve)
func (_ Unimplemented) ApproveNode(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RotateNodeCertificate Issue a fresh 90-day client certificate for the node
// (POST /nodes/{id}/rotate-certificate)
func (_ Unimplemented) RotateNodeCertificate(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /nodes/{id}/telemetry)
func (_ Unimplemented) GetNodeTelemetry(w http.ResponseWriter, r *http.Request, id ID, params GetNodeTelemetryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListFabrics operation middleware
func (siw *ServerInterfaceWrapper) ListFabrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFabrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFabric operation middleware
func (siw *ServerInterfaceWrapper) CreateFabric(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateFabricParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFabric(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFabric operation middleware
func (siw *ServerInterfaceWrapper) DeleteFabric(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteFabricParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFabric(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFabric operation middleware
func (siw *ServerInterfaceWrapper) GetFabric(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFabric(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateFabric operation middleware
func (siw *ServerInterfaceWrapper) UpdateFabric(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateFabricParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFabric(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodeTelemetry operation middleware
func (siw *ServerInterfaceWrapper) ListNodeTelemetry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodeTelemetry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveNode operation middleware
func (siw *ServerInterfaceWrapper) ApproveNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateNodeCertificate operation middleware
func (siw *ServerInterfaceWrapper) RotateNodeCertificate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateNodeCertificate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNodeTelemetry operation middleware
func (siw *ServerInterfaceWrapper) GetNodeTelemetry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNodeTelemetryParams

	// ------------- Optional query parameter "resolution" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resolution", r.URL.Query(), &params.Resolution, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resolution"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resolution", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNodeTelemetry(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/fabrics", wrapper.ListFabrics)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/fabrics", wrapper.CreateFabric)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/fabrics/{id}", wrapper.DeleteFabric)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/fabrics/{id}", wrapper.GetFabric)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/fabrics/{id}", wrapper.UpdateFabric)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes", wrapper.ListNodes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes/{id}", wrapper.GetNode)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/nodes/{id}", wrapper.UpdateNode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/nodes/{id}/approve", wrapper.ApproveNode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/nodes/{id}/rotate-certificate", wrapper.RotateNodeCertificate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes/{id}/telemetry", wrapper.GetNodeTelemetry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes/telemetry", wrapper.ListNodeTelemetry)
	})

	return r
}
