// Code generated by "go run ./internal/generate/modules gen". DO NOT EDIT.
// Source: modules/fleet/module.yaml

package backend

import (
	"encoding/json"

	"github.com/jj-link/local-model-works/internal/moduleapi"
)

// descriptor is this module's frozen manifest.
var descriptor = moduleapi.Descriptor{APIVersion: "localmodelworks/v1alpha1", Kind: "Module", ID: "fleet", Title: "Fleet", Route: "/fleet", Nav: moduleapi.Nav{Label: "Fleet", Order: 10, Icon: "fleet"}, SettingsSchema: json.RawMessage("{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"additionalProperties\":false,\"properties\":{},\"type\":\"object\"}"), APIFragment: "api.yaml", Capabilities: []string{"nodes.read", "fabrics.read", "events.publish"}}
