// Code generated by "go run ./internal/generate/modules gen". DO NOT EDIT.
// Source: modules/chat/module.yaml

package backend

import "github.com/jj-link/local-model-works/internal/moduleapi"

// descriptor is this module's frozen manifest.
var descriptor = moduleapi.Descriptor{APIVersion: "localmodelworks/v1alpha1", Kind: "Module", ID: "chat", Title: "Chat", Route: "/chat", Nav: moduleapi.Nav{Label: "Chat", Order: 55, Icon: "chat"}, APIFragment: "api.yaml", Capabilities: []string{"deployments.read"}}
