import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import type { Node, RecipeDownloadPlan, DeploymentPlan } from "~/lib/api";
import { bytes } from "~/lib/format";
import { record, records } from "./workflow";

export type RuntimeSelection = { workload_index?: number; variants: Record<string, string> };
export function RuntimeSelections({ manifest, value, onChange, parameters, onParametersChange, disabled = false }: {
  manifest: Record<string, unknown>; value: RuntimeSelection; onChange: (value: RuntimeSelection) => void;
  parameters?: Record<string, unknown>; onParametersChange?: (value: Record<string, unknown>) => void; disabled?: boolean;
}) {
  const artifacts = records(manifest.artifacts).filter((artifact) => Array.isArray(artifact.variants) && artifact.variants.length);
  const workloads = records(manifest.workloads);
  const parameterFields = records(manifest.parameters);
  const extraVariants = Object.keys(value.variants).filter((name) => !artifacts.some((artifact) => artifact.name === name));
  const extraParameters = Object.keys(parameters || {}).filter((name) => !parameterFields.some((parameter) => parameter.name === name));
  return <fieldset disabled={disabled} className="space-y-3">
    <label className="grid gap-1.5 text-sm"><span>Runtime files</span><select aria-label="Runtime files" className="control bg-panel p-2" value={value.workload_index ?? ""} onChange={(event) => onChange({ ...value, workload_index: event.target.value === "" ? undefined : Number(event.target.value) })}><option value="">Resolve uniquely compatible runtime</option>{workloads.map((workload, index) => <option key={index} value={index}>{String(workload.name || record(workload.image).reference || `Runtime ${index + 1}`)}</option>)}</select></label>
    {artifacts.map((artifact) => { const name = String(artifact.name); return <label className="grid gap-1.5 text-sm" key={name}><span>{name} version / quantization</span><select aria-label={`${name} variant`} className="control bg-panel p-2" value={value.variants[name] ?? String(artifact.defaultVariant || "")} onChange={(event) => onChange({ ...value, variants: { ...value.variants, [name]: event.target.value } })}><option value="">Choose a supported variant</option>{records(artifact.variants).map((variant) => <option key={String(variant.name)} value={String(variant.name)}>{String(variant.label || variant.name)}{variant.description ? ` · ${String(variant.description)}` : ""}</option>)}</select></label>; })}
    {parameters && onParametersChange ? parameterFields.map((parameter) => { const name = String(parameter.name); const chosen = parameters[name] ?? parameter.default ?? ""; const type = String(parameter.type); const enumValues = Array.isArray(parameter.enum) ? parameter.enum : undefined; return <label className="grid gap-1.5 text-sm" key={name}><span>{name}</span>{parameter.description ? <span className="text-xs text-muted">{String(parameter.description)}</span> : null}{enumValues ? <select aria-label={name} className="control bg-panel p-2" value={String(chosen)} onChange={(event) => onParametersChange({ ...parameters, [name]: enumValues.find((option) => String(option) === event.target.value) })}>{enumValues.map((option) => <option key={String(option)}>{String(option)}</option>)}</select> : ["boolean", "bool"].includes(type) ? <input aria-label={name} type="checkbox" checked={chosen === true} onChange={(event) => onParametersChange({ ...parameters, [name]: event.target.checked })} /> : <Input aria-label={name} type={["int", "integer", "number", "float"].includes(type) ? "number" : parameter.sensitive === true ? "password" : "text"} value={String(chosen)} onChange={(event) => onParametersChange({ ...parameters, [name]: ["int", "integer", "number", "float"].includes(type) ? Number(event.target.value) : event.target.value })} />}</label>; }) : null}
    {extraVariants.map((name) => <div className="border border-fault/40 p-2 text-sm" role="alert" key={name}>Saved variant {name} is not supported by this version. <Button size="sm" variant="outline" onClick={() => { const variants = { ...value.variants }; delete variants[name]; onChange({ ...value, variants }); }}>Remove unsupported variant</Button></div>)}
    {extraParameters.map((name) => <div className="border border-fault/40 p-2 text-sm" role="alert" key={name}>Saved parameter {name} is not supported by this version. <Button size="sm" variant="outline" onClick={() => { const next = { ...parameters }; delete next[name]; onParametersChange?.(next); }}>Remove unsupported parameter</Button></div>)}
  </fieldset>;
}
export function DeviceSelections({ nodes, selected, onChange, rankCount, reason, disabled = false }: {
  nodes: Node[]; selected: string[]; onChange: (selected: string[]) => void; rankCount?: number;
  reason?: (node: Node, rank: number) => string; disabled?: boolean;
}) {
  return <fieldset disabled={disabled} className="space-y-2"><legend className="mb-2 text-sm font-medium">{rankCount ? "Ranked target devices" : "Download devices"}</legend>{rankCount ? Array.from({ length: rankCount }, (_, rank) => <label key={rank} className="grid gap-1 text-sm"><span>{rank === 0 ? "Head · API" : `Worker ${rank}`}</span><select aria-label={`Rank ${rank} node`} className="control bg-panel p-2" value={selected[rank] || ""} onChange={(event) => { const next = [...selected]; next[rank] = event.target.value; onChange(next); }}><option value="">Select enrolled device</option>{nodes.map((node) => { const blocker = reason?.(node, rank) || (node.status !== "online" ? node.status : ""); return <option key={node.id} value={node.id} disabled={Boolean(blocker)}>{node.display_name}{blocker ? ` · ${blocker}` : ""}</option>; })}</select></label>) : nodes.map((node) => <label key={node.id} className="flex gap-2 border border-rule p-2 text-sm"><input type="checkbox" checked={selected.includes(node.id)} disabled={node.status !== "online"} onChange={() => onChange(selected.includes(node.id) ? selected.filter((id) => id !== node.id) : [...selected, node.id])} /><span>{node.display_name} · {node.status}<span className="block text-xs text-muted">Storage eligibility is checked separately from GPU occupancy and runtime suitability.</span></span></label>)}</fieldset>;
}
export function AcquisitionPlanDetails({ plan }: { plan: RecipeDownloadPlan }) {
  return <section className="space-y-3"><h3 className="font-medium">Required files and destinations</h3><div className="space-y-2">{plan.resources.map((resource) => <article key={resource.key} className="space-y-1 border border-rule p-3 text-xs"><p className="font-medium">{resource.kind} · {resource.action} · {resource.verification.state}{resource.verification.stale ? " (stale observation)" : ""}</p><p className="break-all font-mono">{resource.identity}</p><p className="break-all">Device {resource.node_id} · {resource.destination}{resource.platform ? ` · ${resource.platform}` : ""}</p><p>Remaining: {resource.bytes_remaining == null ? "Unknown" : bytes(resource.bytes_remaining)} · Total: {resource.bytes_total == null ? "Unknown" : bytes(resource.bytes_total)}</p>{resource.source_node ? <p>Copy from {resource.source_node}: {resource.source_path}</p> : null}{resource.credential_id ? <p>Selected credential: {resource.credential_id}</p> : null}{resource.verification.verified_at ? <p>Last checked: {resource.verification.verified_at}</p> : null}</article>)}</div>
    <h3 className="font-medium">Storage and staging</h3>{plan.storage.map((storage, index) => <article className="border border-rule p-3 text-xs" key={index}><p className="break-all">{storage.node_id} · {storage.destination}</p><p className="break-all">Filesystem: {storage.filesystem}</p><p>Available: {storage.available_bytes == null ? "Unknown" : bytes(storage.available_bytes)} · Required: {storage.required_bytes == null ? "Unknown" : bytes(storage.required_bytes)} · Staging: {storage.staging_bytes == null ? "Unknown" : bytes(storage.staging_bytes)} · Reserve: {bytes(storage.reserve_bytes)}</p><p>{storage.sufficient == null ? "Safe capacity is unknown; submission is blocked" : storage.sufficient ? "Storage capacity verified" : "Insufficient storage"}</p></article>)}
    {plan.diagnostics.map((diagnostic, index) => <p key={index} className={diagnostic.severity === "error" ? "text-sm text-fault" : "text-sm text-warning"}>{diagnostic.code}: {diagnostic.message}{diagnostic.resource ? ` (${diagnostic.resource})` : ""}</p>)}
  </section>;
}
export function LaunchPlanDetails({ plan }: { plan: DeploymentPlan }) {
  return <section className="space-y-3"><h3 className="font-medium">Run consequences</h3><p className="text-sm text-muted">Starting can create containers, run reviewed preparation and verification helpers, and apply declared host changes. Download completion alone does not prove hardware readiness or offline setup.</p>
    {plan.acquisition ? <AcquisitionPlanDetails plan={plan.acquisition} /> : null}
    {(plan.diagnostics || []).map((diagnostic, index) => <p key={index} className={diagnostic.severity === "error" ? "text-sm text-fault" : "text-sm text-warning"}>{diagnostic.code}: {diagnostic.message}{diagnostic.resource ? ` (${diagnostic.resource})` : ""}</p>)}
    <details><summary className="cursor-pointer text-sm">All ranks, conflicts, permissions, images and host consequences</summary><pre className="mt-2 max-h-96 overflow-auto text-xs">{JSON.stringify(plan, null, 2)}</pre></details>
  </section>;
}
