package ca

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"time"
)

// ParsePublicKeyPEM decodes a PEM-encoded SPKI (SubjectPublicKeyInfo)
// ECDSA P-256 public key, as generated by the agent at enrollment.
func ParsePublicKeyPEM(data []byte) (*ecdsa.PublicKey, error) {
	block, _ := pem.Decode(data)
	if block == nil || block.Type != "PUBLIC KEY" {
		return nil, fmt.Errorf("expected a PEM block of type PUBLIC KEY")
	}
	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse SPKI: %w", err)
	}
	eckey, ok := pub.(*ecdsa.PublicKey)
	if !ok || eckey.Curve != elliptic.P256() {
		return nil, fmt.Errorf("expected an ECDSA P-256 public key")
	}
	return eckey, nil
}

// NewKeyPEMs generates an ECDSA P-256 keypair as PEM blocks (agent side at
// enrollment). The private key stays on the node.
func NewKeyPEMs() (publicKeyPEM, privateKeyPEM []byte, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generate key: %w", err)
	}
	pubDER, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal public key: %w", err)
	}
	keyDER, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, nil, fmt.Errorf("marshal private key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER}),
		pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER}),
		nil
}

// NodeCertFor signs an agent-provided public key into a node certificate.
// The node ID is the subject CN (prefixed) and a DNS SAN; the hostname is an
// additional SAN when distinct.
func (c *CA) NodeCertFor(nodeID, hostname string, pub *ecdsa.PublicKey, validity time.Duration) (certPEM []byte, expires time.Time, err error) {
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, time.Time{}, err
	}
	notAfter := time.Now().UTC().Add(validity)
	names := []string{nodeID}
	if hostname != "" && hostname != nodeID {
		names = append(names, hostname)
	}
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: "lmw-node-" + nodeID, Organization: []string{"Local Model Works"}},
		NotBefore:    time.Now().UTC().Add(-time.Hour),
		NotAfter:     notAfter,
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth, x509.ExtKeyUsageServerAuth},
		DNSNames:     names,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, c.cert, pub, c.key)
	if err != nil {
		return nil, time.Time{}, fmt.Errorf("node cert: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}), notAfter, nil
}

// ServerCert mints the controller's own leaf certificate (name + IP SANs)
// for the agent and browser listeners. Minted per process; clients pin the
// CA, not the leaf.
func (c *CA) ServerCert(name string, ips []net.IP, validity time.Duration) (certPEM, keyPEM []byte, expires time.Time, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, time.Time{}, fmt.Errorf("server key: %w", err)
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, time.Time{}, err
	}
	notAfter := time.Now().UTC().Add(validity)
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: "lmw-server", Organization: []string{"Local Model Works"}},
		NotBefore:    time.Now().UTC().Add(-time.Hour),
		NotAfter:     notAfter,
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     []string{name},
		IPAddresses:  ips,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, c.cert, &key.PublicKey, c.key)
	if err != nil {
		return nil, nil, time.Time{}, fmt.Errorf("server cert: %w", err)
	}
	keyDER, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, nil, time.Time{}, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}),
		pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER}),
		notAfter, nil
}

// ClientTLSConfig builds the agent-side TLS config: the pinned CA is the
// only root, the SHA-256 fingerprint re-checks the exact certificate
// (defense in depth on top of the pool), and an optional node certificate
// enables mTLS.
func ClientTLSConfig(caPEM []byte, fingerprintHex string, clientCertPEM, clientKeyPEM []byte) (*tls.Config, error) {
	block, _ := pem.Decode(caPEM)
	if block == nil {
		return nil, fmt.Errorf("no PEM block in CA certificate")
	}
	caCert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse CA certificate: %w", err)
	}
	verifier, err := PinnedVerifier(caPEM, fingerprintHex)
	if err != nil {
		return nil, err
	}
	pool := x509.NewCertPool()
	pool.AddCert(caCert)
	cfg := &tls.Config{
		MinVersion: tls.VersionTLS13,
		RootCAs:    pool,
		// The pool already chains the server leaf to the pinned CA; the
		// fingerprint check re-validates the exact certificate as defense
		// in depth.
		VerifyConnection: func(cs tls.ConnectionState) error {
			if len(cs.PeerCertificates) == 0 {
				return fmt.Errorf("no peer certificate presented")
			}
			return verifier(cs.PeerCertificates[0], cs.VerifiedChains)
		},
	}
	if len(clientCertPEM) > 0 {
		pair, err := tls.X509KeyPair(clientCertPEM, clientKeyPEM)
		if err != nil {
			return nil, fmt.Errorf("client keypair: %w", err)
		}
		cfg.Certificates = []tls.Certificate{pair}
	}
	return cfg, nil
}
