// Command oapi merges the core API (api/openapi.yaml) with every first-party
// module's OpenAPI fragment (modules/<id>/<apiFragment>) into the public
// contract api/openapi.public.yaml, validates both documents with
// kin-openapi, and rewrites the output only when it changed. A duplicate
// path, component, or tag between the core and any fragment is a build error.
package main

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"gopkg.in/yaml.v3"

	"github.com/jj-link/local-model-works/internal/modules"
)

const (
	corePath   = "api/openapi.yaml"
	publicPath = "api/openapi.public.yaml"
	fragDir    = "modules"
)

var headerLines = []string{
	"# Code generated by \"go run ./internal/generate/oapi gen\". DO NOT EDIT.",
	"# Source: api/openapi.yaml (core) + modules/<id>/api.yaml fragments.",
}

func main() {
	root := "."
	args := os.Args[1:]
	if len(args) < 1 || args[0] != "gen" {
		fmt.Fprintln(os.Stderr, "usage: oapi gen [root]")
		os.Exit(2)
	}
	// Optional root override: merge against an alternate tree (tests). The
	// default "." keeps `go run ./internal/generate/oapi gen` unchanged.
	if len(args) > 1 {
		root = args[1]
	}
	if err := gen(root); err != nil {
		fmt.Fprintln(os.Stderr, "oapi:", err)
		os.Exit(1)
	}
}

func gen(root string) error {
	corePath := filepath.Join(root, "api/openapi.yaml")
	publicPath := filepath.Join(root, "api/openapi.public.yaml")
	core, err := loadMap(corePath)
	if err != nil {
		return err
	}
	if err := validateDoc(corePath, core); err != nil {
		return err
	}

	fragments, err := fragmentList(root)
	if err != nil {
		return err
	}
	for _, f := range fragments {
		frag, err := loadMap(f.path)
		if err != nil {
			return err
		}
		if err := merge(core, frag, f.module); err != nil {
			return err
		}
	}

	out, err := render(core)
	if err != nil {
		return err
	}
	if err := validateYAML(publicPath, out); err != nil {
		return err
	}
	if old, err := os.ReadFile(publicPath); err != nil || !bytes.Equal(old, out) {
		if err := os.WriteFile(publicPath, out, 0o644); err != nil {
			return err
		}
		fmt.Println("wrote", publicPath)
	} else {
		fmt.Println(publicPath, "up to date")
	}
	return generateGoContracts(root, core, fragments)
}

type fragment struct {
	module string
	path   string
}

// fragmentList returns the declared API fragments in ID-sorted order.
func fragmentList(root string) ([]fragment, error) {
	// The default build merges the fragments declared by the compiled
	// (frozen) registry. An explicit root reads the on-disk manifests so a
	// fixture tree can be merged without recompiling core.
	list := append([]modules.Manifest(nil), modules.Registry...)
	if root != "." {
		disk, err := onDiskFragments(root)
		if err != nil {
			return nil, err
		}
		list = disk
	}
	sort.Slice(list, func(i, j int) bool { return list[i].ID < list[j].ID })
	var out []fragment
	for _, m := range list {
		if m.APIFragment == "" {
			continue
		}
		out = append(out, fragment{module: m.ID, path: filepath.Join(root, "modules", m.ID, m.APIFragment)})
	}
	return out, nil
}

// onDiskFragments reads modules/<id>/module.yaml manifests directly from an
// alternate root (the fields the fragment merge needs). It is only used for
// explicit roots; the default build trusts the compiled registry.
func onDiskFragments(root string) ([]modules.Manifest, error) {
	dirs, err := os.ReadDir(filepath.Join(root, "modules"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read modules tree: %w", err)
	}
	var out []modules.Manifest
	for _, d := range dirs {
		if !d.IsDir() {
			continue
		}
		p := filepath.Join(root, "modules", d.Name(), "module.yaml")
		data, err := os.ReadFile(p)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		var dto struct {
			ID          string `yaml:"id"`
			APIFragment string `yaml:"apiFragment"`
		}
		dec := yaml.NewDecoder(bytes.NewReader(data))
		dec.KnownFields(false)
		if err := dec.Decode(&dto); err != nil {
			return nil, fmt.Errorf("parse %s: %w", p, err)
		}
		out = append(out, modules.Manifest{ID: dto.ID, APIFragment: dto.APIFragment})
	}
	return out, nil
}

func loadMap(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(false)
	if err := dec.Decode(&doc); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return doc, nil
}

// merge folds a fragment into the core document, refusing duplicates.
func merge(core, frag map[string]any, module string) error {
	if err := mergeMap(core, frag, "paths", module); err != nil {
		return err
	}
	comps, _ := core["components"].(map[string]any)
	if comps == nil {
		comps = map[string]any{}
		core["components"] = comps
	}
	fcomps, _ := frag["components"].(map[string]any)
	for _, sub := range []string{"parameters", "responses", "schemas"} {
		if err := mergeMap(comps, fcomps, sub, module); err != nil {
			return fmt.Errorf("components.%s: %w", sub, err)
		}
	}
	// Tags: core order first, then fragment tags in declaration order.
	coreTags, _ := core["tags"].([]any)
	tagNames := map[string]bool{}
	for _, t := range coreTags {
		if m, ok := t.(map[string]any); ok {
			if n, ok := m["name"].(string); ok {
				tagNames[n] = true
			}
		}
	}
	changed := false
	for _, t := range fragmentTags(frag) {
		n, _ := t["name"].(string)
		if n == "" || tagNames[n] {
			continue
		}
		tagNames[n] = true
		coreTags = append(coreTags, t)
		changed = true
	}
	if changed {
		core["tags"] = coreTags
	}
	return nil
}

// mergeMap adds src[srcKey] entries to dst[dstKey], erroring on duplicates.
func mergeMap(dst, src map[string]any, key, module string) error {
	if src == nil {
		return nil
	}
	d, _ := dst[key].(map[string]any)
	if d == nil {
		d = map[string]any{}
		dst[key] = d
	}
	s, _ := src[key].(map[string]any)
	if s == nil {
		return nil
	}
	for k, v := range s {
		if _, ok := d[k]; ok {
			return fmt.Errorf("module %s: duplicate %s %q", module, key, k)
		}
		d[k] = v
	}
	return nil
}

func fragmentTags(frag map[string]any) []map[string]any {
	var out []map[string]any
	list, _ := frag["tags"].([]any)
	for _, t := range list {
		if m, ok := t.(map[string]any); ok {
			out = append(out, m)
		}
	}
	return out
}

// render serializes the merged document with a fixed top-level key order;
// map keys within a section sort lexicographically (deterministic output).
func render(doc map[string]any) ([]byte, error) {
	out := &orderedDoc{
		OpenAPI: "3.1.0",
		Info:    doc["info"].(map[string]any),
		Servers: doc["servers"],
		Tags:    doc["tags"].([]any),
		Paths:   doc["paths"].(map[string]any),
		Components: orderedComponents{
			Parameters: mapSection(doc, "parameters"),
			Responses:  mapSection(doc, "responses"),
			Schemas:    mapSection(doc, "schemas"),
		},
	}
	var b bytes.Buffer
	b.WriteString(strings.Join(headerLines, "\n") + "\n")
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(out); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

type orderedDoc struct {
	OpenAPI    string            `yaml:"openapi"`
	Info       map[string]any    `yaml:"info"`
	Servers    any               `yaml:"servers"`
	Tags       []any             `yaml:"tags,omitempty"`
	Paths      map[string]any    `yaml:"paths"`
	Components orderedComponents `yaml:"components"`
}

type orderedComponents struct {
	Parameters map[string]any `yaml:"parameters,omitempty"`
	Responses  map[string]any `yaml:"responses,omitempty"`
	Schemas    map[string]any `yaml:"schemas,omitempty"`
}

func mapSection(doc map[string]any, key string) map[string]any {
	comps, _ := doc["components"].(map[string]any)
	if comps == nil {
		return nil
	}
	m, _ := comps[key].(map[string]any)
	return m
}

func generateGoContracts(root string, _ map[string]any, fragments []fragment) error {
	core, err := loadMap(filepath.Join(root, publicPath))
	if err != nil {
		return err
	}
	if err := runOAPICodegen(root, filepath.Join(root, corePath), "serverapi", filepath.Join(root, "internal", "serverapi", "openapi_gen.go")); err != nil {
		return err
	}
	coreComponents, _ := core["components"].(map[string]any)
	for _, fragment := range fragments {
		document, err := loadMap(fragment.path)
		if err != nil {
			return err
		}
		components, _ := document["components"].(map[string]any)
		if components == nil {
			components = map[string]any{}
			document["components"] = components
		}
		for _, section := range []string{"parameters", "responses", "schemas"} {
			target, _ := components[section].(map[string]any)
			if target == nil {
				target = map[string]any{}
				components[section] = target
			}
			source, _ := coreComponents[section].(map[string]any)
			for name, value := range source {
				if _, exists := target[name]; !exists {
					target[name] = value
				}
			}
		}
		raw, err := yaml.Marshal(document)
		if err != nil {
			return err
		}
		temp, err := os.CreateTemp(filepath.Dir(fragment.path), ".api-bundled-*.yaml")
		if err != nil {
			return err
		}
		tempPath := temp.Name()
		if _, err := temp.Write(raw); err != nil {
			temp.Close()
			os.Remove(tempPath)
			return err
		}
		if err := temp.Close(); err != nil {
			os.Remove(tempPath)
			return err
		}
		output := filepath.Join(root, "modules", fragment.module, "backend", "api_gen.go")
		err = runOAPICodegen(root, tempPath, "backend", output)
		os.Remove(tempPath)
		if err != nil {
			return err
		}
	}
	return nil
}

func runOAPICodegen(root, specPath, packageName, outputPath string) error {
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	command := exec.Command(
		"go", "run", "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0",
		"-generate", "types,chi-server", "-package", packageName,
		"-o", outputPath, specPath,
	)
	command.Dir = root
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("oapi-codegen %s: %w: %s", specPath, err, strings.TrimSpace(string(output)))
	}
	fmt.Println("wrote", outputPath)
	return nil
}

// validateDoc validates a raw YAML map as an OpenAPI document.
func validateDoc(name string, doc map[string]any) error {
	data, err := yaml.Marshal(doc)
	if err != nil {
		return err
	}
	return validateYAML(name, data)
}

func validateYAML(name string, data []byte) error {
	loader := openapi3.NewLoader()
	parsed, err := loader.LoadFromData(data)
	if err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}
	if err := parsed.Validate(context.Background()); err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}
	fmt.Printf("oapi: %s valid (%d paths, %d schemas)\n", name, len(parsed.Paths.Map()), len(parsed.Components.Schemas))
	return nil
}
