/* Shared immutable dataset for all three Library → Recipes UI samples.
   Mirrors the real list/detail fields surfaced in
   web/app/routes/library/recipes/index.tsx and $id.tsx. */
/* global LMX_RECIPES:readonly */
window.LMX_RECIPES = [
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash (DSpark 2× DGX Spark)",
    description: "Cluster-served DeepSeek V4 Flash across two DGX Spark nodes linked over RDMA fabric.",
    version: "1.0.0",
    version_count: 2,
    digest: "sha256:8f3b2c1a9d5e7b04c6a1f8e3d2b5c7a9f0e1d3b5c7a9f0e1d3b5c7a9f0e1d3b5c7",
    installed_at: "2026-08-14T20:11:00Z",
    installed: true,
    license: "Apache-2.0",
    source: {
      type: "git",
      remote: "https://git.example/dspark/deepseek-v4-flash",
      revision: "c4d5e6f7a8b9c0d1",
      reference: "",
      path: "recipes/deepseek-v4-flash/dspark-tp2/",
    },
    trust_state: "local",
    compatibility: { node_count: 2, rdma: true },
    profile_count: 1,
    variant_count: 2,
    artifact_count: 4,
    permissions: ["gpu", "rdma", "network"],
    high_risk: [],
    updates: [
      {
        version: "1.0.1",
        digest: "sha256:cb9a4e71f0d2b6c5a8e3f0d1c2b4a9e7f8d0c1b2a3e4f5c6d7e8f9a0b1c2d3e4",
        summary: "RDMA tuning; pinned NCCL settings for TP2",
      },
    ],
  },
  {
    id: "demo-rdma-pair",
    name: "Demo RDMA Pair",
    description: "Two-node demo workload exercising RDMA fabric paths between a verified reference pair.",
    version: "1.0.0",
    version_count: 1,
    digest: "sha256:0a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f9",
    installed_at: "2026-08-18T09:42:00Z",
    installed: true,
    license: "MIT",
    source: {
      type: "catalog",
      remote: "registry.example/catalog",
      revision: "",
      reference: "catalog-2026.08",
      path: "",
    },
    trust_state: "verified",
    compatibility: { node_count: 2, rdma: true },
    profile_count: 2,
    variant_count: 1,
    artifact_count: 2,
    permissions: ["gpu"],
    high_risk: [],
    updates: [],
  },
  {
    id: "lmw-demo-serve",
    name: "LMW Demo Serve",
    description: "Single-node serve recipe for a lightweight demo endpoint on the local workstation.",
    version: "1.0.0",
    version_count: 2,
    digest: "sha256:11aa22bb33cc44dd55ee66ff7788990011aa22bb33cc44dd55ee66ff77889900",
    installed_at: "2026-07-30T14:05:00Z",
    installed: true,
    license: "MIT",
    source: { type: "local", remote: "", revision: "", reference: "", path: "/DemoServe/" },
    trust_state: "local",
    compatibility: { node_count: 1, rdma: false },
    profile_count: 1,
    variant_count: 1,
    artifact_count: 1,
    permissions: ["gpu"],
    high_risk: [],
    updates: [{ version: "1.0.1", digest: "sha256:99f0e1d2c3b4a5968778ef0d1c2b3a4959687f6e5d4c3b2a1f0e9d8c7b6a5f4e", summary: "Updated serving image digest" }],
  },
  {
    id: "lmw-demo-profiles",
    name: "LMW Demo Profiles",
    description: "Single-node OCI-sourced recipe exposing three runtime profiles for capacity selection.",
    version: "1.0.0",
    version_count: 1,
    digest: "sha256:aa11bb22cc33dd44ee55ff6677889900aa11bb22cc33dd44ee55ff6677889900",
    installed_at: "2026-08-02T11:20:00Z",
    installed: true,
    license: "Apache-2.0",
    source: {
      type: "oci",
      remote: "registry.example/lmw/demo-profiles",
      revision: "",
      reference: "v1.0.0",
      path: "",
    },
    trust_state: "verified",
    compatibility: { node_count: 1, rdma: false },
    profile_count: 3,
    variant_count: 0,
    artifact_count: 2,
    permissions: ["storage"],
    high_risk: [],
    updates: [],
  },
  {
    id: "lmw-demo-git",
    name: "LMW Demo Git",
    description: "Pinned Git-sourced recipe requiring operator review before launch; unverified provenance.",
    version: "1.0.0",
    version_count: 1,
    digest: "sha256:bb22cc33dd44ee55ff6677889900aa11bb22cc33dd44ee55ff6677889900aa11",
    installed_at: "2026-08-09T16:33:00Z",
    installed: false,
    license: "BSD-3-Clause",
    source: {
      type: "git",
      remote: "https://git.example/lmw/demo-git",
      revision: "9f8e7d6c5b4a3f2e",
      reference: "",
      path: "/",
    },
    trust_state: "untrusted",
    compatibility: { node_count: 1, rdma: false },
    profile_count: 1,
    variant_count: 1,
    artifact_count: 1,
    permissions: ["network", "exec"],
    high_risk: ["exec"],
    updates: [],
  },
  {
    id: "lmw-demo-egress",
    name: "LMW Demo Egress",
    description: "Small single-node workload for exercising outbound network paths from a local host.",
    version: "1.0.0",
    version_count: 1,
    digest: "sha256:cc33dd44ee55ff6677889900aa11bb22cc33dd44ee55ff6677889900aa11bb",
    installed_at: "2026-08-11T08:02:00Z",
    installed: false,
    license: "MIT",
    source: { type: "local", remote: "", revision: "", reference: "", path: "/DemoEgress/" },
    trust_state: "local",
    compatibility: { node_count: 1, rdma: false },
    profile_count: 1,
    variant_count: 0,
    artifact_count: 1,
    permissions: ["gpu", "egress"],
    high_risk: ["egress"],
    updates: [],
  },
];
