// Code generated by protoc-gen-connect. DO NOT EDIT.
//
// Source: agent/v1/agent.proto

// Agent protocol for Local Model Works.
//
// EnrollmentService exchanges a one-use token for a node client certificate
// over a TLS connection pinned to the server CA fingerprint.
// AgentService.Session is the single bidirectional control channel.
// PeerTransferService carries resumable artifact bytes between enrolled
// agents over mTLS on the fabric address.
package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/jj-link/local-model-works/proto/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EnrollmentServiceName is the fully-qualified name of the EnrollmentService service.
	EnrollmentServiceName = "lmw.agent.v1.EnrollmentService"
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "lmw.agent.v1.AgentService"
	// PeerTransferServiceName is the fully-qualified name of the PeerTransferService service.
	PeerTransferServiceName = "lmw.agent.v1.PeerTransferService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EnrollmentServiceEnrollProcedure is the fully-qualified name of the EnrollmentService's Enroll
	// RPC.
	EnrollmentServiceEnrollProcedure = "/lmw.agent.v1.EnrollmentService/Enroll"
	// AgentServiceSessionProcedure is the fully-qualified name of the AgentService's Session RPC.
	AgentServiceSessionProcedure = "/lmw.agent.v1.AgentService/Session"
	// PeerTransferServiceManifestProcedure is the fully-qualified name of the PeerTransferService's
	// Manifest RPC.
	PeerTransferServiceManifestProcedure = "/lmw.agent.v1.PeerTransferService/Manifest"
	// PeerTransferServiceReadChunkProcedure is the fully-qualified name of the PeerTransferService's
	// ReadChunk RPC.
	PeerTransferServiceReadChunkProcedure = "/lmw.agent.v1.PeerTransferService/ReadChunk"
)

// EnrollmentServiceClient is a client for the lmw.agent.v1.EnrollmentService service.
type EnrollmentServiceClient interface {
	Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewEnrollmentServiceClient constructs a client for the lmw.agent.v1.EnrollmentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEnrollmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EnrollmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	enrollmentServiceMethods := v1.File_agent_v1_agent_proto.Services().ByName("EnrollmentService").Methods()
	return &enrollmentServiceClient{
		enroll: connect.NewClient[v1.EnrollRequest, v1.EnrollResponse](
			httpClient,
			baseURL+EnrollmentServiceEnrollProcedure,
			connect.WithSchema(enrollmentServiceMethods.ByName("Enroll")),
			connect.WithClientOptions(opts...),
		),
	}
}

// enrollmentServiceClient implements EnrollmentServiceClient.
type enrollmentServiceClient struct {
	enroll *connect.Client[v1.EnrollRequest, v1.EnrollResponse]
}

// Enroll calls lmw.agent.v1.EnrollmentService.Enroll.
func (c *enrollmentServiceClient) Enroll(ctx context.Context, req *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return c.enroll.CallUnary(ctx, req)
}

// EnrollmentServiceHandler is an implementation of the lmw.agent.v1.EnrollmentService service.
type EnrollmentServiceHandler interface {
	Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error)
}

// NewEnrollmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEnrollmentServiceHandler(svc EnrollmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	enrollmentServiceMethods := v1.File_agent_v1_agent_proto.Services().ByName("EnrollmentService").Methods()
	enrollmentServiceEnrollHandler := connect.NewUnaryHandler(
		EnrollmentServiceEnrollProcedure,
		svc.Enroll,
		connect.WithSchema(enrollmentServiceMethods.ByName("Enroll")),
		connect.WithHandlerOptions(opts...),
	)
	return "/lmw.agent.v1.EnrollmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EnrollmentServiceEnrollProcedure:
			enrollmentServiceEnrollHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEnrollmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEnrollmentServiceHandler struct{}

func (UnimplementedEnrollmentServiceHandler) Enroll(context.Context, *connect.Request[v1.EnrollRequest]) (*connect.Response[v1.EnrollResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lmw.agent.v1.EnrollmentService.Enroll is not implemented"))
}

// AgentServiceClient is a client for the lmw.agent.v1.AgentService service.
type AgentServiceClient interface {
	Session(context.Context) *connect.BidiStreamForClient[v1.AgentMessage, v1.ServerMessage]
}

// NewAgentServiceClient constructs a client for the lmw.agent.v1.AgentService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		session: connect.NewClient[v1.AgentMessage, v1.ServerMessage](
			httpClient,
			baseURL+AgentServiceSessionProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Session")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	session *connect.Client[v1.AgentMessage, v1.ServerMessage]
}

// Session calls lmw.agent.v1.AgentService.Session.
func (c *agentServiceClient) Session(ctx context.Context) *connect.BidiStreamForClient[v1.AgentMessage, v1.ServerMessage] {
	return c.session.CallBidiStream(ctx)
}

// AgentServiceHandler is an implementation of the lmw.agent.v1.AgentService service.
type AgentServiceHandler interface {
	Session(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ServerMessage]) error
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_agent_v1_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceSessionHandler := connect.NewBidiStreamHandler(
		AgentServiceSessionProcedure,
		svc.Session,
		connect.WithSchema(agentServiceMethods.ByName("Session")),
		connect.WithHandlerOptions(opts...),
	)
	return "/lmw.agent.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceSessionProcedure:
			agentServiceSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) Session(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ServerMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("lmw.agent.v1.AgentService.Session is not implemented"))
}

// PeerTransferServiceClient is a client for the lmw.agent.v1.PeerTransferService service.
type PeerTransferServiceClient interface {
	Manifest(context.Context, *connect.Request[v1.ManifestRequest]) (*connect.Response[v1.ManifestResponse], error)
	ReadChunk(context.Context, *connect.Request[v1.ReadChunkRequest]) (*connect.Response[v1.ReadChunkResponse], error)
}

// NewPeerTransferServiceClient constructs a client for the lmw.agent.v1.PeerTransferService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPeerTransferServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PeerTransferServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	peerTransferServiceMethods := v1.File_agent_v1_agent_proto.Services().ByName("PeerTransferService").Methods()
	return &peerTransferServiceClient{
		manifest: connect.NewClient[v1.ManifestRequest, v1.ManifestResponse](
			httpClient,
			baseURL+PeerTransferServiceManifestProcedure,
			connect.WithSchema(peerTransferServiceMethods.ByName("Manifest")),
			connect.WithClientOptions(opts...),
		),
		readChunk: connect.NewClient[v1.ReadChunkRequest, v1.ReadChunkResponse](
			httpClient,
			baseURL+PeerTransferServiceReadChunkProcedure,
			connect.WithSchema(peerTransferServiceMethods.ByName("ReadChunk")),
			connect.WithClientOptions(opts...),
		),
	}
}

// peerTransferServiceClient implements PeerTransferServiceClient.
type peerTransferServiceClient struct {
	manifest  *connect.Client[v1.ManifestRequest, v1.ManifestResponse]
	readChunk *connect.Client[v1.ReadChunkRequest, v1.ReadChunkResponse]
}

// Manifest calls lmw.agent.v1.PeerTransferService.Manifest.
func (c *peerTransferServiceClient) Manifest(ctx context.Context, req *connect.Request[v1.ManifestRequest]) (*connect.Response[v1.ManifestResponse], error) {
	return c.manifest.CallUnary(ctx, req)
}

// ReadChunk calls lmw.agent.v1.PeerTransferService.ReadChunk.
func (c *peerTransferServiceClient) ReadChunk(ctx context.Context, req *connect.Request[v1.ReadChunkRequest]) (*connect.Response[v1.ReadChunkResponse], error) {
	return c.readChunk.CallUnary(ctx, req)
}

// PeerTransferServiceHandler is an implementation of the lmw.agent.v1.PeerTransferService service.
type PeerTransferServiceHandler interface {
	Manifest(context.Context, *connect.Request[v1.ManifestRequest]) (*connect.Response[v1.ManifestResponse], error)
	ReadChunk(context.Context, *connect.Request[v1.ReadChunkRequest]) (*connect.Response[v1.ReadChunkResponse], error)
}

// NewPeerTransferServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPeerTransferServiceHandler(svc PeerTransferServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	peerTransferServiceMethods := v1.File_agent_v1_agent_proto.Services().ByName("PeerTransferService").Methods()
	peerTransferServiceManifestHandler := connect.NewUnaryHandler(
		PeerTransferServiceManifestProcedure,
		svc.Manifest,
		connect.WithSchema(peerTransferServiceMethods.ByName("Manifest")),
		connect.WithHandlerOptions(opts...),
	)
	peerTransferServiceReadChunkHandler := connect.NewUnaryHandler(
		PeerTransferServiceReadChunkProcedure,
		svc.ReadChunk,
		connect.WithSchema(peerTransferServiceMethods.ByName("ReadChunk")),
		connect.WithHandlerOptions(opts...),
	)
	return "/lmw.agent.v1.PeerTransferService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PeerTransferServiceManifestProcedure:
			peerTransferServiceManifestHandler.ServeHTTP(w, r)
		case PeerTransferServiceReadChunkProcedure:
			peerTransferServiceReadChunkHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPeerTransferServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPeerTransferServiceHandler struct{}

func (UnimplementedPeerTransferServiceHandler) Manifest(context.Context, *connect.Request[v1.ManifestRequest]) (*connect.Response[v1.ManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lmw.agent.v1.PeerTransferService.Manifest is not implemented"))
}

func (UnimplementedPeerTransferServiceHandler) ReadChunk(context.Context, *connect.Request[v1.ReadChunkRequest]) (*connect.Response[v1.ReadChunkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lmw.agent.v1.PeerTransferService.ReadChunk is not implemented"))
}
