// Package backend provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backend

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DeploymentDesiredState.
const (
	DeploymentDesiredStateRunning DeploymentDesiredState = "running"
	DeploymentDesiredStateStopped DeploymentDesiredState = "stopped"
)

// Valid indicates whether the value is a known member of the DeploymentDesiredState enum.
func (e DeploymentDesiredState) Valid() bool {
	switch e {
	case DeploymentDesiredStateRunning:
		return true
	case DeploymentDesiredStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentObservedState.
const (
	DeploymentObservedStateDegraded  DeploymentObservedState = "degraded"
	DeploymentObservedStateFailed    DeploymentObservedState = "failed"
	DeploymentObservedStateHealthy   DeploymentObservedState = "healthy"
	DeploymentObservedStatePreparing DeploymentObservedState = "preparing"
	DeploymentObservedStateStarting  DeploymentObservedState = "starting"
	DeploymentObservedStateStopped   DeploymentObservedState = "stopped"
	DeploymentObservedStateStopping  DeploymentObservedState = "stopping"
	DeploymentObservedStateUnknown   DeploymentObservedState = "unknown"
)

// Valid indicates whether the value is a known member of the DeploymentObservedState enum.
func (e DeploymentObservedState) Valid() bool {
	switch e {
	case DeploymentObservedStateDegraded:
		return true
	case DeploymentObservedStateFailed:
		return true
	case DeploymentObservedStateHealthy:
		return true
	case DeploymentObservedStatePreparing:
		return true
	case DeploymentObservedStateStarting:
		return true
	case DeploymentObservedStateStopped:
		return true
	case DeploymentObservedStateStopping:
		return true
	case DeploymentObservedStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for DiagnosticSeverity.
const (
	DiagnosticSeverityError   DiagnosticSeverity = "error"
	DiagnosticSeverityInfo    DiagnosticSeverity = "info"
	DiagnosticSeverityWarning DiagnosticSeverity = "warning"
)

// Valid indicates whether the value is a known member of the DiagnosticSeverity enum.
func (e DiagnosticSeverity) Valid() bool {
	switch e {
	case DiagnosticSeverityError:
		return true
	case DiagnosticSeverityInfo:
		return true
	case DiagnosticSeverityWarning:
		return true
	default:
		return false
	}
}

// Deployment defines model for Deployment.
type Deployment struct {
	CreatedAt    *time.Time             `json:"created_at,omitempty"`
	DesiredState DeploymentDesiredState `json:"desired_state"`
	Diagnostics  *[]Diagnostic          `json:"diagnostics,omitempty"`
	Endpoint     *struct {
		Host  *string `json:"host,omitempty"`
		Model *string `json:"model,omitempty"`
		Path  *string `json:"path,omitempty"`
		Port  *int    `json:"port,omitempty"`
	} `json:"endpoint,omitempty"`
	Engine            *string                 `json:"engine,omitempty"`
	Fabric            *string                 `json:"fabric,omitempty"`
	Id                openapi_types.UUID      `json:"id"`
	ModelCapabilities *map[string]interface{} `json:"model_capabilities,omitempty"`
	ObservedState     DeploymentObservedState `json:"observed_state"`
	Placements        *[]struct {
		AcceleratorIndex *int               `json:"accelerator_index,omitempty"`
		Container        *string            `json:"container,omitempty"`
		NodeId           openapi_types.UUID `json:"node_id"`
		NodeName         *string            `json:"node_name,omitempty"`
		Rank             int                `json:"rank"`
	} `json:"placements,omitempty"`
	Profile       string              `json:"profile"`
	RecipeDigest  string              `json:"recipe_digest"`
	RecipeName    *string             `json:"recipe_name,omitempty"`
	RecipeVersion *string             `json:"recipe_version,omitempty"`
	RunId         *openapi_types.UUID `json:"run_id,omitempty"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
}

// DeploymentDesiredState defines model for Deployment.DesiredState.
type DeploymentDesiredState string

// DeploymentObservedState defines model for Deployment.ObservedState.
type DeploymentObservedState string

// DeploymentCreateRequest defines model for DeploymentCreateRequest.
type DeploymentCreateRequest struct {
	Placements *[]struct {
		NodeId openapi_types.UUID `json:"node_id"`
		Rank   int                `json:"rank"`
	} `json:"placements,omitempty"`

	// PlanDigest Distinguishes an unchanged plan from the one previewed
	PlanDigest   *string `json:"plan_digest,omitempty"`
	Profile      string  `json:"profile"`
	RecipeDigest string  `json:"recipe_digest"`

	// Variants Optional artifact name -> selected model variant. Must match the previewed plan.
	Variants *map[string]string `json:"variants,omitempty"`
}

// DeploymentPlan defines model for DeploymentPlan.
type DeploymentPlan struct {
	Conflicts *[]struct {
		DeploymentId *openapi_types.UUID `json:"deployment_id,omitempty"`
		OccupiedBy   *string             `json:"occupied_by,omitempty"`
		Resource     *string             `json:"resource,omitempty"`
	} `json:"conflicts,omitempty"`
	Diagnostics *[]Diagnostic `json:"diagnostics,omitempty"`
	Endpoint    *struct {
		Host  *string `json:"host,omitempty"`
		Model *string `json:"model,omitempty"`
		Path  *string `json:"path,omitempty"`
		Port  *int    `json:"port,omitempty"`
	} `json:"endpoint,omitempty"`
	Fabric     *string `json:"fabric,omitempty"`
	Placements []struct {
		AcceleratorIndex int                `json:"accelerator_index"`
		AcceleratorUuid  *string            `json:"accelerator_uuid,omitempty"`
		NodeId           openapi_types.UUID `json:"node_id"`
		NodeName         *string            `json:"node_name,omitempty"`
		Rank             int                `json:"rank"`
	} `json:"placements"`

	// PlanDigest Opaque digest for this previewed plan; pass to create to pin it
	PlanDigest *string `json:"plan_digest,omitempty"`
	Ports      *[]struct {
		ContainerPort int                `json:"container_port"`
		HostPort      int                `json:"host_port"`
		NodeId        openapi_types.UUID `json:"node_id"`
		NodeName      *string            `json:"node_name,omitempty"`
		Protocol      *string            `json:"protocol,omitempty"`
	} `json:"ports,omitempty"`
	Profile string `json:"profile"`

	// Ready false when conflicts or unmet compatibility block creation
	Ready         bool               `json:"ready"`
	RecipeDigest  string             `json:"recipe_digest"`
	RecipeName    *string            `json:"recipe_name,omitempty"`
	RecipeVersion *string            `json:"recipe_version,omitempty"`
	Risks         *[]string          `json:"risks,omitempty"`
	Transfers     *[]TransferPreview `json:"transfers,omitempty"`

	// Variants Resolved per-artifact model variants
	Variants *map[string]string `json:"variants,omitempty"`

	// WorkloadIndex Workload identity for accelerator tuning
	WorkloadIndex *int `json:"workload_index,omitempty"`
}

// DeploymentPlanRequest defines model for DeploymentPlanRequest.
type DeploymentPlanRequest struct {
	// Placements Optional explicit node per rank; omit for automatic selection
	Placements *[]struct {
		NodeId openapi_types.UUID `json:"node_id"`
		Rank   int                `json:"rank"`
	} `json:"placements,omitempty"`
	Profile      string `json:"profile"`
	RecipeDigest string `json:"recipe_digest"`

	// Variants Optional artifact name -> selected model variant. Omit for the recipe default.
	Variants *map[string]string `json:"variants,omitempty"`
}

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Code     string             `json:"code"`
	Message  string             `json:"message"`
	Resource *string            `json:"resource,omitempty"`
	Severity DiagnosticSeverity `json:"severity"`
}

// DiagnosticSeverity defines model for Diagnostic.Severity.
type DiagnosticSeverity string

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable error code, e.g. node.occupied, plan.incompatible
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// TransferPreview defines model for TransferPreview.
type TransferPreview struct {
	ArtifactId openapi_types.UUID `json:"artifact_id"`
	Bytes      int64              `json:"bytes"`
	DestNode   string             `json:"dest_node"`
	DestPath   string             `json:"dest_path"`
	Identity   *string            `json:"identity,omitempty"`

	// Network Network path, e.g. fabric spark-p2p (roce), tailnet, local
	Network    *string `json:"network,omitempty"`
	SourceNode string  `json:"source_node"`
	SourcePath *string `json:"source_path,omitempty"`
}

// ID defines model for ID.
type ID = string

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// DeploymentLogsParams defines parameters for DeploymentLogs.
type DeploymentLogsParams struct {
	Rank *int `form:"rank,omitempty" json:"rank,omitempty"`
}

// CreateDeploymentJSONRequestBody defines body for CreateDeployment for application/json ContentType.
type CreateDeploymentJSONRequestBody = DeploymentCreateRequest

// PlanDeploymentJSONRequestBody defines body for PlanDeployment for application/json ContentType.
type PlanDeploymentJSONRequestBody = DeploymentPlanRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /deployments)
	ListDeployments(w http.ResponseWriter, r *http.Request)
	// CreateDeployment Create and start a deployment from a validated plan
	// (POST /deployments)
	CreateDeployment(w http.ResponseWriter, r *http.Request)
	// PlanDeployment Preview a deployment: placement, artifact preparation, ports, risks, conflicts
	// (POST /deployments/plan)
	PlanDeployment(w http.ResponseWriter, r *http.Request)
	// DeleteDeployment Delete a fully-stopped deployment and its runs, freeing the slot
	// (DELETE /deployments/{id})
	DeleteDeployment(w http.ResponseWriter, r *http.Request, id ID)

	// (GET /deployments/{id})
	GetDeployment(w http.ResponseWriter, r *http.Request, id ID)
	// DeploymentLogs Stream workload logs (SSE); byte-cursor resume via Last-Event-ID
	// (GET /deployments/{id}/logs)
	DeploymentLogs(w http.ResponseWriter, r *http.Request, id ID, params DeploymentLogsParams)
	// StartDeployment Restart a fully-stopped deployment, re-acquiring leases and re-dispatching
	// (POST /deployments/{id}/start)
	StartDeployment(w http.ResponseWriter, r *http.Request, id ID)
	// StopDeployment Stop exactly this deployment's workload (label-scoped)
	// (POST /deployments/{id}/stop)
	StopDeployment(w http.ResponseWriter, r *http.Request, id ID)
	// VerifyDeployment Run the recipe's verification probes against the live workload
	// (POST /deployments/{id}/verify)
	VerifyDeployment(w http.ResponseWriter, r *http.Request, id ID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /deployments)
func (_ Unimplemented) ListDeployments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateDeployment Create and start a deployment from a validated plan
// (POST /deployments)
func (_ Unimplemented) CreateDeployment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlanDeployment Preview a deployment: placement, artifact preparation, ports, risks, conflicts
// (POST /deployments/plan)
func (_ Unimplemented) PlanDeployment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteDeployment Delete a fully-stopped deployment and its runs, freeing the slot
// (DELETE /deployments/{id})
func (_ Unimplemented) DeleteDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /deployments/{id})
func (_ Unimplemented) GetDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeploymentLogs Stream workload logs (SSE); byte-cursor resume via Last-Event-ID
// (GET /deployments/{id}/logs)
func (_ Unimplemented) DeploymentLogs(w http.ResponseWriter, r *http.Request, id ID, params DeploymentLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StartDeployment Restart a fully-stopped deployment, re-acquiring leases and re-dispatching
// (POST /deployments/{id}/start)
func (_ Unimplemented) StartDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StopDeployment Stop exactly this deployment's workload (label-scoped)
// (POST /deployments/{id}/stop)
func (_ Unimplemented) StopDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyDeployment Run the recipe's verification probes against the live workload
// (POST /deployments/{id}/verify)
func (_ Unimplemented) VerifyDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDeployments operation middleware
func (siw *ServerInterfaceWrapper) ListDeployments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeployments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeployment operation middleware
func (siw *ServerInterfaceWrapper) CreateDeployment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeployment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlanDeployment operation middleware
func (siw *ServerInterfaceWrapper) PlanDeployment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlanDeployment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDeployment operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeployment operation middleware
func (siw *ServerInterfaceWrapper) GetDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeploymentLogs operation middleware
func (siw *ServerInterfaceWrapper) DeploymentLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeploymentLogsParams

	// ------------- Optional query parameter "rank" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rank", r.URL.Query(), &params.Rank, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "rank"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rank", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeploymentLogs(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartDeployment operation middleware
func (siw *ServerInterfaceWrapper) StartDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopDeployment operation middleware
func (siw *ServerInterfaceWrapper) StopDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyDeployment operation middleware
func (siw *ServerInterfaceWrapper) VerifyDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments", wrapper.ListDeployments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments", wrapper.CreateDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/deployments/{id}", wrapper.DeleteDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}", wrapper.GetDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}/logs", wrapper.DeploymentLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/start", wrapper.StartDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/stop", wrapper.StopDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/verify", wrapper.VerifyDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/plan", wrapper.PlanDeployment)
	})

	return r
}
