// Package backend provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backend

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DeploymentDesiredState.
const (
	DeploymentDesiredStateRunning DeploymentDesiredState = "running"
	DeploymentDesiredStateStopped DeploymentDesiredState = "stopped"
)

// Valid indicates whether the value is a known member of the DeploymentDesiredState enum.
func (e DeploymentDesiredState) Valid() bool {
	switch e {
	case DeploymentDesiredStateRunning:
		return true
	case DeploymentDesiredStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentObservedState.
const (
	DeploymentObservedStateDegraded  DeploymentObservedState = "degraded"
	DeploymentObservedStateFailed    DeploymentObservedState = "failed"
	DeploymentObservedStateHealthy   DeploymentObservedState = "healthy"
	DeploymentObservedStatePreparing DeploymentObservedState = "preparing"
	DeploymentObservedStateStarting  DeploymentObservedState = "starting"
	DeploymentObservedStateStopped   DeploymentObservedState = "stopped"
	DeploymentObservedStateStopping  DeploymentObservedState = "stopping"
	DeploymentObservedStateUnknown   DeploymentObservedState = "unknown"
)

// Valid indicates whether the value is a known member of the DeploymentObservedState enum.
func (e DeploymentObservedState) Valid() bool {
	switch e {
	case DeploymentObservedStateDegraded:
		return true
	case DeploymentObservedStateFailed:
		return true
	case DeploymentObservedStateHealthy:
		return true
	case DeploymentObservedStatePreparing:
		return true
	case DeploymentObservedStateStarting:
		return true
	case DeploymentObservedStateStopped:
		return true
	case DeploymentObservedStateStopping:
		return true
	case DeploymentObservedStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentCreateRequestAcquisitionPolicy.
const (
	DeploymentCreateRequestAcquisitionPolicyDownloadMissing DeploymentCreateRequestAcquisitionPolicy = "download-missing"
	DeploymentCreateRequestAcquisitionPolicyRequireExisting DeploymentCreateRequestAcquisitionPolicy = "require-existing"
)

// Valid indicates whether the value is a known member of the DeploymentCreateRequestAcquisitionPolicy enum.
func (e DeploymentCreateRequestAcquisitionPolicy) Valid() bool {
	switch e {
	case DeploymentCreateRequestAcquisitionPolicyDownloadMissing:
		return true
	case DeploymentCreateRequestAcquisitionPolicyRequireExisting:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentPlanAcquisitionPolicy.
const (
	DeploymentPlanAcquisitionPolicyDownloadMissing DeploymentPlanAcquisitionPolicy = "download-missing"
	DeploymentPlanAcquisitionPolicyRequireExisting DeploymentPlanAcquisitionPolicy = "require-existing"
)

// Valid indicates whether the value is a known member of the DeploymentPlanAcquisitionPolicy enum.
func (e DeploymentPlanAcquisitionPolicy) Valid() bool {
	switch e {
	case DeploymentPlanAcquisitionPolicyDownloadMissing:
		return true
	case DeploymentPlanAcquisitionPolicyRequireExisting:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentPlanRequestAcquisitionPolicy.
const (
	DeploymentPlanRequestAcquisitionPolicyDownloadMissing DeploymentPlanRequestAcquisitionPolicy = "download-missing"
	DeploymentPlanRequestAcquisitionPolicyRequireExisting DeploymentPlanRequestAcquisitionPolicy = "require-existing"
)

// Valid indicates whether the value is a known member of the DeploymentPlanRequestAcquisitionPolicy enum.
func (e DeploymentPlanRequestAcquisitionPolicy) Valid() bool {
	switch e {
	case DeploymentPlanRequestAcquisitionPolicyDownloadMissing:
		return true
	case DeploymentPlanRequestAcquisitionPolicyRequireExisting:
		return true
	default:
		return false
	}
}

// Defines values for DiagnosticSeverity.
const (
	DiagnosticSeverityError   DiagnosticSeverity = "error"
	DiagnosticSeverityInfo    DiagnosticSeverity = "info"
	DiagnosticSeverityWarning DiagnosticSeverity = "warning"
)

// Valid indicates whether the value is a known member of the DiagnosticSeverity enum.
func (e DiagnosticSeverity) Valid() bool {
	switch e {
	case DiagnosticSeverityError:
		return true
	case DiagnosticSeverityInfo:
		return true
	case DiagnosticSeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for ImagePreviewAction.
const (
	VerifyOrPull ImagePreviewAction = "verify-or-pull"
)

// Valid indicates whether the value is a known member of the ImagePreviewAction enum.
func (e ImagePreviewAction) Valid() bool {
	switch e {
	case VerifyOrPull:
		return true
	default:
		return false
	}
}

// Defines values for RecipeDownloadResourceAction.
const (
	RecipeDownloadResourceActionDownloadOrigin RecipeDownloadResourceAction = "download-origin"
	RecipeDownloadResourceActionPeerCopy       RecipeDownloadResourceAction = "peer-copy"
	RecipeDownloadResourceActionReuse          RecipeDownloadResourceAction = "reuse"
	RecipeDownloadResourceActionValidateLocal  RecipeDownloadResourceAction = "validate-local"
)

// Valid indicates whether the value is a known member of the RecipeDownloadResourceAction enum.
func (e RecipeDownloadResourceAction) Valid() bool {
	switch e {
	case RecipeDownloadResourceActionDownloadOrigin:
		return true
	case RecipeDownloadResourceActionPeerCopy:
		return true
	case RecipeDownloadResourceActionReuse:
		return true
	case RecipeDownloadResourceActionValidateLocal:
		return true
	default:
		return false
	}
}

// Defines values for RecipeDownloadResourceKind.
const (
	Artifact RecipeDownloadResourceKind = "artifact"
	Image    RecipeDownloadResourceKind = "image"
	Recipe   RecipeDownloadResourceKind = "recipe"
)

// Valid indicates whether the value is a known member of the RecipeDownloadResourceKind enum.
func (e RecipeDownloadResourceKind) Valid() bool {
	switch e {
	case Artifact:
		return true
	case Image:
		return true
	case Recipe:
		return true
	default:
		return false
	}
}

// Defines values for RecipeResourceVerificationState.
const (
	RecipeResourceVerificationStateAvailable RecipeResourceVerificationState = "available"
	RecipeResourceVerificationStateInvalid   RecipeResourceVerificationState = "invalid"
	RecipeResourceVerificationStateMissing   RecipeResourceVerificationState = "missing"
	RecipeResourceVerificationStatePartial   RecipeResourceVerificationState = "partial"
	RecipeResourceVerificationStateUnknown   RecipeResourceVerificationState = "unknown"
	RecipeResourceVerificationStateVerifying RecipeResourceVerificationState = "verifying"
)

// Valid indicates whether the value is a known member of the RecipeResourceVerificationState enum.
func (e RecipeResourceVerificationState) Valid() bool {
	switch e {
	case RecipeResourceVerificationStateAvailable:
		return true
	case RecipeResourceVerificationStateInvalid:
		return true
	case RecipeResourceVerificationStateMissing:
		return true
	case RecipeResourceVerificationStatePartial:
		return true
	case RecipeResourceVerificationStateUnknown:
		return true
	case RecipeResourceVerificationStateVerifying:
		return true
	default:
		return false
	}
}

// Defines values for RecipeUpdateRunningDeploymentPhase.
const (
	RecipeUpdateRunningDeploymentPhaseFetching         RecipeUpdateRunningDeploymentPhase = "fetching"
	RecipeUpdateRunningDeploymentPhaseInstallingRecipe RecipeUpdateRunningDeploymentPhase = "installing_recipe"
	RecipeUpdateRunningDeploymentPhasePreparing        RecipeUpdateRunningDeploymentPhase = "preparing"
	RecipeUpdateRunningDeploymentPhasePulling          RecipeUpdateRunningDeploymentPhase = "pulling"
	RecipeUpdateRunningDeploymentPhaseReady            RecipeUpdateRunningDeploymentPhase = "ready"
	RecipeUpdateRunningDeploymentPhaseRestored         RecipeUpdateRunningDeploymentPhase = "restored"
	RecipeUpdateRunningDeploymentPhaseRestoringOld     RecipeUpdateRunningDeploymentPhase = "restoring_old"
	RecipeUpdateRunningDeploymentPhaseRollbackFailed   RecipeUpdateRunningDeploymentPhase = "rollback_failed"
	RecipeUpdateRunningDeploymentPhaseRollingBack      RecipeUpdateRunningDeploymentPhase = "rolling_back"
	RecipeUpdateRunningDeploymentPhaseSkipped          RecipeUpdateRunningDeploymentPhase = "skipped"
	RecipeUpdateRunningDeploymentPhaseStarting         RecipeUpdateRunningDeploymentPhase = "starting"
	RecipeUpdateRunningDeploymentPhaseStoppingOld      RecipeUpdateRunningDeploymentPhase = "stopping_old"
	RecipeUpdateRunningDeploymentPhaseValidating       RecipeUpdateRunningDeploymentPhase = "validating"
	RecipeUpdateRunningDeploymentPhaseVerifying        RecipeUpdateRunningDeploymentPhase = "verifying"
	RecipeUpdateRunningDeploymentPhaseWaitingOffline   RecipeUpdateRunningDeploymentPhase = "waiting_offline"
)

// Valid indicates whether the value is a known member of the RecipeUpdateRunningDeploymentPhase enum.
func (e RecipeUpdateRunningDeploymentPhase) Valid() bool {
	switch e {
	case RecipeUpdateRunningDeploymentPhaseFetching:
		return true
	case RecipeUpdateRunningDeploymentPhaseInstallingRecipe:
		return true
	case RecipeUpdateRunningDeploymentPhasePreparing:
		return true
	case RecipeUpdateRunningDeploymentPhasePulling:
		return true
	case RecipeUpdateRunningDeploymentPhaseReady:
		return true
	case RecipeUpdateRunningDeploymentPhaseRestored:
		return true
	case RecipeUpdateRunningDeploymentPhaseRestoringOld:
		return true
	case RecipeUpdateRunningDeploymentPhaseRollbackFailed:
		return true
	case RecipeUpdateRunningDeploymentPhaseRollingBack:
		return true
	case RecipeUpdateRunningDeploymentPhaseSkipped:
		return true
	case RecipeUpdateRunningDeploymentPhaseStarting:
		return true
	case RecipeUpdateRunningDeploymentPhaseStoppingOld:
		return true
	case RecipeUpdateRunningDeploymentPhaseValidating:
		return true
	case RecipeUpdateRunningDeploymentPhaseVerifying:
		return true
	case RecipeUpdateRunningDeploymentPhaseWaitingOffline:
		return true
	default:
		return false
	}
}

// Defines values for RecipeUpdateRunningDeploymentStatus.
const (
	RecipeUpdateRunningDeploymentStatusFailed    RecipeUpdateRunningDeploymentStatus = "failed"
	RecipeUpdateRunningDeploymentStatusPending   RecipeUpdateRunningDeploymentStatus = "pending"
	RecipeUpdateRunningDeploymentStatusRunning   RecipeUpdateRunningDeploymentStatus = "running"
	RecipeUpdateRunningDeploymentStatusSucceeded RecipeUpdateRunningDeploymentStatus = "succeeded"
	RecipeUpdateRunningDeploymentStatusWaiting   RecipeUpdateRunningDeploymentStatus = "waiting"
)

// Valid indicates whether the value is a known member of the RecipeUpdateRunningDeploymentStatus enum.
func (e RecipeUpdateRunningDeploymentStatus) Valid() bool {
	switch e {
	case RecipeUpdateRunningDeploymentStatusFailed:
		return true
	case RecipeUpdateRunningDeploymentStatusPending:
		return true
	case RecipeUpdateRunningDeploymentStatusRunning:
		return true
	case RecipeUpdateRunningDeploymentStatusSucceeded:
		return true
	case RecipeUpdateRunningDeploymentStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for TransferPreviewAction.
const (
	TransferPreviewActionDownloadOrigin TransferPreviewAction = "download-origin"
	TransferPreviewActionPeerCopy       TransferPreviewAction = "peer-copy"
	TransferPreviewActionReconcileLocal TransferPreviewAction = "reconcile-local"
)

// Valid indicates whether the value is a known member of the TransferPreviewAction enum.
func (e TransferPreviewAction) Valid() bool {
	switch e {
	case TransferPreviewActionDownloadOrigin:
		return true
	case TransferPreviewActionPeerCopy:
		return true
	case TransferPreviewActionReconcileLocal:
		return true
	default:
		return false
	}
}

// Defines values for UpstreamExecutionPreviewExecutionConfigurationEditsFormat.
const (
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatArgv               UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "argv"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatArgvHeredoc        UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "argv-heredoc"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatArgvQuotedHeredoc  UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "argv-quoted-heredoc"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatFlag               UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "flag"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatFlagCompose        UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "flag-compose"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatJsonCompose        UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "json-compose"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatShell              UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "shell"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellCompose       UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "shell-compose"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellDoubleQuoted  UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "shell-double-quoted"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellHeredoc       UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "shell-heredoc"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellQuotedHeredoc UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "shell-quoted-heredoc"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellReparse       UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "shell-reparse"
	UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellWord          UpstreamExecutionPreviewExecutionConfigurationEditsFormat = "shell-word"
)

// Valid indicates whether the value is a known member of the UpstreamExecutionPreviewExecutionConfigurationEditsFormat enum.
func (e UpstreamExecutionPreviewExecutionConfigurationEditsFormat) Valid() bool {
	switch e {
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatArgv:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatArgvHeredoc:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatArgvQuotedHeredoc:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatFlag:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatFlagCompose:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatJsonCompose:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatShell:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellCompose:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellDoubleQuoted:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellHeredoc:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellQuotedHeredoc:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellReparse:
		return true
	case UpstreamExecutionPreviewExecutionConfigurationEditsFormatShellWord:
		return true
	default:
		return false
	}
}

// Defines values for UpstreamExecutionPreviewExecutionEnvFormat.
const (
	UpstreamExecutionPreviewExecutionEnvFormatLiteral UpstreamExecutionPreviewExecutionEnvFormat = "literal"
	UpstreamExecutionPreviewExecutionEnvFormatShell   UpstreamExecutionPreviewExecutionEnvFormat = "shell"
)

// Valid indicates whether the value is a known member of the UpstreamExecutionPreviewExecutionEnvFormat enum.
func (e UpstreamExecutionPreviewExecutionEnvFormat) Valid() bool {
	switch e {
	case UpstreamExecutionPreviewExecutionEnvFormatLiteral:
		return true
	case UpstreamExecutionPreviewExecutionEnvFormatShell:
		return true
	default:
		return false
	}
}

// Defines values for GetDeploymentTelemetryParamsResolution.
const (
	N1m GetDeploymentTelemetryParamsResolution = "1m"
	N5s GetDeploymentTelemetryParamsResolution = "5s"
)

// Valid indicates whether the value is a known member of the GetDeploymentTelemetryParamsResolution enum.
func (e GetDeploymentTelemetryParamsResolution) Valid() bool {
	switch e {
	case N1m:
		return true
	case N5s:
		return true
	default:
		return false
	}
}

// Deployment defines model for Deployment.
type Deployment struct {
	CreatedAt    *time.Time             `json:"created_at,omitempty"`
	DesiredState DeploymentDesiredState `json:"desired_state"`
	Diagnostics  *[]Diagnostic          `json:"diagnostics,omitempty"`
	Endpoint     *struct {
		Host  *string `json:"host,omitempty"`
		Model *string `json:"model,omitempty"`
		Path  *string `json:"path,omitempty"`
		Port  *int    `json:"port,omitempty"`
	} `json:"endpoint,omitempty"`
	Engine            *string                 `json:"engine,omitempty"`
	Fabric            *string                 `json:"fabric,omitempty"`
	Id                openapi_types.UUID      `json:"id"`
	ModelCapabilities *map[string]interface{} `json:"model_capabilities,omitempty"`
	ObservedState     DeploymentObservedState `json:"observed_state"`

	// Parameters Launch settings resolved at create time
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Placements *[]struct {
		AcceleratorIndex *int               `json:"accelerator_index,omitempty"`
		Container        *string            `json:"container,omitempty"`
		NodeId           openapi_types.UUID `json:"node_id"`
		NodeName         *string            `json:"node_name,omitempty"`
		Rank             int                `json:"rank"`
	} `json:"placements,omitempty"`
	RecipeDigest  string              `json:"recipe_digest"`
	RecipeName    *string             `json:"recipe_name,omitempty"`
	RecipeVersion *string             `json:"recipe_version,omitempty"`
	RunId         *openapi_types.UUID `json:"run_id,omitempty"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`

	// Variants Exact artifact variants selected for this deployment.
	Variants *map[string]string `json:"variants,omitempty"`

	// WorkloadIndex Exact runtime selected for this deployment, when recorded.
	WorkloadIndex *int `json:"workload_index,omitempty"`
}

// DeploymentDesiredState defines model for Deployment.DesiredState.
type DeploymentDesiredState string

// DeploymentObservedState defines model for Deployment.ObservedState.
type DeploymentObservedState string

// DeploymentConfigurationPlanRequest Explicit launch inputs for the deployment's current immutable recipe. Omitted values resolve declared defaults. Does not permit version, placement or fabric changes.
type DeploymentConfigurationPlanRequest struct {
	Parameters    *map[string]interface{} `json:"parameters,omitempty"`
	Variants      *map[string]string      `json:"variants,omitempty"`
	WorkloadIndex *int                    `json:"workload_index,omitempty"`
}

// DeploymentConfigurationRequest defines model for DeploymentConfigurationRequest.
type DeploymentConfigurationRequest struct {
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// PlanDigest Digest of the reviewed effective plan and live source deployment contract.
	PlanDigest    string             `json:"plan_digest"`
	Variants      *map[string]string `json:"variants,omitempty"`
	WorkloadIndex *int               `json:"workload_index,omitempty"`
}

// DeploymentCreateRequest defines model for DeploymentCreateRequest.
type DeploymentCreateRequest struct {
	AcquisitionPolicy *DeploymentCreateRequestAcquisitionPolicy `json:"acquisition_policy,omitempty"`

	// LaunchProfileId Saved profile to apply; mutually exclusive with variants/parameters
	LaunchProfileId *string `json:"launch_profile_id,omitempty"`

	// Parameters Optional parameter overrides; validated against the recipe manifest.
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Placements *[]struct {
		NodeId openapi_types.UUID `json:"node_id"`
		Rank   int                `json:"rank"`
	} `json:"placements,omitempty"`

	// PlanDigest Required digest of the explicitly reviewed plan, including its acquisition policy.
	PlanDigest   string `json:"plan_digest"`
	RecipeDigest string `json:"recipe_digest"`

	// Variants Optional artifact name -> selected model variant. Must match the previewed plan.
	Variants      *map[string]string `json:"variants,omitempty"`
	WorkloadIndex *int               `json:"workload_index,omitempty"`
}

// DeploymentCreateRequestAcquisitionPolicy defines model for DeploymentCreateRequest.AcquisitionPolicy.
type DeploymentCreateRequestAcquisitionPolicy string

// DeploymentPlan defines model for DeploymentPlan.
type DeploymentPlan struct {
	Acquisition *RecipeDownloadPlan `json:"acquisition,omitempty"`

	// AcquisitionPolicy Applies only to controller-managed resources; approved upstream scripts own their repository, dependency and model acquisition.
	AcquisitionPolicy DeploymentPlanAcquisitionPolicy `json:"acquisition_policy"`
	Conflicts         *[]struct {
		DeploymentId *openapi_types.UUID `json:"deployment_id,omitempty"`
		OccupiedBy   *string             `json:"occupied_by,omitempty"`
		Resource     *string             `json:"resource,omitempty"`
	} `json:"conflicts,omitempty"`
	Diagnostics *[]Diagnostic `json:"diagnostics,omitempty"`
	Endpoint    *struct {
		Host  *string `json:"host,omitempty"`
		Model *string `json:"model,omitempty"`
		Path  *string `json:"path,omitempty"`
		Port  *int    `json:"port,omitempty"`
	} `json:"endpoint,omitempty"`
	Fabric           *string                   `json:"fabric,omitempty"`
	HostPreparation  *[]HostPreparationPreview `json:"host_preparation,omitempty"`
	Images           *[]ImagePreview           `json:"images,omitempty"`
	MissingResources *[]RecipeDownloadResource `json:"missing_resources,omitempty"`

	// Parameters Effective launch parameters for this plan
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	Placements []struct {
		AcceleratorIndex int                `json:"accelerator_index"`
		AcceleratorUuid  *string            `json:"accelerator_uuid,omitempty"`
		NodeId           openapi_types.UUID `json:"node_id"`
		NodeName         *string            `json:"node_name,omitempty"`
		Rank             int                `json:"rank"`
	} `json:"placements"`

	// PlanDigest Opaque digest for this previewed plan; pass to create to pin it
	PlanDigest string `json:"plan_digest"`
	Ports      *[]struct {
		ContainerPort int                `json:"container_port"`
		HostPort      int                `json:"host_port"`
		NodeId        openapi_types.UUID `json:"node_id"`
		NodeName      *string            `json:"node_name,omitempty"`
		Protocol      *string            `json:"protocol,omitempty"`
	} `json:"ports,omitempty"`

	// Ready false when conflicts or unmet compatibility block creation
	Ready         bool                        `json:"ready"`
	RecipeDigest  string                      `json:"recipe_digest"`
	RecipeName    *string                     `json:"recipe_name,omitempty"`
	RecipeVersion *string                     `json:"recipe_version,omitempty"`
	Risks         *[]string                   `json:"risks,omitempty"`
	Storage       *[]StoragePreview           `json:"storage,omitempty"`
	Transfers     *[]TransferPreview          `json:"transfers,omitempty"`
	Upstream      *[]UpstreamExecutionPreview `json:"upstream,omitempty"`

	// Variants Resolved per-artifact model variants
	Variants *map[string]string `json:"variants,omitempty"`

	// WorkloadIndex Workload identity for accelerator tuning
	WorkloadIndex *int `json:"workload_index,omitempty"`
}

// DeploymentPlanAcquisitionPolicy Applies only to controller-managed resources; approved upstream scripts own their repository, dependency and model acquisition.
type DeploymentPlanAcquisitionPolicy string

// DeploymentPlanRequest defines model for DeploymentPlanRequest.
type DeploymentPlanRequest struct {
	// AcquisitionPolicy Require exact local resources, or acquire missing resources through shared downloads before launch.
	AcquisitionPolicy *DeploymentPlanRequestAcquisitionPolicy `json:"acquisition_policy,omitempty"`

	// LaunchProfileId Saved profile to apply; mutually exclusive with variants/parameters
	LaunchProfileId *string `json:"launch_profile_id,omitempty"`

	// Parameters Optional parameter overrides; validated against the recipe manifest.
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// Placements Optional explicit node per rank; omit for automatic selection
	Placements *[]struct {
		NodeId openapi_types.UUID `json:"node_id"`
		Rank   int                `json:"rank"`
	} `json:"placements,omitempty"`
	RecipeDigest string `json:"recipe_digest"`

	// Variants Optional artifact name -> selected model variant. Omit for the recipe default.
	Variants *map[string]string `json:"variants,omitempty"`

	// WorkloadIndex Optional explicit workload selection; otherwise selected from compatible fleet inventory.
	WorkloadIndex *int `json:"workload_index,omitempty"`
}

// DeploymentPlanRequestAcquisitionPolicy Require exact local resources, or acquire missing resources through shared downloads before launch.
type DeploymentPlanRequestAcquisitionPolicy string

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Code     string             `json:"code"`
	Message  string             `json:"message"`
	Resource *string            `json:"resource,omitempty"`
	Severity DiagnosticSeverity `json:"severity"`
}

// DiagnosticSeverity defines model for Diagnostic.Severity.
type DiagnosticSeverity string

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable error code, e.g. node.occupied, plan.incompatible
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// HostPreparationPreview defines model for HostPreparationPreview.
type HostPreparationPreview struct {
	DropPageCache     bool               `json:"drop_page_cache"`
	HelperImage       string             `json:"helper_image"`
	NodeId            openapi_types.UUID `json:"node_id"`
	NodeName          *string            `json:"node_name,omitempty"`
	RequireSwap       bool               `json:"require_swap"`
	SwapTotalBytes    *int64             `json:"swap_total_bytes,omitempty"`
	SwappinessCurrent int32              `json:"swappiness_current"`
	SwappinessTarget  *int32             `json:"swappiness_target,omitempty"`
}

// ImagePreview defines model for ImagePreview.
type ImagePreview struct {
	Action    ImagePreviewAction `json:"action"`
	Digest    string             `json:"digest"`
	NodeId    openapi_types.UUID `json:"node_id"`
	NodeName  *string            `json:"node_name,omitempty"`
	Reference string             `json:"reference"`
}

// ImagePreviewAction defines model for ImagePreview.Action.
type ImagePreviewAction string

// LaunchProfile defines model for LaunchProfile.
type LaunchProfile struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`

	// Parameters Optional parameter overrides (validated against the recipe)
	Parameters   *map[string]interface{} `json:"parameters,omitempty"`
	RecipeDigest string                  `json:"recipe_digest"`
	UpdatedAt    time.Time               `json:"updated_at"`

	// Variants Optional artifact name -> selected model variant
	Variants *map[string]string `json:"variants,omitempty"`
}

// LaunchProfileUpsert defines model for LaunchProfileUpsert.
type LaunchProfileUpsert struct {
	Name       string                  `json:"name"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// RecipeDigest Immutable digest pin; only honored on create
	RecipeDigest *string            `json:"recipe_digest,omitempty"`
	Variants     *map[string]string `json:"variants,omitempty"`
}

// RecipeDownloadPlan defines model for RecipeDownloadPlan.
type RecipeDownloadPlan struct {
	Diagnostics   []Diagnostic             `json:"diagnostics"`
	PlanDigest    string                   `json:"plan_digest"`
	Ready         bool                     `json:"ready"`
	RecipeDigest  string                   `json:"recipe_digest"`
	Resources     []RecipeDownloadResource `json:"resources"`
	Storage       []RecipeDownloadStorage  `json:"storage"`
	Targets       []RecipeDownloadTarget   `json:"targets"`
	Variants      map[string]string        `json:"variants"`
	WorkloadIndex int                      `json:"workload_index"`
}

// RecipeDownloadResource defines model for RecipeDownloadResource.
type RecipeDownloadResource struct {
	Action         RecipeDownloadResourceAction `json:"action"`
	BytesRemaining *int64                       `json:"bytes_remaining,omitempty"`
	BytesTotal     *int64                       `json:"bytes_total,omitempty"`
	CredentialId   *string                      `json:"credential_id,omitempty"`
	Destination    string                       `json:"destination"`
	Identity       string                       `json:"identity"`
	IndexDigest    *string                      `json:"index_digest,omitempty"`
	Key            string                       `json:"key"`
	Kind           RecipeDownloadResourceKind   `json:"kind"`
	ManifestDigest *string                      `json:"manifest_digest,omitempty"`
	NodeId         string                       `json:"node_id"`
	Platform       *string                      `json:"platform,omitempty"`
	Required       bool                         `json:"required"`
	SizeBytes      *int64                       `json:"size_bytes,omitempty"`
	Source         struct {
		Digest    *string `json:"digest,omitempty"`
		Reference *string `json:"reference,omitempty"`
		Revision  *string `json:"revision,omitempty"`
		Type      string  `json:"type"`
		Url       *string `json:"url,omitempty"`
	} `json:"source"`
	SourceNode   *string                    `json:"source_node,omitempty"`
	SourcePath   *string                    `json:"source_path,omitempty"`
	Verification RecipeResourceVerification `json:"verification"`
}

// RecipeDownloadResourceAction defines model for RecipeDownloadResource.Action.
type RecipeDownloadResourceAction string

// RecipeDownloadResourceKind defines model for RecipeDownloadResource.Kind.
type RecipeDownloadResourceKind string

// RecipeDownloadStorage defines model for RecipeDownloadStorage.
type RecipeDownloadStorage struct {
	AvailableBytes *int64   `json:"available_bytes,omitempty"`
	Destination    string   `json:"destination"`
	Filesystem     string   `json:"filesystem"`
	NodeId         string   `json:"node_id"`
	RequiredBytes  *int64   `json:"required_bytes,omitempty"`
	ReserveBytes   int64    `json:"reserve_bytes"`
	ResourceKeys   []string `json:"resource_keys"`
	StagingBytes   *int64   `json:"staging_bytes,omitempty"`
	Sufficient     *bool    `json:"sufficient,omitempty"`
	TotalBytes     *int64   `json:"total_bytes,omitempty"`
}

// RecipeDownloadTarget defines model for RecipeDownloadTarget.
type RecipeDownloadTarget struct {
	CacheRoot *string `json:"cache_root,omitempty"`
	NodeId    string  `json:"node_id"`
}

// RecipeResourceVerification defines model for RecipeResourceVerification.
type RecipeResourceVerification struct {
	Diagnostics *[]Diagnostic                   `json:"diagnostics,omitempty"`
	Stale       bool                            `json:"stale"`
	State       RecipeResourceVerificationState `json:"state"`
	VerifiedAt  *time.Time                      `json:"verified_at,omitempty"`
}

// RecipeResourceVerificationState defines model for RecipeResourceVerification.State.
type RecipeResourceVerificationState string

// RecipeUpdateAccepted defines model for RecipeUpdateAccepted.
type RecipeUpdateAccepted struct {
	RunId openapi_types.UUID `json:"run_id"`
}

// RecipeUpdateDevice defines model for RecipeUpdateDevice.
type RecipeUpdateDevice struct {
	InstalledDigests []string `json:"installed_digests"`
	NodeId           string   `json:"node_id"`
	NodeName         string   `json:"node_name"`
	NodeStatus       string   `json:"node_status"`
}

// RecipeUpdatePlan defines model for RecipeUpdatePlan.
type RecipeUpdatePlan struct {
	AddedPermissions     []string  `json:"added_permissions"`
	CandidatePermissions []string  `json:"candidate_permissions"`
	CurrentPermissions   []string  `json:"current_permissions"`
	DeploymentIds        *[]string `json:"deployment_ids,omitempty"`
	Deployments          *[]struct {
		AddedPermissions   []string                `json:"added_permissions"`
		CurrentPermissions []string                `json:"current_permissions"`
		DeploymentPlan     DeploymentPlan          `json:"deployment_plan"`
		Fabric             *string                 `json:"fabric,omitempty"`
		Parameters         *map[string]interface{} `json:"parameters,omitempty"`
		Placement          string                  `json:"placement"`
		RemovedPermissions []string                `json:"removed_permissions"`
		SourceDeploymentId string                  `json:"source_deployment_id"`
		SourceDigest       string                  `json:"source_digest"`

		// SourceWasStopped Rollback preserves the source deployment's stopped state instead of starting it.
		SourceWasStopped *bool              `json:"source_was_stopped,omitempty"`
		Variants         *map[string]string `json:"variants,omitempty"`
		WorkloadIndex    int                `json:"workload_index"`
	} `json:"deployments,omitempty"`
	Diagnostics            []Diagnostic                    `json:"diagnostics"`
	InstalledDevices       []RecipeUpdateDevice            `json:"installed_devices"`
	PlanDigest             string                          `json:"plan_digest"`
	Ready                  bool                            `json:"ready"`
	RemovedPermissions     []string                        `json:"removed_permissions"`
	RepositoryId           *string                         `json:"repository_id,omitempty"`
	RunningDeployments     []RecipeUpdateRunningDeployment `json:"running_deployments"`
	TargetDigest           *string                         `json:"target_digest,omitempty"`
	TargetVersion          *string                         `json:"target_version,omitempty"`
	UnchangedDeploymentIds *[]string                       `json:"unchanged_deployment_ids,omitempty"`

	// UpToDate Every installed device has completed package acquisition and any required source preparation for the frozen saved settings.
	UpToDate *bool `json:"up_to_date,omitempty"`
}

// RecipeUpdateRunningDeployment defines model for RecipeUpdateRunningDeployment.
type RecipeUpdateRunningDeployment struct {
	CurrentStep             int                                 `json:"current_step"`
	ErrorCode               *string                             `json:"error_code,omitempty"`
	ErrorMessage            *string                             `json:"error_message,omitempty"`
	NodeId                  string                              `json:"node_id"`
	NodeName                string                              `json:"node_name"`
	NodeStatus              string                              `json:"node_status"`
	Phase                   RecipeUpdateRunningDeploymentPhase  `json:"phase"`
	Rank                    int32                               `json:"rank"`
	ReplacementDeploymentId *string                             `json:"replacement_deployment_id,omitempty"`
	SourceDeploymentId      string                              `json:"source_deployment_id"`
	Status                  RecipeUpdateRunningDeploymentStatus `json:"status"`
	TotalSteps              int                                 `json:"total_steps"`
}

// RecipeUpdateRunningDeploymentPhase defines model for RecipeUpdateRunningDeployment.Phase.
type RecipeUpdateRunningDeploymentPhase string

// RecipeUpdateRunningDeploymentStatus defines model for RecipeUpdateRunningDeployment.Status.
type RecipeUpdateRunningDeploymentStatus string

// ResolvedSourceConfiguration defines model for ResolvedSourceConfiguration.
type ResolvedSourceConfiguration struct {
	Edits []struct {
		End         int    `json:"end"`
		Replacement string `json:"replacement"`
		Start       int    `json:"start"`
	} `json:"edits"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// ServingPayload defines model for ServingPayload.
type ServingPayload struct {
	Available           *bool    `json:"available,omitempty"`
	Backend             *string  `json:"backend,omitempty"`
	ContextLength       *int64   `json:"context_length,omitempty"`
	E2eP95Seconds       *float64 `json:"e2e_p95_seconds,omitempty"`
	Error               *string  `json:"error,omitempty"`
	ErrorCode           *string  `json:"error_code,omitempty"`
	GenerationTps       *float64 `json:"generation_tps,omitempty"`
	ItlP95Seconds       *float64 `json:"itl_p95_seconds,omitempty"`
	KvCacheUsageRatio   *float64 `json:"kv_cache_usage_ratio,omitempty"`
	ModelId             *string  `json:"model_id,omitempty"`
	PreemptionsTotal    *int64   `json:"preemptions_total,omitempty"`
	PrefillTps          *float64 `json:"prefill_tps,omitempty"`
	PrefixCacheHitRatio *float64 `json:"prefix_cache_hit_ratio,omitempty"`
	RequestsRunning     *int64   `json:"requests_running,omitempty"`
	RequestsWaiting     *int64   `json:"requests_waiting,omitempty"`
	SlotsActive         *int64   `json:"slots_active,omitempty"`
	SlotsTotal          *int64   `json:"slots_total,omitempty"`
	SpecAcceptanceRatio *float64 `json:"spec_acceptance_ratio,omitempty"`
	TtftP95Seconds      *float64 `json:"ttft_p95_seconds,omitempty"`
}

// ServingTelemetrySample defines model for ServingTelemetrySample.
type ServingTelemetrySample struct {
	DeploymentId openapi_types.UUID `json:"deployment_id"`
	Payload      ServingPayload     `json:"payload"`
	Ts           int64              `json:"ts"`
}

// StoragePreview defines model for StoragePreview.
type StoragePreview struct {
	AvailableBytes *int64             `json:"available_bytes,omitempty"`
	CacheRoot      *string            `json:"cache_root,omitempty"`
	Known          bool               `json:"known"`
	NodeId         openapi_types.UUID `json:"node_id"`
	NodeName       *string            `json:"node_name,omitempty"`
	RequiredBytes  int64              `json:"required_bytes"`
	Sufficient     bool               `json:"sufficient"`
	TotalBytes     *int64             `json:"total_bytes,omitempty"`
}

// TransferPreview defines model for TransferPreview.
type TransferPreview struct {
	Action     TransferPreviewAction `json:"action"`
	ArtifactId string                `json:"artifact_id"`

	// Bytes Known transfer bytes; omitted when the source size is unknown.
	Bytes    *int64  `json:"bytes,omitempty"`
	DestNode string  `json:"dest_node"`
	DestPath string  `json:"dest_path"`
	Identity *string `json:"identity,omitempty"`

	// Network Network path, e.g. fabric spark-p2p (roce), tailnet, local
	Network    *string `json:"network,omitempty"`
	SourceNode *string `json:"source_node,omitempty"`
	SourcePath *string `json:"source_path,omitempty"`
}

// TransferPreviewAction defines model for TransferPreview.Action.
type TransferPreviewAction string

// UpstreamExecutionPreview Pinned upstream lifecycle, environment and explicit runtime-configuration adaptations approved for this node.
type UpstreamExecutionPreview struct {
	Configuration *[]ResolvedSourceConfiguration `json:"configuration,omitempty"`
	Environment   *map[string]string             `json:"environment,omitempty"`
	Execution     struct {
		AuxiliaryContainers *[]string `json:"auxiliaryContainers,omitempty"`
		Configuration       *[]struct {
			Edits []struct {
				Command   *string                                                   `json:"command,omitempty"`
				End       int                                                       `json:"end"`
				Flag      *string                                                   `json:"flag,omitempty"`
				Format    UpstreamExecutionPreviewExecutionConfigurationEditsFormat `json:"format"`
				Indirect  *bool                                                     `json:"indirect,omitempty"`
				Parameter *string                                                   `json:"parameter,omitempty"`
				Prefix    *string                                                   `json:"prefix,omitempty"`
				Start     int                                                       `json:"start"`
				Suffix    *string                                                   `json:"suffix,omitempty"`
				Template  *string                                                   `json:"template,omitempty"`
				Variable  *string                                                   `json:"variable,omitempty"`
			} `json:"edits"`
			Path   string `json:"path"`
			Sha256 string `json:"sha256"`
		} `json:"configuration,omitempty"`
		Containers []string `json:"containers"`

		// CoordinatorRank Only the head executes start/stop; other ranks finish their per-node install and independently observe its service.
		CoordinatorRank *int                                        `json:"coordinatorRank,omitempty"`
		EnvFile         *string                                     `json:"envFile,omitempty"`
		EnvFormat       *UpstreamExecutionPreviewExecutionEnvFormat `json:"envFormat,omitempty"`
		EnvTemplate     *string                                     `json:"envTemplate,omitempty"`
		Install         *[][]string                                 `json:"install,omitempty"`
		LogFile         *string                                     `json:"logFile,omitempty"`
		Start           []string                                    `json:"start"`
		Stop            []string                                    `json:"stop"`
	} `json:"execution"`
	NodeId   openapi_types.UUID `json:"node_id"`
	NodeName *string            `json:"node_name,omitempty"`
	Rank     int                `json:"rank"`
	Source   struct {
		Path      *string `json:"path,omitempty"`
		Procedure *string `json:"procedure,omitempty"`
		Revision  string  `json:"revision"`
		Url       string  `json:"url"`
	} `json:"source"`
}

// UpstreamExecutionPreviewExecutionConfigurationEditsFormat defines model for UpstreamExecutionPreview.Execution.Configuration.Edits.Format.
type UpstreamExecutionPreviewExecutionConfigurationEditsFormat string

// UpstreamExecutionPreviewExecutionEnvFormat defines model for UpstreamExecutionPreview.Execution.EnvFormat.
type UpstreamExecutionPreviewExecutionEnvFormat string

// ID defines model for ID.
type ID = string

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// DeploymentLogsParams defines parameters for DeploymentLogs.
type DeploymentLogsParams struct {
	Rank *int `form:"rank,omitempty" json:"rank,omitempty"`
}

// GetDeploymentTelemetryParams defines parameters for GetDeploymentTelemetry.
type GetDeploymentTelemetryParams struct {
	Resolution *GetDeploymentTelemetryParamsResolution `form:"resolution,omitempty" json:"resolution,omitempty"`
	From       *int64                                  `form:"from,omitempty" json:"from,omitempty"`
	To         *int64                                  `form:"to,omitempty" json:"to,omitempty"`
	Limit      *int                                    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetDeploymentTelemetryParamsResolution defines parameters for GetDeploymentTelemetry.
type GetDeploymentTelemetryParamsResolution string

// CreateDeploymentJSONRequestBody defines body for CreateDeployment for application/json ContentType.
type CreateDeploymentJSONRequestBody = DeploymentCreateRequest

// PlanDeploymentJSONRequestBody defines body for PlanDeployment for application/json ContentType.
type PlanDeploymentJSONRequestBody = DeploymentPlanRequest

// ApplyDeploymentConfigurationJSONRequestBody defines body for ApplyDeploymentConfiguration for application/json ContentType.
type ApplyDeploymentConfigurationJSONRequestBody = DeploymentConfigurationRequest

// PlanDeploymentConfigurationJSONRequestBody defines body for PlanDeploymentConfiguration for application/json ContentType.
type PlanDeploymentConfigurationJSONRequestBody = DeploymentConfigurationPlanRequest

// UpdateLaunchProfileJSONRequestBody defines body for UpdateLaunchProfile for application/json ContentType.
type UpdateLaunchProfileJSONRequestBody = LaunchProfileUpsert

// CreateLaunchProfileJSONRequestBody defines body for CreateLaunchProfile for application/json ContentType.
type CreateLaunchProfileJSONRequestBody = LaunchProfileUpsert

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /deployments)
	ListDeployments(w http.ResponseWriter, r *http.Request)
	// CreateDeployment Create and start a deployment from a validated plan
	// (POST /deployments)
	CreateDeployment(w http.ResponseWriter, r *http.Request)
	// PlanDeployment Preview a deployment: placement, artifact preparation, ports, risks, conflicts
	// (POST /deployments/plan)
	PlanDeployment(w http.ResponseWriter, r *http.Request)
	// ListDeploymentTelemetry Latest typed serving telemetry sample per deployment
	// (GET /deployments/telemetry)
	ListDeploymentTelemetry(w http.ResponseWriter, r *http.Request)
	// DeleteDeployment Delete a fully-stopped deployment and its runs, freeing the slot
	// (DELETE /deployments/{id})
	DeleteDeployment(w http.ResponseWriter, r *http.Request, id ID)

	// (GET /deployments/{id})
	GetDeployment(w http.ResponseWriter, r *http.Request, id ID)
	// ApplyDeploymentConfiguration Apply reviewed configuration using source-state-aware replacement and rollback
	// (POST /deployments/{id}/configuration)
	ApplyDeploymentConfiguration(w http.ResponseWriter, r *http.Request, id ID)
	// PlanDeploymentConfiguration Review same-recipe configuration without requiring repository ownership
	// (POST /deployments/{id}/configuration/plan)
	PlanDeploymentConfiguration(w http.ResponseWriter, r *http.Request, id ID)
	// DeploymentLogs Stream workload logs (SSE); byte-cursor resume via Last-Event-ID
	// (GET /deployments/{id}/logs)
	DeploymentLogs(w http.ResponseWriter, r *http.Request, id ID, params DeploymentLogsParams)
	// StartDeployment Restart a fully-stopped deployment, re-acquiring leases and re-dispatching
	// (POST /deployments/{id}/start)
	StartDeployment(w http.ResponseWriter, r *http.Request, id ID)
	// StopDeployment Stop exactly this deployment's workload (label-scoped)
	// (POST /deployments/{id}/stop)
	StopDeployment(w http.ResponseWriter, r *http.Request, id ID)
	// GetDeploymentTelemetry Ranged serving telemetry history for one deployment
	// (GET /deployments/{id}/telemetry)
	GetDeploymentTelemetry(w http.ResponseWriter, r *http.Request, id ID, params GetDeploymentTelemetryParams)
	// VerifyDeployment Run the recipe's verification probes against the live workload
	// (POST /deployments/{id}/verify)
	VerifyDeployment(w http.ResponseWriter, r *http.Request, id ID)
	// DeleteLaunchProfile Delete an operator-owned launch profile
	// (DELETE /launch-profiles/{id})
	DeleteLaunchProfile(w http.ResponseWriter, r *http.Request, id string)
	// UpdateLaunchProfile Replace an operator-owned launch profile (digest pinned)
	// (PUT /launch-profiles/{id})
	UpdateLaunchProfile(w http.ResponseWriter, r *http.Request, id string)
	// ListLaunchProfiles Saved launch profiles for one recipe digest
	// (GET /recipes/{digest}/launch-profiles)
	ListLaunchProfiles(w http.ResponseWriter, r *http.Request, digest string)
	// CreateLaunchProfile Save an operator-owned launch profile for this recipe digest
	// (POST /recipes/{digest}/launch-profiles)
	CreateLaunchProfile(w http.ResponseWriter, r *http.Request, digest string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /deployments)
func (_ Unimplemented) ListDeployments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateDeployment Create and start a deployment from a validated plan
// (POST /deployments)
func (_ Unimplemented) CreateDeployment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlanDeployment Preview a deployment: placement, artifact preparation, ports, risks, conflicts
// (POST /deployments/plan)
func (_ Unimplemented) PlanDeployment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListDeploymentTelemetry Latest typed serving telemetry sample per deployment
// (GET /deployments/telemetry)
func (_ Unimplemented) ListDeploymentTelemetry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteDeployment Delete a fully-stopped deployment and its runs, freeing the slot
// (DELETE /deployments/{id})
func (_ Unimplemented) DeleteDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /deployments/{id})
func (_ Unimplemented) GetDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApplyDeploymentConfiguration Apply reviewed configuration using source-state-aware replacement and rollback
// (POST /deployments/{id}/configuration)
func (_ Unimplemented) ApplyDeploymentConfiguration(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PlanDeploymentConfiguration Review same-recipe configuration without requiring repository ownership
// (POST /deployments/{id}/configuration/plan)
func (_ Unimplemented) PlanDeploymentConfiguration(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeploymentLogs Stream workload logs (SSE); byte-cursor resume via Last-Event-ID
// (GET /deployments/{id}/logs)
func (_ Unimplemented) DeploymentLogs(w http.ResponseWriter, r *http.Request, id ID, params DeploymentLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StartDeployment Restart a fully-stopped deployment, re-acquiring leases and re-dispatching
// (POST /deployments/{id}/start)
func (_ Unimplemented) StartDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StopDeployment Stop exactly this deployment's workload (label-scoped)
// (POST /deployments/{id}/stop)
func (_ Unimplemented) StopDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDeploymentTelemetry Ranged serving telemetry history for one deployment
// (GET /deployments/{id}/telemetry)
func (_ Unimplemented) GetDeploymentTelemetry(w http.ResponseWriter, r *http.Request, id ID, params GetDeploymentTelemetryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyDeployment Run the recipe's verification probes against the live workload
// (POST /deployments/{id}/verify)
func (_ Unimplemented) VerifyDeployment(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteLaunchProfile Delete an operator-owned launch profile
// (DELETE /launch-profiles/{id})
func (_ Unimplemented) DeleteLaunchProfile(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateLaunchProfile Replace an operator-owned launch profile (digest pinned)
// (PUT /launch-profiles/{id})
func (_ Unimplemented) UpdateLaunchProfile(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListLaunchProfiles Saved launch profiles for one recipe digest
// (GET /recipes/{digest}/launch-profiles)
func (_ Unimplemented) ListLaunchProfiles(w http.ResponseWriter, r *http.Request, digest string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateLaunchProfile Save an operator-owned launch profile for this recipe digest
// (POST /recipes/{digest}/launch-profiles)
func (_ Unimplemented) CreateLaunchProfile(w http.ResponseWriter, r *http.Request, digest string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDeployments operation middleware
func (siw *ServerInterfaceWrapper) ListDeployments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeployments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeployment operation middleware
func (siw *ServerInterfaceWrapper) CreateDeployment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeployment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlanDeployment operation middleware
func (siw *ServerInterfaceWrapper) PlanDeployment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlanDeployment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeploymentTelemetry operation middleware
func (siw *ServerInterfaceWrapper) ListDeploymentTelemetry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeploymentTelemetry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDeployment operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeployment operation middleware
func (siw *ServerInterfaceWrapper) GetDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyDeploymentConfiguration operation middleware
func (siw *ServerInterfaceWrapper) ApplyDeploymentConfiguration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyDeploymentConfiguration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlanDeploymentConfiguration operation middleware
func (siw *ServerInterfaceWrapper) PlanDeploymentConfiguration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlanDeploymentConfiguration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeploymentLogs operation middleware
func (siw *ServerInterfaceWrapper) DeploymentLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeploymentLogsParams

	// ------------- Optional query parameter "rank" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rank", r.URL.Query(), &params.Rank, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "rank"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rank", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeploymentLogs(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartDeployment operation middleware
func (siw *ServerInterfaceWrapper) StartDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopDeployment operation middleware
func (siw *ServerInterfaceWrapper) StopDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeploymentTelemetry operation middleware
func (siw *ServerInterfaceWrapper) GetDeploymentTelemetry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeploymentTelemetryParams

	// ------------- Optional query parameter "resolution" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "resolution", r.URL.Query(), &params.Resolution, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resolution"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resolution", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeploymentTelemetry(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyDeployment operation middleware
func (siw *ServerInterfaceWrapper) VerifyDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLaunchProfile operation middleware
func (siw *ServerInterfaceWrapper) DeleteLaunchProfile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLaunchProfile(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLaunchProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateLaunchProfile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLaunchProfile(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLaunchProfiles operation middleware
func (siw *ServerInterfaceWrapper) ListLaunchProfiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "digest" -------------
	var digest string

	err = runtime.BindStyledParameterWithOptions("simple", "digest", chi.URLParam(r, "digest"), &digest, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "digest", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLaunchProfiles(w, r, digest)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLaunchProfile operation middleware
func (siw *ServerInterfaceWrapper) CreateLaunchProfile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "digest" -------------
	var digest string

	err = runtime.BindStyledParameterWithOptions("simple", "digest", chi.URLParam(r, "digest"), &digest, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "digest", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLaunchProfile(w, r, digest)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments", wrapper.ListDeployments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments", wrapper.CreateDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/deployments/{id}", wrapper.DeleteDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}", wrapper.GetDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/configuration", wrapper.ApplyDeploymentConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/configuration/plan", wrapper.PlanDeploymentConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}/logs", wrapper.DeploymentLogs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/start", wrapper.StartDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/stop", wrapper.StopDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}/telemetry", wrapper.GetDeploymentTelemetry)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/{id}/verify", wrapper.VerifyDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/deployments/plan", wrapper.PlanDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/telemetry", wrapper.ListDeploymentTelemetry)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/launch-profiles/{id}", wrapper.DeleteLaunchProfile)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/launch-profiles/{id}", wrapper.UpdateLaunchProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recipes/{digest}/launch-profiles", wrapper.ListLaunchProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/recipes/{digest}/launch-profiles", wrapper.CreateLaunchProfile)
	})

	return r
}
