// Code generated by "go run ./internal/generate/modules gen". DO NOT EDIT.
// Source: modules/serving/module.yaml

package backend

import (
	"encoding/json"

	"github.com/jj-link/local-model-works/internal/moduleapi"
)

// descriptor is this module's frozen manifest.
var descriptor = moduleapi.Descriptor{APIVersion: "localmodelworks/v1alpha1", Kind: "Module", ID: "serving", Title: "Serving", Route: "/serving", Nav: moduleapi.Nav{Label: "Serving", Order: 30, Icon: "serving"}, SettingsSchema: json.RawMessage("{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"additionalProperties\":false,\"properties\":{\"verify_timeout_seconds\":{\"maximum\":600,\"minimum\":5,\"type\":\"integer\"}},\"type\":\"object\"}"), JobKinds: []string{"serve", "stop"}, ArtifactKinds: []string{"model"}, APIFragment: "api.yaml", Capabilities: []string{"deployments.write", "runs.create", "nodes.read", "transfers.write", "secrets.read", "events.publish"}}
