// Package backend provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backend

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SecretPurpose.
const (
	SecretPurposeGithub        SecretPurpose = "github"
	SecretPurposeHuggingface   SecretPurpose = "huggingface"
	SecretPurposeModelProvider SecretPurpose = "model_provider"
	SecretPurposeRegistry      SecretPurpose = "registry"
	SecretPurposeSsh           SecretPurpose = "ssh"
)

// Valid indicates whether the value is a known member of the SecretPurpose enum.
func (e SecretPurpose) Valid() bool {
	switch e {
	case SecretPurposeGithub:
		return true
	case SecretPurposeHuggingface:
		return true
	case SecretPurposeModelProvider:
		return true
	case SecretPurposeRegistry:
		return true
	case SecretPurposeSsh:
		return true
	default:
		return false
	}
}

// Defines values for SecretWritePurpose.
const (
	SecretWritePurposeGithub        SecretWritePurpose = "github"
	SecretWritePurposeHuggingface   SecretWritePurpose = "huggingface"
	SecretWritePurposeModelProvider SecretWritePurpose = "model_provider"
	SecretWritePurposeRegistry      SecretWritePurpose = "registry"
	SecretWritePurposeSsh           SecretWritePurpose = "ssh"
)

// Valid indicates whether the value is a known member of the SecretWritePurpose enum.
func (e SecretWritePurpose) Valid() bool {
	switch e {
	case SecretWritePurposeGithub:
		return true
	case SecretWritePurposeHuggingface:
		return true
	case SecretWritePurposeModelProvider:
		return true
	case SecretWritePurposeRegistry:
		return true
	case SecretWritePurposeSsh:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable error code, e.g. node.occupied, plan.incompatible
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ModuleSettings defines model for ModuleSettings.
type ModuleSettings struct {
	Module   string                 `json:"module"`
	Settings map[string]interface{} `json:"settings"`

	// Version ETag for optimistic concurrency
	Version string `json:"version"`
}

// Secret defines model for Secret.
type Secret struct {
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Purpose   SecretPurpose      `json:"purpose"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// SecretPurpose defines model for Secret.Purpose.
type SecretPurpose string

// SecretWrite defines model for SecretWrite.
type SecretWrite struct {
	Name    string             `json:"name"`
	Purpose SecretWritePurpose `json:"purpose"`
	Value   string             `json:"value"`
}

// SecretWritePurpose defines model for SecretWrite.Purpose.
type SecretWritePurpose string

// ID defines model for ID.
type ID = string

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// PutModuleSettingsParams defines parameters for PutModuleSettings.
type PutModuleSettingsParams struct {
	IfMatch string `json:"If-Match"`
}

// PutModuleSettingsJSONRequestBody defines body for PutModuleSettings for application/json ContentType.
type PutModuleSettingsJSONRequestBody = ModuleSettings

// PutSecretJSONRequestBody defines body for PutSecret for application/json ContentType.
type PutSecretJSONRequestBody = SecretWrite

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /modules/{id}/settings)
	GetModuleSettings(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /modules/{id}/settings)
	PutModuleSettings(w http.ResponseWriter, r *http.Request, id string, params PutModuleSettingsParams)

	// (GET /secrets)
	ListSecrets(w http.ResponseWriter, r *http.Request)
	// PutSecret Create or replace a secret value (AES-256-GCM encrypted at rest)
	// (POST /secrets)
	PutSecret(w http.ResponseWriter, r *http.Request)

	// (DELETE /secrets/{id})
	DeleteSecret(w http.ResponseWriter, r *http.Request, id ID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /modules/{id}/settings)
func (_ Unimplemented) GetModuleSettings(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /modules/{id}/settings)
func (_ Unimplemented) PutModuleSettings(w http.ResponseWriter, r *http.Request, id string, params PutModuleSettingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /secrets)
func (_ Unimplemented) ListSecrets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PutSecret Create or replace a secret value (AES-256-GCM encrypted at rest)
// (POST /secrets)
func (_ Unimplemented) PutSecret(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /secrets/{id})
func (_ Unimplemented) DeleteSecret(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetModuleSettings operation middleware
func (siw *ServerInterfaceWrapper) GetModuleSettings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetModuleSettings(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutModuleSettings operation middleware
func (siw *ServerInterfaceWrapper) PutModuleSettings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutModuleSettingsParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutModuleSettings(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSecrets operation middleware
func (siw *ServerInterfaceWrapper) ListSecrets(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSecrets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSecret operation middleware
func (siw *ServerInterfaceWrapper) PutSecret(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSecret(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSecret operation middleware
func (siw *ServerInterfaceWrapper) DeleteSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSecret(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/modules/{id}/settings", wrapper.GetModuleSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/modules/{id}/settings", wrapper.PutModuleSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/secrets", wrapper.ListSecrets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/secrets", wrapper.PutSecret)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/secrets/{id}", wrapper.DeleteSecret)
	})

	return r
}
