// Package backend provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backend

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RunState.
const (
	Cancelled   RunState = "cancelled"
	Cancelling  RunState = "cancelling"
	Failed      RunState = "failed"
	Interrupted RunState = "interrupted"
	Paused      RunState = "paused"
	Planning    RunState = "planning"
	Queued      RunState = "queued"
	Running     RunState = "running"
	Succeeded   RunState = "succeeded"
	Verifying   RunState = "verifying"
	Waiting     RunState = "waiting"
)

// Valid indicates whether the value is a known member of the RunState enum.
func (e RunState) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Cancelling:
		return true
	case Failed:
		return true
	case Interrupted:
		return true
	case Paused:
		return true
	case Planning:
		return true
	case Queued:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	case Verifying:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable error code, e.g. node.occupied, plan.incompatible
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Run defines model for Run.
type Run struct {
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	DeploymentId   *openapi_types.UUID     `json:"deployment_id,omitempty"`
	ErrorCode      *string                 `json:"error_code,omitempty"`
	ErrorMessage   *string                 `json:"error_message,omitempty"`
	FinishedAt     *time.Time              `json:"finished_at,omitempty"`
	Id             openapi_types.UUID      `json:"id"`
	Input          *map[string]interface{} `json:"input,omitempty"`
	Kind           string                  `json:"kind"`
	LegacyIdentity *string                 `json:"legacy_identity,omitempty"`
	Module         string                  `json:"module"`
	Output         *map[string]interface{} `json:"output,omitempty"`
	Resources      *struct {
		Accelerators *[]string `json:"accelerators,omitempty"`
		Fabrics      *[]string `json:"fabrics,omitempty"`
		Nodes        *[]string `json:"nodes,omitempty"`
	} `json:"resources,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
	State     RunState   `json:"state"`
}

// RunState defines model for RunState.
type RunState string

// RunsPage defines model for RunsPage.
type RunsPage struct {
	Items      []Run  `json:"items"`
	NextCursor string `json:"next_cursor"`
}

// ID defines model for ID.
type ID = string

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	Module *string   `form:"module,omitempty" json:"module,omitempty"`
	State  *RunState `form:"state,omitempty" json:"state,omitempty"`
	Limit  *int      `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /runs)
	ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams)

	// (GET /runs/{id})
	GetRun(w http.ResponseWriter, r *http.Request, id ID)
	// CancelRun Cancel a nonterminal run; terminates the exact process/container
	// (POST /runs/{id}/cancel)
	CancelRun(w http.ResponseWriter, r *http.Request, id ID)
	// RunLogs Stream run logs (SSE); byte-cursor resume via Last-Event-ID
	// (GET /runs/{id}/logs)
	RunLogs(w http.ResponseWriter, r *http.Request, id ID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /runs)
func (_ Unimplemented) ListRuns(w http.ResponseWriter, r *http.Request, params ListRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /runs/{id})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelRun Cancel a nonterminal run; terminates the exact process/container
// (POST /runs/{id}/cancel)
func (_ Unimplemented) CancelRun(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RunLogs Stream run logs (SSE); byte-cursor resume via Last-Event-ID
// (GET /runs/{id}/logs)
func (_ Unimplemented) RunLogs(w http.ResponseWriter, r *http.Request, id ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListRuns operation middleware
func (siw *ServerInterfaceWrapper) ListRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsParams

	// ------------- Optional query parameter "module" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "module", r.URL.Query(), &params.Module, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "module"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "module", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelRun operation middleware
func (siw *ServerInterfaceWrapper) CancelRun(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelRun(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunLogs operation middleware
func (siw *ServerInterfaceWrapper) RunLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunLogs(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs", wrapper.ListRuns)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{id}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runs/{id}/cancel", wrapper.CancelRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{id}/logs", wrapper.RunLogs)
	})

	return r
}
