// Code generated by "go run ./internal/generate/modules gen". DO NOT EDIT.
// Source: modules/runs/module.yaml

package backend

import (
	"encoding/json"

	"github.com/jj-link/local-model-works/internal/moduleapi"
)

// descriptor is this module's frozen manifest.
var descriptor = moduleapi.Descriptor{APIVersion: "localmodelworks/v1alpha1", Kind: "Module", ID: "runs", Title: "Runs", Route: "/runs", Nav: moduleapi.Nav{Label: "Runs", Order: 50, Icon: "runs"}, SettingsSchema: json.RawMessage("{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"additionalProperties\":false,\"properties\":{},\"type\":\"object\"}"), APIFragment: "api.yaml", Capabilities: []string{"runs.read", "events.publish"}}
