// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: autoresearch.sql

package db

import (
	"context"
	"database/sql"
)

const clearAutoResearchIdeaSelections = `-- name: ClearAutoResearchIdeaSelections :exec
UPDATE autoresearch_ideas
SET selected = 0, version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE project_id = ? AND selected = 1 AND id <> ?
`

type ClearAutoResearchIdeaSelectionsParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) ClearAutoResearchIdeaSelections(ctx context.Context, arg ClearAutoResearchIdeaSelectionsParams) error {
	_, err := q.db.ExecContext(ctx, clearAutoResearchIdeaSelections, arg.ProjectID, arg.ID)
	return err
}

const countSelectedAutoResearchIdeas = `-- name: CountSelectedAutoResearchIdeas :one
SELECT COUNT(*) FROM autoresearch_ideas WHERE project_id = ? AND selected = 1
`

func (q *Queries) CountSelectedAutoResearchIdeas(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSelectedAutoResearchIdeas, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAutoResearchIdea = `-- name: CreateAutoResearchIdea :exec
INSERT INTO autoresearch_ideas (id, project_id, ordinal, source, title, body, selected)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAutoResearchIdeaParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Ordinal   int64  `json:"ordinal"`
	Source    string `json:"source"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Selected  int64  `json:"selected"`
}

func (q *Queries) CreateAutoResearchIdea(ctx context.Context, arg CreateAutoResearchIdeaParams) error {
	_, err := q.db.ExecContext(ctx, createAutoResearchIdea,
		arg.ID,
		arg.ProjectID,
		arg.Ordinal,
		arg.Source,
		arg.Title,
		arg.Body,
		arg.Selected,
	)
	return err
}

const createAutoResearchInvocation = `-- name: CreateAutoResearchInvocation :exec
INSERT INTO autoresearch_invocations
(id, run_id, parent_id, node_id, role, backend, model, advisor, session_id, state)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAutoResearchInvocationParams struct {
	ID        string         `json:"id"`
	RunID     string         `json:"run_id"`
	ParentID  sql.NullString `json:"parent_id"`
	NodeID    sql.NullString `json:"node_id"`
	Role      string         `json:"role"`
	Backend   string         `json:"backend"`
	Model     string         `json:"model"`
	Advisor   int64          `json:"advisor"`
	SessionID sql.NullString `json:"session_id"`
	State     string         `json:"state"`
}

func (q *Queries) CreateAutoResearchInvocation(ctx context.Context, arg CreateAutoResearchInvocationParams) error {
	_, err := q.db.ExecContext(ctx, createAutoResearchInvocation,
		arg.ID,
		arg.RunID,
		arg.ParentID,
		arg.NodeID,
		arg.Role,
		arg.Backend,
		arg.Model,
		arg.Advisor,
		arg.SessionID,
		arg.State,
	)
	return err
}

const createAutoResearchMessage = `-- name: CreateAutoResearchMessage :exec
INSERT INTO autoresearch_messages (id, project_id, role, body, changed_paths_json)
VALUES (?, ?, ?, ?, ?)
`

type CreateAutoResearchMessageParams struct {
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	Role             string `json:"role"`
	Body             string `json:"body"`
	ChangedPathsJson string `json:"changed_paths_json"`
}

func (q *Queries) CreateAutoResearchMessage(ctx context.Context, arg CreateAutoResearchMessageParams) error {
	_, err := q.db.ExecContext(ctx, createAutoResearchMessage,
		arg.ID,
		arg.ProjectID,
		arg.Role,
		arg.Body,
		arg.ChangedPathsJson,
	)
	return err
}

const createAutoResearchProject = `-- name: CreateAutoResearchProject :exec
INSERT INTO autoresearch_projects (id, name, status, idea_prompt, config_json)
VALUES (?, ?, ?, ?, ?)
`

type CreateAutoResearchProjectParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Status     string `json:"status"`
	IdeaPrompt string `json:"idea_prompt"`
	ConfigJson string `json:"config_json"`
}

func (q *Queries) CreateAutoResearchProject(ctx context.Context, arg CreateAutoResearchProjectParams) error {
	_, err := q.db.ExecContext(ctx, createAutoResearchProject,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.IdeaPrompt,
		arg.ConfigJson,
	)
	return err
}

const createAutoResearchRun = `-- name: CreateAutoResearchRun :exec
INSERT INTO autoresearch_runs
(run_id, project_id, factory, parent_run_id, dispatcher_session_id, worker_node_id, config_snapshot)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAutoResearchRunParams struct {
	RunID               string         `json:"run_id"`
	ProjectID           string         `json:"project_id"`
	Factory             string         `json:"factory"`
	ParentRunID         sql.NullString `json:"parent_run_id"`
	DispatcherSessionID sql.NullString `json:"dispatcher_session_id"`
	WorkerNodeID        sql.NullString `json:"worker_node_id"`
	ConfigSnapshot      string         `json:"config_snapshot"`
}

func (q *Queries) CreateAutoResearchRun(ctx context.Context, arg CreateAutoResearchRunParams) error {
	_, err := q.db.ExecContext(ctx, createAutoResearchRun,
		arg.RunID,
		arg.ProjectID,
		arg.Factory,
		arg.ParentRunID,
		arg.DispatcherSessionID,
		arg.WorkerNodeID,
		arg.ConfigSnapshot,
	)
	return err
}

const createAutoResearchSource = `-- name: CreateAutoResearchSource :exec
INSERT INTO autoresearch_sources
(id, project_id, kind, locator, title, metadata_json, local_path, sha256, status, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAutoResearchSourceParams struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	Kind         string         `json:"kind"`
	Locator      string         `json:"locator"`
	Title        sql.NullString `json:"title"`
	MetadataJson string         `json:"metadata_json"`
	LocalPath    sql.NullString `json:"local_path"`
	Sha256       sql.NullString `json:"sha256"`
	Status       string         `json:"status"`
	Error        sql.NullString `json:"error"`
}

func (q *Queries) CreateAutoResearchSource(ctx context.Context, arg CreateAutoResearchSourceParams) error {
	_, err := q.db.ExecContext(ctx, createAutoResearchSource,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Locator,
		arg.Title,
		arg.MetadataJson,
		arg.LocalPath,
		arg.Sha256,
		arg.Status,
		arg.Error,
	)
	return err
}

const deleteUnselectedGeneratedAutoResearchIdeas = `-- name: DeleteUnselectedGeneratedAutoResearchIdeas :exec
DELETE FROM autoresearch_ideas
WHERE project_id = ? AND source = 'generated' AND selected = 0
`

func (q *Queries) DeleteUnselectedGeneratedAutoResearchIdeas(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteUnselectedGeneratedAutoResearchIdeas, projectID)
	return err
}

const finishAutoResearchInvocation = `-- name: FinishAutoResearchInvocation :execrows
UPDATE autoresearch_invocations
SET state = ?, input_tokens = ?, output_tokens = ?, cost_usd = ?, error = ?,
    finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'running'
`

type FinishAutoResearchInvocationParams struct {
	State        string         `json:"state"`
	InputTokens  int64          `json:"input_tokens"`
	OutputTokens int64          `json:"output_tokens"`
	CostUsd      float64        `json:"cost_usd"`
	Error        sql.NullString `json:"error"`
	ID           string         `json:"id"`
}

func (q *Queries) FinishAutoResearchInvocation(ctx context.Context, arg FinishAutoResearchInvocationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishAutoResearchInvocation,
		arg.State,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.Error,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAutoResearchIdea = `-- name: GetAutoResearchIdea :one
SELECT id, project_id, ordinal, source, title, body, selected, version, created_at, updated_at FROM autoresearch_ideas WHERE id = ? AND project_id = ?
`

type GetAutoResearchIdeaParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetAutoResearchIdea(ctx context.Context, arg GetAutoResearchIdeaParams) (AutoresearchIdea, error) {
	row := q.db.QueryRowContext(ctx, getAutoResearchIdea, arg.ID, arg.ProjectID)
	var i AutoresearchIdea
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Ordinal,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Selected,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutoResearchInvocation = `-- name: GetAutoResearchInvocation :one
SELECT id, run_id, parent_id, node_id, role, backend, model, advisor, session_id, state, input_tokens, output_tokens, cost_usd, started_at, finished_at, error FROM autoresearch_invocations WHERE id = ?
`

func (q *Queries) GetAutoResearchInvocation(ctx context.Context, id string) (AutoresearchInvocation, error) {
	row := q.db.QueryRowContext(ctx, getAutoResearchInvocation, id)
	var i AutoresearchInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ParentID,
		&i.NodeID,
		&i.Role,
		&i.Backend,
		&i.Model,
		&i.Advisor,
		&i.SessionID,
		&i.State,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
	)
	return i, err
}

const getAutoResearchProject = `-- name: GetAutoResearchProject :one
SELECT id, name, status, idea_prompt, config_json, version, created_at, updated_at FROM autoresearch_projects WHERE id = ?
`

func (q *Queries) GetAutoResearchProject(ctx context.Context, id string) (AutoresearchProject, error) {
	row := q.db.QueryRowContext(ctx, getAutoResearchProject, id)
	var i AutoresearchProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.IdeaPrompt,
		&i.ConfigJson,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutoResearchRun = `-- name: GetAutoResearchRun :one
SELECT run_id, project_id, factory, parent_run_id, dispatcher_session_id, worker_node_id, config_snapshot FROM autoresearch_runs WHERE run_id = ?
`

func (q *Queries) GetAutoResearchRun(ctx context.Context, runID string) (AutoresearchRun, error) {
	row := q.db.QueryRowContext(ctx, getAutoResearchRun, runID)
	var i AutoresearchRun
	err := row.Scan(
		&i.RunID,
		&i.ProjectID,
		&i.Factory,
		&i.ParentRunID,
		&i.DispatcherSessionID,
		&i.WorkerNodeID,
		&i.ConfigSnapshot,
	)
	return i, err
}

const getAutoResearchSource = `-- name: GetAutoResearchSource :one
SELECT id, project_id, kind, locator, title, metadata_json, local_path, sha256, status, error, created_at FROM autoresearch_sources WHERE id = ? AND project_id = ?
`

type GetAutoResearchSourceParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetAutoResearchSource(ctx context.Context, arg GetAutoResearchSourceParams) (AutoresearchSource, error) {
	row := q.db.QueryRowContext(ctx, getAutoResearchSource, arg.ID, arg.ProjectID)
	var i AutoresearchSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Locator,
		&i.Title,
		&i.MetadataJson,
		&i.LocalPath,
		&i.Sha256,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxAutoResearchIdeaOrdinal = `-- name: GetMaxAutoResearchIdeaOrdinal :one
SELECT CAST(COALESCE(MAX(ordinal), 0) AS INTEGER) FROM autoresearch_ideas WHERE project_id = ?
`

func (q *Queries) GetMaxAutoResearchIdeaOrdinal(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxAutoResearchIdeaOrdinal, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSelectedAutoResearchIdea = `-- name: GetSelectedAutoResearchIdea :one
SELECT id, project_id, ordinal, source, title, body, selected, version, created_at, updated_at FROM autoresearch_ideas
WHERE project_id = ? AND selected = 1
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetSelectedAutoResearchIdea(ctx context.Context, projectID string) (AutoresearchIdea, error) {
	row := q.db.QueryRowContext(ctx, getSelectedAutoResearchIdea, projectID)
	var i AutoresearchIdea
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Ordinal,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.Selected,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAutoResearchIdeas = `-- name: ListAutoResearchIdeas :many
SELECT id, project_id, ordinal, source, title, body, selected, version, created_at, updated_at FROM autoresearch_ideas WHERE project_id = ? ORDER BY ordinal, id
`

func (q *Queries) ListAutoResearchIdeas(ctx context.Context, projectID string) ([]AutoresearchIdea, error) {
	rows, err := q.db.QueryContext(ctx, listAutoResearchIdeas, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoresearchIdea
	for rows.Next() {
		var i AutoresearchIdea
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Ordinal,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.Selected,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoResearchInvocations = `-- name: ListAutoResearchInvocations :many
SELECT id, run_id, parent_id, node_id, role, backend, model, advisor, session_id, state, input_tokens, output_tokens, cost_usd, started_at, finished_at, error FROM autoresearch_invocations WHERE run_id = ? ORDER BY started_at, id
`

func (q *Queries) ListAutoResearchInvocations(ctx context.Context, runID string) ([]AutoresearchInvocation, error) {
	rows, err := q.db.QueryContext(ctx, listAutoResearchInvocations, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoresearchInvocation
	for rows.Next() {
		var i AutoresearchInvocation
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ParentID,
			&i.NodeID,
			&i.Role,
			&i.Backend,
			&i.Model,
			&i.Advisor,
			&i.SessionID,
			&i.State,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoResearchMessages = `-- name: ListAutoResearchMessages :many
SELECT id, project_id, role, body, changed_paths_json, created_at FROM autoresearch_messages WHERE project_id = ? ORDER BY created_at, id
`

func (q *Queries) ListAutoResearchMessages(ctx context.Context, projectID string) ([]AutoresearchMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAutoResearchMessages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoresearchMessage
	for rows.Next() {
		var i AutoresearchMessage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Role,
			&i.Body,
			&i.ChangedPathsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoResearchProjects = `-- name: ListAutoResearchProjects :many
SELECT id, name, status, idea_prompt, config_json, version, created_at, updated_at FROM autoresearch_projects ORDER BY updated_at DESC, id
`

func (q *Queries) ListAutoResearchProjects(ctx context.Context) ([]AutoresearchProject, error) {
	rows, err := q.db.QueryContext(ctx, listAutoResearchProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoresearchProject
	for rows.Next() {
		var i AutoresearchProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.IdeaPrompt,
			&i.ConfigJson,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoResearchRuns = `-- name: ListAutoResearchRuns :many
SELECT run_id, project_id, factory, parent_run_id, dispatcher_session_id, worker_node_id, config_snapshot FROM autoresearch_runs WHERE project_id = ? ORDER BY run_id DESC
`

func (q *Queries) ListAutoResearchRuns(ctx context.Context, projectID string) ([]AutoresearchRun, error) {
	rows, err := q.db.QueryContext(ctx, listAutoResearchRuns, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoresearchRun
	for rows.Next() {
		var i AutoresearchRun
		if err := rows.Scan(
			&i.RunID,
			&i.ProjectID,
			&i.Factory,
			&i.ParentRunID,
			&i.DispatcherSessionID,
			&i.WorkerNodeID,
			&i.ConfigSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoResearchSources = `-- name: ListAutoResearchSources :many
SELECT id, project_id, kind, locator, title, metadata_json, local_path, sha256, status, error, created_at FROM autoresearch_sources WHERE project_id = ? ORDER BY created_at, id
`

func (q *Queries) ListAutoResearchSources(ctx context.Context, projectID string) ([]AutoresearchSource, error) {
	rows, err := q.db.QueryContext(ctx, listAutoResearchSources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoresearchSource
	for rows.Next() {
		var i AutoresearchSource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Locator,
			&i.Title,
			&i.MetadataJson,
			&i.LocalPath,
			&i.Sha256,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterruptedAutoResearchRunsByNode = `-- name: ListInterruptedAutoResearchRunsByNode :many
SELECT ar.run_id, ar.project_id, ar.factory, ar.parent_run_id, ar.dispatcher_session_id, ar.worker_node_id, ar.config_snapshot
FROM autoresearch_runs ar
JOIN runs r ON r.id = ar.run_id
WHERE ar.worker_node_id = ? AND r.state = 'interrupted'
ORDER BY ar.run_id
`

func (q *Queries) ListInterruptedAutoResearchRunsByNode(ctx context.Context, workerNodeID sql.NullString) ([]AutoresearchRun, error) {
	rows, err := q.db.QueryContext(ctx, listInterruptedAutoResearchRunsByNode, workerNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoresearchRun
	for rows.Next() {
		var i AutoresearchRun
		if err := rows.Scan(
			&i.RunID,
			&i.ProjectID,
			&i.Factory,
			&i.ParentRunID,
			&i.DispatcherSessionID,
			&i.WorkerNodeID,
			&i.ConfigSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAutoResearchIdea = `-- name: SelectAutoResearchIdea :execrows
UPDATE autoresearch_ideas
SET selected = 1, version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND project_id = ? AND version = ?
`

type SelectAutoResearchIdeaParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Version   int64  `json:"version"`
}

func (q *Queries) SelectAutoResearchIdea(ctx context.Context, arg SelectAutoResearchIdeaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, selectAutoResearchIdea, arg.ID, arg.ProjectID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAutoResearchProjectStatus = `-- name: SetAutoResearchProjectStatus :execrows
UPDATE autoresearch_projects
SET status = ?, version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetAutoResearchProjectStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetAutoResearchProjectStatus(ctx context.Context, arg SetAutoResearchProjectStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAutoResearchProjectStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startAutoResearchInvocation = `-- name: StartAutoResearchInvocation :execrows
UPDATE autoresearch_invocations
SET state = 'running', session_id = ?, started_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'queued'
`

type StartAutoResearchInvocationParams struct {
	SessionID sql.NullString `json:"session_id"`
	ID        string         `json:"id"`
}

func (q *Queries) StartAutoResearchInvocation(ctx context.Context, arg StartAutoResearchInvocationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startAutoResearchInvocation, arg.SessionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAutoResearchIdea = `-- name: UpdateAutoResearchIdea :execrows
UPDATE autoresearch_ideas
SET title = ?, body = ?, version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND project_id = ? AND version = ?
`

type UpdateAutoResearchIdeaParams struct {
	Title     string `json:"title"`
	Body      string `json:"body"`
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Version   int64  `json:"version"`
}

func (q *Queries) UpdateAutoResearchIdea(ctx context.Context, arg UpdateAutoResearchIdeaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAutoResearchIdea,
		arg.Title,
		arg.Body,
		arg.ID,
		arg.ProjectID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAutoResearchInvocationUsage = `-- name: UpdateAutoResearchInvocationUsage :exec
UPDATE autoresearch_invocations
SET input_tokens = ?, output_tokens = ?, cost_usd = ?
WHERE id = ?
`

type UpdateAutoResearchInvocationUsageParams struct {
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
	CostUsd      float64 `json:"cost_usd"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateAutoResearchInvocationUsage(ctx context.Context, arg UpdateAutoResearchInvocationUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateAutoResearchInvocationUsage,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.ID,
	)
	return err
}

const updateAutoResearchProject = `-- name: UpdateAutoResearchProject :execrows
UPDATE autoresearch_projects
SET name = ?, status = ?, idea_prompt = ?, config_json = ?,
    version = version + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
`

type UpdateAutoResearchProjectParams struct {
	Name       string `json:"name"`
	Status     string `json:"status"`
	IdeaPrompt string `json:"idea_prompt"`
	ConfigJson string `json:"config_json"`
	ID         string `json:"id"`
	Version    int64  `json:"version"`
}

func (q *Queries) UpdateAutoResearchProject(ctx context.Context, arg UpdateAutoResearchProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAutoResearchProject,
		arg.Name,
		arg.Status,
		arg.IdeaPrompt,
		arg.ConfigJson,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAutoResearchRunSession = `-- name: UpdateAutoResearchRunSession :exec
UPDATE autoresearch_runs SET dispatcher_session_id = ?, worker_node_id = ? WHERE run_id = ?
`

type UpdateAutoResearchRunSessionParams struct {
	DispatcherSessionID sql.NullString `json:"dispatcher_session_id"`
	WorkerNodeID        sql.NullString `json:"worker_node_id"`
	RunID               string         `json:"run_id"`
}

func (q *Queries) UpdateAutoResearchRunSession(ctx context.Context, arg UpdateAutoResearchRunSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateAutoResearchRunSession, arg.DispatcherSessionID, arg.WorkerNodeID, arg.RunID)
	return err
}

const updateAutoResearchSource = `-- name: UpdateAutoResearchSource :exec
UPDATE autoresearch_sources
SET locator = ?, title = ?, metadata_json = ?, local_path = ?, sha256 = ?, status = ?, error = ?
WHERE id = ? AND project_id = ?
`

type UpdateAutoResearchSourceParams struct {
	Locator      string         `json:"locator"`
	Title        sql.NullString `json:"title"`
	MetadataJson string         `json:"metadata_json"`
	LocalPath    sql.NullString `json:"local_path"`
	Sha256       sql.NullString `json:"sha256"`
	Status       string         `json:"status"`
	Error        sql.NullString `json:"error"`
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
}

func (q *Queries) UpdateAutoResearchSource(ctx context.Context, arg UpdateAutoResearchSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateAutoResearchSource,
		arg.Locator,
		arg.Title,
		arg.MetadataJson,
		arg.LocalPath,
		arg.Sha256,
		arg.Status,
		arg.Error,
		arg.ID,
		arg.ProjectID,
	)
	return err
}
