// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package db

import (
	"context"
	"database/sql"
)

const acquireDestinationLock = `-- name: AcquireDestinationLock :exec
INSERT INTO acquisition_destination_locks (
    node_id, destination, identity, platform, owner_kind, owner_id, run_id, item_id
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8
)
`

type AcquireDestinationLockParams struct {
	NodeID      string         `json:"node_id"`
	Destination string         `json:"destination"`
	Identity    string         `json:"identity"`
	Platform    string         `json:"platform"`
	OwnerKind   string         `json:"owner_kind"`
	OwnerID     string         `json:"owner_id"`
	RunID       sql.NullString `json:"run_id"`
	ItemID      sql.NullString `json:"item_id"`
}

func (q *Queries) AcquireDestinationLock(ctx context.Context, arg AcquireDestinationLockParams) error {
	_, err := q.db.ExecContext(ctx, acquireDestinationLock,
		arg.NodeID,
		arg.Destination,
		arg.Identity,
		arg.Platform,
		arg.OwnerKind,
		arg.OwnerID,
		arg.RunID,
		arg.ItemID,
	)
	return err
}

const bindDownloadItemCommand = `-- name: BindDownloadItemCommand :execrows
UPDATE download_items
SET command_id = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE download_items.id = ?2 AND download_items.node_id = ?3
    AND download_items.state = ?4 AND download_items.state IN ('pending', 'checking', 'transferring', 'verifying')
    AND download_items.command_id IS NULL
    AND EXISTS (
        SELECT 1 FROM acquisition_destination_locks AS lock
        WHERE lock.item_id = download_items.id AND lock.state = 'held'
    )
`

type BindDownloadItemCommandParams struct {
	CommandID     sql.NullString `json:"command_id"`
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	ExpectedState string         `json:"expected_state"`
}

func (q *Queries) BindDownloadItemCommand(ctx context.Context, arg BindDownloadItemCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindDownloadItemCommand,
		arg.CommandID,
		arg.ID,
		arg.NodeID,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const bindDownloadItemTransfer = `-- name: BindDownloadItemTransfer :execrows
UPDATE download_items
SET transfer_id = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE download_items.id = ?2 AND download_items.node_id = ?3
    AND download_items.state = ?4 AND download_items.state IN ('pending', 'checking', 'transferring', 'verifying')
    AND download_items.transfer_id IS NULL
    AND EXISTS (
        SELECT 1 FROM acquisition_destination_locks AS lock
        WHERE lock.item_id = download_items.id AND lock.state = 'held'
    )
`

type BindDownloadItemTransferParams struct {
	TransferID    sql.NullString `json:"transfer_id"`
	ID            string         `json:"id"`
	NodeID        string         `json:"node_id"`
	ExpectedState string         `json:"expected_state"`
}

func (q *Queries) BindDownloadItemTransfer(ctx context.Context, arg BindDownloadItemTransferParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bindDownloadItemTransfer,
		arg.TransferID,
		arg.ID,
		arg.NodeID,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelDestinationLock = `-- name: CancelDestinationLock :execrows
UPDATE acquisition_destination_locks
SET state = 'cancelling', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE node_id = ?1 AND destination = ?2
    AND owner_kind = ?3 AND owner_id = ?4
    AND state = 'held'
`

type CancelDestinationLockParams struct {
	NodeID      string `json:"node_id"`
	Destination string `json:"destination"`
	OwnerKind   string `json:"owner_kind"`
	OwnerID     string `json:"owner_id"`
}

func (q *Queries) CancelDestinationLock(ctx context.Context, arg CancelDestinationLockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelDestinationLock,
		arg.NodeID,
		arg.Destination,
		arg.OwnerKind,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDownloadItem = `-- name: CreateDownloadItem :exec

INSERT INTO download_items (
    id, run_id, predecessor_item_id, resource_key, node_id, resource_json
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6
)
`

type CreateDownloadItemParams struct {
	ID                string         `json:"id"`
	RunID             string         `json:"run_id"`
	PredecessorItemID sql.NullString `json:"predecessor_item_id"`
	ResourceKey       string         `json:"resource_key"`
	NodeID            string         `json:"node_id"`
	ResourceJson      string         `json:"resource_json"`
}

// Item, destination lock and command/transfer ownership must be committed before
// dispatch. Transactions use these same queries for standalone and serving work.
func (q *Queries) CreateDownloadItem(ctx context.Context, arg CreateDownloadItemParams) error {
	_, err := q.db.ExecContext(ctx, createDownloadItem,
		arg.ID,
		arg.RunID,
		arg.PredecessorItemID,
		arg.ResourceKey,
		arg.NodeID,
		arg.ResourceJson,
	)
	return err
}

const getDestinationLock = `-- name: GetDestinationLock :one
SELECT node_id, destination, identity, platform, owner_kind, owner_id,
       run_id, item_id, state, quiesced_at, quiescence_proof, created_at, updated_at
FROM acquisition_destination_locks WHERE node_id = ? AND destination = ?
`

type GetDestinationLockParams struct {
	NodeID      string `json:"node_id"`
	Destination string `json:"destination"`
}

func (q *Queries) GetDestinationLock(ctx context.Context, arg GetDestinationLockParams) (AcquisitionDestinationLock, error) {
	row := q.db.QueryRowContext(ctx, getDestinationLock, arg.NodeID, arg.Destination)
	var i AcquisitionDestinationLock
	err := row.Scan(
		&i.NodeID,
		&i.Destination,
		&i.Identity,
		&i.Platform,
		&i.OwnerKind,
		&i.OwnerID,
		&i.RunID,
		&i.ItemID,
		&i.State,
		&i.QuiescedAt,
		&i.QuiescenceProof,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadItem = `-- name: GetDownloadItem :one
SELECT id, run_id, predecessor_item_id, resource_key, node_id, resource_json,
       state, command_id, transfer_id, checkpoint_json, error_json, updated_at
FROM download_items WHERE id = ?
`

func (q *Queries) GetDownloadItem(ctx context.Context, id string) (DownloadItem, error) {
	row := q.db.QueryRowContext(ctx, getDownloadItem, id)
	var i DownloadItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.PredecessorItemID,
		&i.ResourceKey,
		&i.NodeID,
		&i.ResourceJson,
		&i.State,
		&i.CommandID,
		&i.TransferID,
		&i.CheckpointJson,
		&i.ErrorJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadItemByCommand = `-- name: GetDownloadItemByCommand :one
SELECT id, run_id, predecessor_item_id, resource_key, node_id, resource_json,
       state, command_id, transfer_id, checkpoint_json, error_json, updated_at
FROM download_items WHERE command_id = ? AND node_id = ?
`

type GetDownloadItemByCommandParams struct {
	CommandID sql.NullString `json:"command_id"`
	NodeID    string         `json:"node_id"`
}

func (q *Queries) GetDownloadItemByCommand(ctx context.Context, arg GetDownloadItemByCommandParams) (DownloadItem, error) {
	row := q.db.QueryRowContext(ctx, getDownloadItemByCommand, arg.CommandID, arg.NodeID)
	var i DownloadItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.PredecessorItemID,
		&i.ResourceKey,
		&i.NodeID,
		&i.ResourceJson,
		&i.State,
		&i.CommandID,
		&i.TransferID,
		&i.CheckpointJson,
		&i.ErrorJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadItemByTransfer = `-- name: GetDownloadItemByTransfer :one
SELECT id, run_id, predecessor_item_id, resource_key, node_id, resource_json,
       state, command_id, transfer_id, checkpoint_json, error_json, updated_at
FROM download_items WHERE transfer_id = ? AND node_id = ?
`

type GetDownloadItemByTransferParams struct {
	TransferID sql.NullString `json:"transfer_id"`
	NodeID     string         `json:"node_id"`
}

func (q *Queries) GetDownloadItemByTransfer(ctx context.Context, arg GetDownloadItemByTransferParams) (DownloadItem, error) {
	row := q.db.QueryRowContext(ctx, getDownloadItemByTransfer, arg.TransferID, arg.NodeID)
	var i DownloadItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.PredecessorItemID,
		&i.ResourceKey,
		&i.NodeID,
		&i.ResourceJson,
		&i.State,
		&i.CommandID,
		&i.TransferID,
		&i.CheckpointJson,
		&i.ErrorJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeDownloadRun = `-- name: GetRecipeDownloadRun :one
SELECT id, module, kind, state, resources, input, output, error_code, error_message,
       deployment_id, legacy_identity, created_at, started_at, finished_at
FROM runs
WHERE id = ? AND module = 'library' AND kind = 'recipe-download'
    AND json_extract(input, '$.plan.recipe_digest') = ?
`

type GetRecipeDownloadRunParams struct {
	ID    string `json:"id"`
	Input string `json:"input"`
}

type GetRecipeDownloadRunRow struct {
	ID             string         `json:"id"`
	Module         string         `json:"module"`
	Kind           string         `json:"kind"`
	State          string         `json:"state"`
	Resources      string         `json:"resources"`
	Input          string         `json:"input"`
	Output         sql.NullString `json:"output"`
	ErrorCode      sql.NullString `json:"error_code"`
	ErrorMessage   sql.NullString `json:"error_message"`
	DeploymentID   sql.NullString `json:"deployment_id"`
	LegacyIdentity sql.NullString `json:"legacy_identity"`
	CreatedAt      string         `json:"created_at"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
}

func (q *Queries) GetRecipeDownloadRun(ctx context.Context, arg GetRecipeDownloadRunParams) (GetRecipeDownloadRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeDownloadRun, arg.ID, arg.Input)
	var i GetRecipeDownloadRunRow
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Kind,
		&i.State,
		&i.Resources,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.DeploymentID,
		&i.LegacyIdentity,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const interruptDownloadItemsForRun = `-- name: InterruptDownloadItemsForRun :execrows
UPDATE download_items
SET state = 'interrupted', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE run_id = ? AND state IN ('pending', 'checking', 'transferring', 'verifying', 'cancelling')
`

// A restart interrupts the attempt without clearing command IDs or locks.
// Reconciliation must obtain agent quiescence before any successor can dispatch.
func (q *Queries) InterruptDownloadItemsForRun(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptDownloadItemsForRun, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveDownloadItemsByNode = `-- name: ListActiveDownloadItemsByNode :many
SELECT id, run_id, predecessor_item_id, resource_key, node_id, resource_json,
       state, command_id, transfer_id, checkpoint_json, error_json, updated_at
FROM download_items
WHERE node_id = ? AND state IN ('pending', 'checking', 'transferring', 'verifying', 'cancelling')
ORDER BY run_id, resource_key
`

func (q *Queries) ListActiveDownloadItemsByNode(ctx context.Context, nodeID string) ([]DownloadItem, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDownloadItemsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownloadItem
	for rows.Next() {
		var i DownloadItem
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.PredecessorItemID,
			&i.ResourceKey,
			&i.NodeID,
			&i.ResourceJson,
			&i.State,
			&i.CommandID,
			&i.TransferID,
			&i.CheckpointJson,
			&i.ErrorJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinationLocksByOwner = `-- name: ListDestinationLocksByOwner :many
SELECT node_id, destination, identity, platform, owner_kind, owner_id,
       run_id, item_id, state, quiesced_at, quiescence_proof, created_at, updated_at
FROM acquisition_destination_locks
WHERE owner_kind = ? AND owner_id = ? ORDER BY node_id, destination
`

type ListDestinationLocksByOwnerParams struct {
	OwnerKind string `json:"owner_kind"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) ListDestinationLocksByOwner(ctx context.Context, arg ListDestinationLocksByOwnerParams) ([]AcquisitionDestinationLock, error) {
	rows, err := q.db.QueryContext(ctx, listDestinationLocksByOwner, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquisitionDestinationLock
	for rows.Next() {
		var i AcquisitionDestinationLock
		if err := rows.Scan(
			&i.NodeID,
			&i.Destination,
			&i.Identity,
			&i.Platform,
			&i.OwnerKind,
			&i.OwnerID,
			&i.RunID,
			&i.ItemID,
			&i.State,
			&i.QuiescedAt,
			&i.QuiescenceProof,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinationLocksByRun = `-- name: ListDestinationLocksByRun :many
SELECT node_id, destination, identity, platform, owner_kind, owner_id,
       run_id, item_id, state, quiesced_at, quiescence_proof, created_at, updated_at
FROM acquisition_destination_locks WHERE run_id = ? ORDER BY node_id, destination
`

func (q *Queries) ListDestinationLocksByRun(ctx context.Context, runID sql.NullString) ([]AcquisitionDestinationLock, error) {
	rows, err := q.db.QueryContext(ctx, listDestinationLocksByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquisitionDestinationLock
	for rows.Next() {
		var i AcquisitionDestinationLock
		if err := rows.Scan(
			&i.NodeID,
			&i.Destination,
			&i.Identity,
			&i.Platform,
			&i.OwnerKind,
			&i.OwnerID,
			&i.RunID,
			&i.ItemID,
			&i.State,
			&i.QuiescedAt,
			&i.QuiescenceProof,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadItems = `-- name: ListDownloadItems :many
SELECT id, run_id, predecessor_item_id, resource_key, node_id, resource_json,
       state, command_id, transfer_id, checkpoint_json, error_json, updated_at
FROM download_items WHERE run_id = ? ORDER BY resource_key
`

func (q *Queries) ListDownloadItems(ctx context.Context, runID string) ([]DownloadItem, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadItems, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DownloadItem
	for rows.Next() {
		var i DownloadItem
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.PredecessorItemID,
			&i.ResourceKey,
			&i.NodeID,
			&i.ResourceJson,
			&i.State,
			&i.CommandID,
			&i.TransferID,
			&i.CheckpointJson,
			&i.ErrorJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeDownloadRuns = `-- name: ListRecipeDownloadRuns :many
SELECT id, module, kind, state, resources, input, output, error_code, error_message,
       deployment_id, legacy_identity, created_at, started_at, finished_at
FROM runs
WHERE module = 'library' AND kind = 'recipe-download'
    AND json_extract(input, '$.plan.recipe_digest') = ?
ORDER BY created_at DESC, id DESC
`

type ListRecipeDownloadRunsRow struct {
	ID             string         `json:"id"`
	Module         string         `json:"module"`
	Kind           string         `json:"kind"`
	State          string         `json:"state"`
	Resources      string         `json:"resources"`
	Input          string         `json:"input"`
	Output         sql.NullString `json:"output"`
	ErrorCode      sql.NullString `json:"error_code"`
	ErrorMessage   sql.NullString `json:"error_message"`
	DeploymentID   sql.NullString `json:"deployment_id"`
	LegacyIdentity sql.NullString `json:"legacy_identity"`
	CreatedAt      string         `json:"created_at"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
}

// Listing retains every matching attempt, not merely the latest request. The
// input includes normalized variants, workload, targets and predecessor linkage.
func (q *Queries) ListRecipeDownloadRuns(ctx context.Context, input string) ([]ListRecipeDownloadRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeDownloadRuns, input)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeDownloadRunsRow
	for rows.Next() {
		var i ListRecipeDownloadRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Kind,
			&i.State,
			&i.Resources,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.DeploymentID,
			&i.LegacyIdentity,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnquiescedDestinationLocksByNode = `-- name: ListUnquiescedDestinationLocksByNode :many
SELECT node_id, destination, identity, platform, owner_kind, owner_id,
       run_id, item_id, state, quiesced_at, quiescence_proof, created_at, updated_at
FROM acquisition_destination_locks
WHERE node_id = ? AND state <> 'quiesced' ORDER BY destination
`

func (q *Queries) ListUnquiescedDestinationLocksByNode(ctx context.Context, nodeID string) ([]AcquisitionDestinationLock, error) {
	rows, err := q.db.QueryContext(ctx, listUnquiescedDestinationLocksByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquisitionDestinationLock
	for rows.Next() {
		var i AcquisitionDestinationLock
		if err := rows.Scan(
			&i.NodeID,
			&i.Destination,
			&i.Identity,
			&i.Platform,
			&i.OwnerKind,
			&i.OwnerID,
			&i.RunID,
			&i.ItemID,
			&i.State,
			&i.QuiescedAt,
			&i.QuiescenceProof,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quiesceDestinationLock = `-- name: QuiesceDestinationLock :execrows
UPDATE acquisition_destination_locks
SET state = 'quiesced', quiesced_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    quiescence_proof = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE node_id = ?2 AND destination = ?3
    AND owner_kind = ?4 AND owner_id = ?5
    AND state = ?6 AND state IN ('held', 'cancelling')
`

type QuiesceDestinationLockParams struct {
	QuiescenceProof sql.NullString `json:"quiescence_proof"`
	NodeID          string         `json:"node_id"`
	Destination     string         `json:"destination"`
	OwnerKind       string         `json:"owner_kind"`
	OwnerID         string         `json:"owner_id"`
	ExpectedState   string         `json:"expected_state"`
}

// Call only after an enrolled node's matching terminal acknowledgement or a
// bounded node quiescence barrier. never-dispatched is allowed only when durable
// command ownership proves no dispatch could have occurred. No timeout/offline
// inference is a quiescence proof; cancelling stays pending until confirmed.
func (q *Queries) QuiesceDestinationLock(ctx context.Context, arg QuiesceDestinationLockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, quiesceDestinationLock,
		arg.QuiescenceProof,
		arg.NodeID,
		arg.Destination,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordDownloadItemCheckpoint = `-- name: RecordDownloadItemCheckpoint :execrows
UPDATE download_items
SET checkpoint_json = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2 AND node_id = ?3
    AND state = ?4
    AND state IN ('checking', 'transferring', 'verifying', 'cancelling')
    AND command_id IS ?5
    AND transfer_id IS ?6
    AND checkpoint_json = ?7
`

type RecordDownloadItemCheckpointParams struct {
	CheckpointJson         string         `json:"checkpoint_json"`
	ID                     string         `json:"id"`
	NodeID                 string         `json:"node_id"`
	ExpectedState          string         `json:"expected_state"`
	ExpectedCommandID      sql.NullString `json:"expected_command_id"`
	ExpectedTransferID     sql.NullString `json:"expected_transfer_id"`
	ExpectedCheckpointJson string         `json:"expected_checkpoint_json"`
}

// Checkpoint CAS prevents an older progress observation from overwriting a newer
// one. The coordinator validates counters/phase before attempting this update.
func (q *Queries) RecordDownloadItemCheckpoint(ctx context.Context, arg RecordDownloadItemCheckpointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordDownloadItemCheckpoint,
		arg.CheckpointJson,
		arg.ID,
		arg.NodeID,
		arg.ExpectedState,
		arg.ExpectedCommandID,
		arg.ExpectedTransferID,
		arg.ExpectedCheckpointJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseDestinationLock = `-- name: ReleaseDestinationLock :execrows
DELETE FROM acquisition_destination_locks
WHERE node_id = ?1 AND destination = ?2
    AND owner_kind = ?3 AND owner_id = ?4
    AND state = 'quiesced'
`

type ReleaseDestinationLockParams struct {
	NodeID      string `json:"node_id"`
	Destination string `json:"destination"`
	OwnerKind   string `json:"owner_kind"`
	OwnerID     string `json:"owner_id"`
}

// Delete/reacquire for a successor in one transaction after quiescence. The
// immutable old item and its checkpoint remain available for explicit Resume.
func (q *Queries) ReleaseDestinationLock(ctx context.Context, arg ReleaseDestinationLockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseDestinationLock,
		arg.NodeID,
		arg.Destination,
		arg.OwnerKind,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const transitionDownloadItem = `-- name: TransitionDownloadItem :execrows
UPDATE download_items
SET state = ?1, checkpoint_json = ?2,
    error_json = ?3,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?4 AND node_id = ?5
    AND state = ?6
    AND state IN ('pending', 'checking', 'transferring', 'verifying', 'cancelling')
    AND command_id IS ?7
    AND transfer_id IS ?8
`

type TransitionDownloadItemParams struct {
	State              string         `json:"state"`
	CheckpointJson     string         `json:"checkpoint_json"`
	ErrorJson          sql.NullString `json:"error_json"`
	ID                 string         `json:"id"`
	NodeID             string         `json:"node_id"`
	ExpectedState      string         `json:"expected_state"`
	ExpectedCommandID  sql.NullString `json:"expected_command_id"`
	ExpectedTransferID sql.NullString `json:"expected_transfer_id"`
}

// State transitions are CAS and additionally guarded by the migration trigger.
// Sender node and both attempt IDs bind results to the currently owned attempt.
// NULL IDs must match NULL, never act as wildcards. Zero affected rows means a
// stale result or concurrent transition; it is not permission to retry a fetch.
func (q *Queries) TransitionDownloadItem(ctx context.Context, arg TransitionDownloadItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionDownloadItem,
		arg.State,
		arg.CheckpointJson,
		arg.ErrorJson,
		arg.ID,
		arg.NodeID,
		arg.ExpectedState,
		arg.ExpectedCommandID,
		arg.ExpectedTransferID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
