// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const acquireLease = `-- name: AcquireLease :exec
INSERT INTO leases (resource, owner_kind, owner_id, state)
VALUES (?, ?, ?, 'active')
`

type AcquireLeaseParams struct {
	Resource  string `json:"resource"`
	OwnerKind string `json:"owner_kind"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) error {
	_, err := q.db.ExecContext(ctx, acquireLease, arg.Resource, arg.OwnerKind, arg.OwnerID)
	return err
}

const activeLeaseOwners = `-- name: ActiveLeaseOwners :many
SELECT owner_kind, owner_id FROM leases
WHERE resource = ? AND state = 'active'
`

type ActiveLeaseOwnersRow struct {
	OwnerKind string `json:"owner_kind"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) ActiveLeaseOwners(ctx context.Context, resource string) ([]ActiveLeaseOwnersRow, error) {
	rows, err := q.db.QueryContext(ctx, activeLeaseOwners, resource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveLeaseOwnersRow
	for rows.Next() {
		var i ActiveLeaseOwnersRow
		if err := rows.Scan(&i.OwnerKind, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeLeases = `-- name: ActiveLeases :many
SELECT resource FROM leases WHERE state = 'active'
`

func (q *Queries) ActiveLeases(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, activeLeases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var resource string
		if err := rows.Scan(&resource); err != nil {
			return nil, err
		}
		items = append(items, resource)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appendEvent = `-- name: AppendEvent :one
INSERT INTO events (type, node_id, payload) VALUES (?, ?, ?)
RETURNING id
`

type AppendEventParams struct {
	Type    string         `json:"type"`
	NodeID  sql.NullString `json:"node_id"`
	Payload string         `json:"payload"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendEvent, arg.Type, arg.NodeID, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const approveNode = `-- name: ApproveNode :exec
UPDATE nodes SET status = 'online' WHERE id = ? AND status = 'pending'
`

func (q *Queries) ApproveNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, approveNode, id)
	return err
}

const countActiveDeploymentsOnFabric = `-- name: CountActiveDeploymentsOnFabric :one
SELECT COUNT(*) FROM deployments
WHERE fabric = ? AND desired_state = 'running'
`

func (q *Queries) CountActiveDeploymentsOnFabric(ctx context.Context, fabric sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDeploymentsOnFabric, fabric)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :exec
INSERT OR IGNORE INTO artifacts (id, kind, identity, revision, digest, metadata)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateArtifactParams struct {
	ID       string         `json:"id"`
	Kind     string         `json:"kind"`
	Identity string         `json:"identity"`
	Revision sql.NullString `json:"revision"`
	Digest   sql.NullString `json:"digest"`
	Metadata string         `json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) error {
	_, err := q.db.ExecContext(ctx, createArtifact,
		arg.ID,
		arg.Kind,
		arg.Identity,
		arg.Revision,
		arg.Digest,
		arg.Metadata,
	)
	return err
}

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployments (id, recipe_digest, profile, placement, fabric,
                         desired_state, observed_state, run_id)
VALUES (?, ?, ?, ?, ?, 'running', 'unknown', ?)
`

type CreateDeploymentParams struct {
	ID           string         `json:"id"`
	RecipeDigest string         `json:"recipe_digest"`
	Profile      string         `json:"profile"`
	Placement    string         `json:"placement"`
	Fabric       sql.NullString `json:"fabric"`
	RunID        sql.NullString `json:"run_id"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment,
		arg.ID,
		arg.RecipeDigest,
		arg.Profile,
		arg.Placement,
		arg.Fabric,
		arg.RunID,
	)
	return err
}

const createEnrollmentToken = `-- name: CreateEnrollmentToken :exec
INSERT INTO enrollment_tokens (id, token_hash, description, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateEnrollmentTokenParams struct {
	ID          string         `json:"id"`
	TokenHash   []byte         `json:"token_hash"`
	Description sql.NullString `json:"description"`
	ExpiresAt   string         `json:"expires_at"`
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) error {
	_, err := q.db.ExecContext(ctx, createEnrollmentToken,
		arg.ID,
		arg.TokenHash,
		arg.Description,
		arg.ExpiresAt,
	)
	return err
}

const createFabric = `-- name: CreateFabric :exec
INSERT INTO fabrics (id, name, transport, interface_name, address, rdma_device,
                     members, state, diagnostics, version)
VALUES (?, ?, ?, ?, ?, ?, ?, 'incomplete', '[]', ?)
`

type CreateFabricParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Transport     string         `json:"transport"`
	InterfaceName sql.NullString `json:"interface_name"`
	Address       sql.NullString `json:"address"`
	RdmaDevice    sql.NullString `json:"rdma_device"`
	Members       string         `json:"members"`
	Version       string         `json:"version"`
}

func (q *Queries) CreateFabric(ctx context.Context, arg CreateFabricParams) error {
	_, err := q.db.ExecContext(ctx, createFabric,
		arg.ID,
		arg.Name,
		arg.Transport,
		arg.InterfaceName,
		arg.Address,
		arg.RdmaDevice,
		arg.Members,
		arg.Version,
	)
	return err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (id, display_name, labels, status, created_at)
VALUES (?, ?, ?, 'pending', ?)
`

type CreateNodeParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	Labels      string `json:"labels"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.ID,
		arg.DisplayName,
		arg.Labels,
		arg.CreatedAt,
	)
	return err
}

const createRecipe = `-- name: CreateRecipe :exec
INSERT OR IGNORE INTO recipes (digest, name, version, display_name, description,
                               license, source, trust_state, manifest)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRecipeParams struct {
	Digest      string         `json:"digest"`
	Name        string         `json:"name"`
	Version     string         `json:"version"`
	DisplayName sql.NullString `json:"display_name"`
	Description sql.NullString `json:"description"`
	License     sql.NullString `json:"license"`
	Source      string         `json:"source"`
	TrustState  string         `json:"trust_state"`
	Manifest    string         `json:"manifest"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) error {
	_, err := q.db.ExecContext(ctx, createRecipe,
		arg.Digest,
		arg.Name,
		arg.Version,
		arg.DisplayName,
		arg.Description,
		arg.License,
		arg.Source,
		arg.TrustState,
		arg.Manifest,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, module, kind, state, resources, input, deployment_id,
                  legacy_identity)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRunParams struct {
	ID             string         `json:"id"`
	Module         string         `json:"module"`
	Kind           string         `json:"kind"`
	State          string         `json:"state"`
	Resources      string         `json:"resources"`
	Input          string         `json:"input"`
	DeploymentID   sql.NullString `json:"deployment_id"`
	LegacyIdentity sql.NullString `json:"legacy_identity"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.Module,
		arg.Kind,
		arg.State,
		arg.Resources,
		arg.Input,
		arg.DeploymentID,
		arg.LegacyIdentity,
	)
	return err
}

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (id, name, purpose, nonce, ciphertext)
VALUES (?, ?, ?, ?, ?)
`

type CreateSecretParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Purpose    string `json:"purpose"`
	Nonce      []byte `json:"nonce"`
	Ciphertext []byte `json:"ciphertext"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.ExecContext(ctx, createSecret,
		arg.ID,
		arg.Name,
		arg.Purpose,
		arg.Nonce,
		arg.Ciphertext,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, username, csrf_hash, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string `json:"token_hash"`
	Username  string `json:"username"`
	CsrfHash  string `json:"csrf_hash"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.Username,
		arg.CsrfHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createTransfer = `-- name: CreateTransfer :exec
INSERT INTO transfers (id, artifact_id, source_node, dest_node, dest_path,
                       credential_hash, state)
VALUES (?, ?, ?, ?, ?, ?, 'pending')
`

type CreateTransferParams struct {
	ID             string `json:"id"`
	ArtifactID     string `json:"artifact_id"`
	SourceNode     string `json:"source_node"`
	DestNode       string `json:"dest_node"`
	DestPath       string `json:"dest_path"`
	CredentialHash []byte `json:"credential_hash"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) error {
	_, err := q.db.ExecContext(ctx, createTransfer,
		arg.ID,
		arg.ArtifactID,
		arg.SourceNode,
		arg.DestNode,
		arg.DestPath,
		arg.CredentialHash,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, argon2_hash) VALUES (?, ?)
`

type CreateUserParams struct {
	Username   string `json:"username"`
	Argon2Hash string `json:"argon2_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Argon2Hash)
	return err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments WHERE id = ?
`

func (q *Queries) DeleteDeployment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, id)
	return err
}

const deleteDeploymentRuns = `-- name: DeleteDeploymentRuns :exec
DELETE FROM runs WHERE deployment_id = ?
`

func (q *Queries) DeleteDeploymentRuns(ctx context.Context, deploymentID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentRuns, deploymentID)
	return err
}

const deleteEnrollmentToken = `-- name: DeleteEnrollmentToken :exec
DELETE FROM enrollment_tokens WHERE id = ?
`

func (q *Queries) DeleteEnrollmentToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEnrollmentToken, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteExpiredUnusedTokens = `-- name: DeleteExpiredUnusedTokens :exec
DELETE FROM enrollment_tokens WHERE used_at IS NULL AND expires_at < ?
`

func (q *Queries) DeleteExpiredUnusedTokens(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredUnusedTokens, expiresAt)
	return err
}

const deleteFabric = `-- name: DeleteFabric :exec
DELETE FROM fabrics WHERE id = ? AND version = ?
`

type DeleteFabricParams struct {
	ID      string `json:"id"`
	Version string `json:"version"`
}

func (q *Queries) DeleteFabric(ctx context.Context, arg DeleteFabricParams) error {
	_, err := q.db.ExecContext(ctx, deleteFabric, arg.ID, arg.Version)
	return err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes WHERE digest = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, digest string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, digest)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE id = ?
`

func (q *Queries) DeleteSecret(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, id)
	return err
}

const deleteServingTelemetry1mOlder = `-- name: DeleteServingTelemetry1mOlder :exec
DELETE FROM serving_telemetry_1m WHERE ts < ?
`

func (q *Queries) DeleteServingTelemetry1mOlder(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, deleteServingTelemetry1mOlder, ts)
	return err
}

const deleteServingTelemetry5sOlder = `-- name: DeleteServingTelemetry5sOlder :exec
DELETE FROM serving_telemetry_5s WHERE ts < ?
`

func (q *Queries) DeleteServingTelemetry5sOlder(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, deleteServingTelemetry5sOlder, ts)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteTelemetry1mOlder = `-- name: DeleteTelemetry1mOlder :exec
DELETE FROM telemetry_1m WHERE ts < ?
`

func (q *Queries) DeleteTelemetry1mOlder(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetry1mOlder, ts)
	return err
}

const deleteTelemetry5sOlder = `-- name: DeleteTelemetry5sOlder :exec
DELETE FROM telemetry_5s WHERE ts < ?
`

func (q *Queries) DeleteTelemetry5sOlder(ctx context.Context, ts int64) error {
	_, err := q.db.ExecContext(ctx, deleteTelemetry5sOlder, ts)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, kind, identity, revision, digest, validation_state, metadata, created_at
FROM artifacts WHERE id = ?
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Identity,
		&i.Revision,
		&i.Digest,
		&i.ValidationState,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByIdentity = `-- name: GetArtifactByIdentity :one
SELECT id, kind, identity, revision, digest, validation_state, metadata, created_at
FROM artifacts WHERE identity = ?
`

func (q *Queries) GetArtifactByIdentity(ctx context.Context, identity string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByIdentity, identity)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Identity,
		&i.Revision,
		&i.Digest,
		&i.ValidationState,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, recipe_digest, profile, placement, fabric, desired_state,
       observed_state, endpoint, endpoint_model, endpoint_path,
       model_capabilities, diagnostics, run_id,
       dispatch, created_at, updated_at
FROM deployments WHERE id = ?
`

type GetDeploymentRow struct {
	ID                string         `json:"id"`
	RecipeDigest      string         `json:"recipe_digest"`
	Profile           string         `json:"profile"`
	Placement         string         `json:"placement"`
	Fabric            sql.NullString `json:"fabric"`
	DesiredState      string         `json:"desired_state"`
	ObservedState     string         `json:"observed_state"`
	Endpoint          sql.NullString `json:"endpoint"`
	EndpointModel     sql.NullString `json:"endpoint_model"`
	EndpointPath      sql.NullString `json:"endpoint_path"`
	ModelCapabilities sql.NullString `json:"model_capabilities"`
	Diagnostics       string         `json:"diagnostics"`
	RunID             sql.NullString `json:"run_id"`
	Dispatch          string         `json:"dispatch"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) GetDeployment(ctx context.Context, id string) (GetDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i GetDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.RecipeDigest,
		&i.Profile,
		&i.Placement,
		&i.Fabric,
		&i.DesiredState,
		&i.ObservedState,
		&i.Endpoint,
		&i.EndpointModel,
		&i.EndpointPath,
		&i.ModelCapabilities,
		&i.Diagnostics,
		&i.RunID,
		&i.Dispatch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentTokenByHash = `-- name: GetEnrollmentTokenByHash :one
SELECT id, description, created_at, expires_at, used_at, used_by_node
FROM enrollment_tokens WHERE token_hash = ?
`

type GetEnrollmentTokenByHashRow struct {
	ID          string         `json:"id"`
	Description sql.NullString `json:"description"`
	CreatedAt   string         `json:"created_at"`
	ExpiresAt   string         `json:"expires_at"`
	UsedAt      sql.NullString `json:"used_at"`
	UsedByNode  sql.NullString `json:"used_by_node"`
}

func (q *Queries) GetEnrollmentTokenByHash(ctx context.Context, tokenHash []byte) (GetEnrollmentTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentTokenByHash, tokenHash)
	var i GetEnrollmentTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByNode,
	)
	return i, err
}

const getEnrollmentTokenByID = `-- name: GetEnrollmentTokenByID :one
SELECT id, description, created_at, expires_at, used_at, used_by_node
FROM enrollment_tokens WHERE id = ?
`

type GetEnrollmentTokenByIDRow struct {
	ID          string         `json:"id"`
	Description sql.NullString `json:"description"`
	CreatedAt   string         `json:"created_at"`
	ExpiresAt   string         `json:"expires_at"`
	UsedAt      sql.NullString `json:"used_at"`
	UsedByNode  sql.NullString `json:"used_by_node"`
}

func (q *Queries) GetEnrollmentTokenByID(ctx context.Context, id string) (GetEnrollmentTokenByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentTokenByID, id)
	var i GetEnrollmentTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByNode,
	)
	return i, err
}

const getFabric = `-- name: GetFabric :one
SELECT id, name, transport, interface_name, address, rdma_device, members,
       state, diagnostics, version, created_at, updated_at
FROM fabrics WHERE id = ?
`

func (q *Queries) GetFabric(ctx context.Context, id string) (Fabric, error) {
	row := q.db.QueryRowContext(ctx, getFabric, id)
	var i Fabric
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.InterfaceName,
		&i.Address,
		&i.RdmaDevice,
		&i.Members,
		&i.State,
		&i.Diagnostics,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFabricByIfMatch = `-- name: GetFabricByIfMatch :one
SELECT id, name, transport, interface_name, address, rdma_device, members,
       state, diagnostics, version, created_at, updated_at
FROM fabrics WHERE id = ? AND version = ?
`

type GetFabricByIfMatchParams struct {
	ID      string `json:"id"`
	Version string `json:"version"`
}

func (q *Queries) GetFabricByIfMatch(ctx context.Context, arg GetFabricByIfMatchParams) (Fabric, error) {
	row := q.db.QueryRowContext(ctx, getFabricByIfMatch, arg.ID, arg.Version)
	var i Fabric
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.InterfaceName,
		&i.Address,
		&i.RdmaDevice,
		&i.Members,
		&i.State,
		&i.Diagnostics,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationPlan = `-- name: GetMigrationPlan :one
SELECT plan_digest, request, plan, created_at
FROM migration_plans WHERE plan_digest = ?
`

func (q *Queries) GetMigrationPlan(ctx context.Context, planDigest string) (MigrationPlan, error) {
	row := q.db.QueryRowContext(ctx, getMigrationPlan, planDigest)
	var i MigrationPlan
	err := row.Scan(
		&i.PlanDigest,
		&i.Request,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getModuleSettings = `-- name: GetModuleSettings :one
SELECT module, settings, version, updated_at FROM module_settings WHERE module = ?
`

func (q *Queries) GetModuleSettings(ctx context.Context, module string) (ModuleSetting, error) {
	row := q.db.QueryRowContext(ctx, getModuleSettings, module)
	var i ModuleSetting
	err := row.Scan(
		&i.Module,
		&i.Settings,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, display_name, labels, agent_version, status, last_heartbeat, inventory,
       certificate_expires_at, created_at
FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Labels,
		&i.AgentVersion,
		&i.Status,
		&i.LastHeartbeat,
		&i.Inventory,
		&i.CertificateExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeCredential = `-- name: GetNodeCredential :one
SELECT node_id, public_key_pem, serial, issued_at, expires_at
FROM node_credentials WHERE node_id = ?
`

func (q *Queries) GetNodeCredential(ctx context.Context, nodeID string) (NodeCredential, error) {
	row := q.db.QueryRowContext(ctx, getNodeCredential, nodeID)
	var i NodeCredential
	err := row.Scan(
		&i.NodeID,
		&i.PublicKeyPem,
		&i.Serial,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPlacement = `-- name: GetPlacement :one
SELECT id, artifact_id, node_id, path, state, verified_at, diagnostics, size_bytes
FROM artifact_placements WHERE artifact_id = ? AND node_id = ? AND path = ?
`

type GetPlacementParams struct {
	ArtifactID string `json:"artifact_id"`
	NodeID     string `json:"node_id"`
	Path       string `json:"path"`
}

func (q *Queries) GetPlacement(ctx context.Context, arg GetPlacementParams) (ArtifactPlacement, error) {
	row := q.db.QueryRowContext(ctx, getPlacement, arg.ArtifactID, arg.NodeID, arg.Path)
	var i ArtifactPlacement
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.NodeID,
		&i.Path,
		&i.State,
		&i.VerifiedAt,
		&i.Diagnostics,
		&i.SizeBytes,
	)
	return i, err
}

const getRecipe = `-- name: GetRecipe :one
SELECT digest, name, version, display_name, description, license, source,
       trust_state, manifest, installed_at
FROM recipes WHERE digest = ?
`

func (q *Queries) GetRecipe(ctx context.Context, digest string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, digest)
	var i Recipe
	err := row.Scan(
		&i.Digest,
		&i.Name,
		&i.Version,
		&i.DisplayName,
		&i.Description,
		&i.License,
		&i.Source,
		&i.TrustState,
		&i.Manifest,
		&i.InstalledAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, module, kind, state, resources, input, output, error_code,
       error_message, deployment_id, legacy_identity, created_at, started_at,
       finished_at
FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Kind,
		&i.State,
		&i.Resources,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.DeploymentID,
		&i.LegacyIdentity,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT id, name, purpose, nonce, ciphertext, created_at, updated_at
FROM secrets WHERE id = ?
`

func (q *Queries) GetSecret(ctx context.Context, id string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Purpose,
		&i.Nonce,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretByName = `-- name: GetSecretByName :one
SELECT id, name, purpose, nonce, ciphertext, created_at, updated_at
FROM secrets WHERE name = ?
`

func (q *Queries) GetSecretByName(ctx context.Context, name string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecretByName, name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Purpose,
		&i.Nonce,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT token_hash, username, csrf_hash, created_at, expires_at
FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.Username,
		&i.CsrfHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, artifact_id, source_node, dest_node, dest_path, credential_hash,
       state, bytes_total, bytes_done, diagnostic, created_at, updated_at
FROM transfers WHERE id = ?
`

func (q *Queries) GetTransfer(ctx context.Context, id string) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.SourceNode,
		&i.DestNode,
		&i.DestPath,
		&i.CredentialHash,
		&i.State,
		&i.BytesTotal,
		&i.BytesDone,
		&i.Diagnostic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, argon2_hash, created_at FROM users WHERE username = ?
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(&i.Username, &i.Argon2Hash, &i.CreatedAt)
	return i, err
}

const insertBenchmarkResult = `-- name: InsertBenchmarkResult :exec
INSERT INTO benchmark_results (run_id, language, endpoint, model, requests,
                               successes, prompt_tokens, completion_tokens,
                               total_tokens, wall_seconds, tokens_per_second,
                               latency, first_token, grading, quantization,
                               reasoning, result_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBenchmarkResultParams struct {
	RunID            string         `json:"run_id"`
	Language         string         `json:"language"`
	Endpoint         sql.NullString `json:"endpoint"`
	Model            sql.NullString `json:"model"`
	Requests         int64          `json:"requests"`
	Successes        int64          `json:"successes"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	TotalTokens      int64          `json:"total_tokens"`
	WallSeconds      float64        `json:"wall_seconds"`
	TokensPerSecond  float64        `json:"tokens_per_second"`
	Latency          string         `json:"latency"`
	FirstToken       string         `json:"first_token"`
	Grading          sql.NullString `json:"grading"`
	Quantization     sql.NullString `json:"quantization"`
	Reasoning        sql.NullString `json:"reasoning"`
	ResultPath       sql.NullString `json:"result_path"`
}

func (q *Queries) InsertBenchmarkResult(ctx context.Context, arg InsertBenchmarkResultParams) error {
	_, err := q.db.ExecContext(ctx, insertBenchmarkResult,
		arg.RunID,
		arg.Language,
		arg.Endpoint,
		arg.Model,
		arg.Requests,
		arg.Successes,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.WallSeconds,
		arg.TokensPerSecond,
		arg.Latency,
		arg.FirstToken,
		arg.Grading,
		arg.Quantization,
		arg.Reasoning,
		arg.ResultPath,
	)
	return err
}

const insertServingTelemetry1m = `-- name: InsertServingTelemetry1m :exec
INSERT OR REPLACE INTO serving_telemetry_1m (deployment_id, ts, payload) VALUES (?, ?, ?)
`

type InsertServingTelemetry1mParams struct {
	DeploymentID string `json:"deployment_id"`
	Ts           int64  `json:"ts"`
	Payload      string `json:"payload"`
}

func (q *Queries) InsertServingTelemetry1m(ctx context.Context, arg InsertServingTelemetry1mParams) error {
	_, err := q.db.ExecContext(ctx, insertServingTelemetry1m, arg.DeploymentID, arg.Ts, arg.Payload)
	return err
}

const insertServingTelemetry5s = `-- name: InsertServingTelemetry5s :exec
INSERT OR REPLACE INTO serving_telemetry_5s (deployment_id, ts, payload) VALUES (?, ?, ?)
`

type InsertServingTelemetry5sParams struct {
	DeploymentID string `json:"deployment_id"`
	Ts           int64  `json:"ts"`
	Payload      string `json:"payload"`
}

func (q *Queries) InsertServingTelemetry5s(ctx context.Context, arg InsertServingTelemetry5sParams) error {
	_, err := q.db.ExecContext(ctx, insertServingTelemetry5s, arg.DeploymentID, arg.Ts, arg.Payload)
	return err
}

const insertTelemetry1m = `-- name: InsertTelemetry1m :exec
INSERT OR REPLACE INTO telemetry_1m (node_id, ts, payload) VALUES (?, ?, ?)
`

type InsertTelemetry1mParams struct {
	NodeID  string `json:"node_id"`
	Ts      int64  `json:"ts"`
	Payload string `json:"payload"`
}

func (q *Queries) InsertTelemetry1m(ctx context.Context, arg InsertTelemetry1mParams) error {
	_, err := q.db.ExecContext(ctx, insertTelemetry1m, arg.NodeID, arg.Ts, arg.Payload)
	return err
}

const insertTelemetry5s = `-- name: InsertTelemetry5s :exec
INSERT OR REPLACE INTO telemetry_5s (node_id, ts, payload) VALUES (?, ?, ?)
`

type InsertTelemetry5sParams struct {
	NodeID  string `json:"node_id"`
	Ts      int64  `json:"ts"`
	Payload string `json:"payload"`
}

func (q *Queries) InsertTelemetry5s(ctx context.Context, arg InsertTelemetry5sParams) error {
	_, err := q.db.ExecContext(ctx, insertTelemetry5s, arg.NodeID, arg.Ts, arg.Payload)
	return err
}

const latestServingTelemetryAll = `-- name: LatestServingTelemetryAll :many
SELECT s.deployment_id, s.ts, s.payload FROM serving_telemetry_5s s
JOIN (SELECT deployment_id, MAX(ts) ts FROM serving_telemetry_5s GROUP BY deployment_id) latest
  ON latest.deployment_id = s.deployment_id AND latest.ts = s.ts
ORDER BY s.deployment_id
`

func (q *Queries) LatestServingTelemetryAll(ctx context.Context) ([]ServingTelemetry5, error) {
	rows, err := q.db.QueryContext(ctx, latestServingTelemetryAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServingTelemetry5
	for rows.Next() {
		var i ServingTelemetry5
		if err := rows.Scan(&i.DeploymentID, &i.Ts, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestTelemetry5s = `-- name: LatestTelemetry5s :one
SELECT ts, payload FROM telemetry_5s WHERE node_id = ?
ORDER BY ts DESC LIMIT 1
`

type LatestTelemetry5sRow struct {
	Ts      int64  `json:"ts"`
	Payload string `json:"payload"`
}

func (q *Queries) LatestTelemetry5s(ctx context.Context, nodeID string) (LatestTelemetry5sRow, error) {
	row := q.db.QueryRowContext(ctx, latestTelemetry5s, nodeID)
	var i LatestTelemetry5sRow
	err := row.Scan(&i.Ts, &i.Payload)
	return i, err
}

const latestTelemetryAll = `-- name: LatestTelemetryAll :many
SELECT t.node_id, t.ts, t.payload FROM telemetry_5s t
JOIN (SELECT node_id, MAX(ts) ts FROM telemetry_5s GROUP BY node_id) latest
  ON latest.node_id = t.node_id AND latest.ts = t.ts
ORDER BY t.node_id
`

func (q *Queries) LatestTelemetryAll(ctx context.Context) ([]Telemetry5, error) {
	rows, err := q.db.QueryContext(ctx, latestTelemetryAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Telemetry5
	for rows.Next() {
		var i Telemetry5
		if err := rows.Scan(&i.NodeID, &i.Ts, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leasesForOwner = `-- name: LeasesForOwner :many
SELECT resource, state FROM leases
WHERE owner_kind = ? AND owner_id = ?
ORDER BY resource
`

type LeasesForOwnerParams struct {
	OwnerKind string `json:"owner_kind"`
	OwnerID   string `json:"owner_id"`
}

type LeasesForOwnerRow struct {
	Resource string `json:"resource"`
	State    string `json:"state"`
}

func (q *Queries) LeasesForOwner(ctx context.Context, arg LeasesForOwnerParams) ([]LeasesForOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, leasesForOwner, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeasesForOwnerRow
	for rows.Next() {
		var i LeasesForOwnerRow
		if err := rows.Scan(&i.Resource, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDeployments = `-- name: ListActiveDeployments :many
SELECT id, recipe_digest, profile, placement, fabric, desired_state,
       observed_state, endpoint, endpoint_model, endpoint_path,
       model_capabilities, diagnostics, run_id,
       dispatch, created_at, updated_at
FROM deployments WHERE desired_state = 'running'
`

type ListActiveDeploymentsRow struct {
	ID                string         `json:"id"`
	RecipeDigest      string         `json:"recipe_digest"`
	Profile           string         `json:"profile"`
	Placement         string         `json:"placement"`
	Fabric            sql.NullString `json:"fabric"`
	DesiredState      string         `json:"desired_state"`
	ObservedState     string         `json:"observed_state"`
	Endpoint          sql.NullString `json:"endpoint"`
	EndpointModel     sql.NullString `json:"endpoint_model"`
	EndpointPath      sql.NullString `json:"endpoint_path"`
	ModelCapabilities sql.NullString `json:"model_capabilities"`
	Diagnostics       string         `json:"diagnostics"`
	RunID             sql.NullString `json:"run_id"`
	Dispatch          string         `json:"dispatch"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) ListActiveDeployments(ctx context.Context) ([]ListActiveDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveDeploymentsRow
	for rows.Next() {
		var i ListActiveDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeDigest,
			&i.Profile,
			&i.Placement,
			&i.Fabric,
			&i.DesiredState,
			&i.ObservedState,
			&i.Endpoint,
			&i.EndpointModel,
			&i.EndpointPath,
			&i.ModelCapabilities,
			&i.Diagnostics,
			&i.RunID,
			&i.Dispatch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, kind, identity, revision, digest, validation_state, metadata, created_at
FROM artifacts WHERE (? IS NULL OR kind = ?)
ORDER BY created_at DESC
`

type ListArtifactsParams struct {
	Column1 interface{} `json:"column_1"`
	Kind    string      `json:"kind"`
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts, arg.Column1, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Identity,
			&i.Revision,
			&i.Digest,
			&i.ValidationState,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsOnNode = `-- name: ListArtifactsOnNode :many
SELECT a.id, a.kind, a.identity, a.revision, a.digest, a.validation_state, a.metadata, a.created_at
FROM artifacts a
JOIN artifact_placements p ON p.artifact_id = a.id
WHERE p.node_id = ?
ORDER BY a.created_at DESC
`

func (q *Queries) ListArtifactsOnNode(ctx context.Context, nodeID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsOnNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Identity,
			&i.Revision,
			&i.Digest,
			&i.ValidationState,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenchmarkResults = `-- name: ListBenchmarkResults :many
SELECT id, run_id, language, endpoint, model, requests, successes, prompt_tokens,
       completion_tokens, total_tokens, wall_seconds, tokens_per_second, latency,
       first_token, grading, quantization, reasoning, result_path, created_at
FROM benchmark_results ORDER BY created_at DESC
`

func (q *Queries) ListBenchmarkResults(ctx context.Context) ([]BenchmarkResult, error) {
	rows, err := q.db.QueryContext(ctx, listBenchmarkResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BenchmarkResult
	for rows.Next() {
		var i BenchmarkResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Language,
			&i.Endpoint,
			&i.Model,
			&i.Requests,
			&i.Successes,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.WallSeconds,
			&i.TokensPerSecond,
			&i.Latency,
			&i.FirstToken,
			&i.Grading,
			&i.Quantization,
			&i.Reasoning,
			&i.ResultPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenchmarkResultsByRun = `-- name: ListBenchmarkResultsByRun :many
SELECT id, run_id, language, endpoint, model, requests, successes, prompt_tokens,
       completion_tokens, total_tokens, wall_seconds, tokens_per_second, latency,
       first_token, grading, quantization, reasoning, result_path, created_at
FROM benchmark_results WHERE run_id = ? ORDER BY language
`

func (q *Queries) ListBenchmarkResultsByRun(ctx context.Context, runID string) ([]BenchmarkResult, error) {
	rows, err := q.db.QueryContext(ctx, listBenchmarkResultsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BenchmarkResult
	for rows.Next() {
		var i BenchmarkResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Language,
			&i.Endpoint,
			&i.Model,
			&i.Requests,
			&i.Successes,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.WallSeconds,
			&i.TokensPerSecond,
			&i.Latency,
			&i.FirstToken,
			&i.Grading,
			&i.Quantization,
			&i.Reasoning,
			&i.ResultPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, recipe_digest, profile, placement, fabric, desired_state,
       observed_state, endpoint, endpoint_model, endpoint_path,
       model_capabilities, diagnostics, run_id,
       dispatch, created_at, updated_at
FROM deployments ORDER BY created_at DESC
`

type ListDeploymentsRow struct {
	ID                string         `json:"id"`
	RecipeDigest      string         `json:"recipe_digest"`
	Profile           string         `json:"profile"`
	Placement         string         `json:"placement"`
	Fabric            sql.NullString `json:"fabric"`
	DesiredState      string         `json:"desired_state"`
	ObservedState     string         `json:"observed_state"`
	Endpoint          sql.NullString `json:"endpoint"`
	EndpointModel     sql.NullString `json:"endpoint_model"`
	EndpointPath      sql.NullString `json:"endpoint_path"`
	ModelCapabilities sql.NullString `json:"model_capabilities"`
	Diagnostics       string         `json:"diagnostics"`
	RunID             sql.NullString `json:"run_id"`
	Dispatch          string         `json:"dispatch"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) ListDeployments(ctx context.Context) ([]ListDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentsRow
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeDigest,
			&i.Profile,
			&i.Placement,
			&i.Fabric,
			&i.DesiredState,
			&i.ObservedState,
			&i.Endpoint,
			&i.EndpointModel,
			&i.EndpointPath,
			&i.ModelCapabilities,
			&i.Diagnostics,
			&i.RunID,
			&i.Dispatch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentTokens = `-- name: ListEnrollmentTokens :many
SELECT id, description, created_at, expires_at, used_at, used_by_node
FROM enrollment_tokens ORDER BY created_at DESC
`

type ListEnrollmentTokensRow struct {
	ID          string         `json:"id"`
	Description sql.NullString `json:"description"`
	CreatedAt   string         `json:"created_at"`
	ExpiresAt   string         `json:"expires_at"`
	UsedAt      sql.NullString `json:"used_at"`
	UsedByNode  sql.NullString `json:"used_by_node"`
}

func (q *Queries) ListEnrollmentTokens(ctx context.Context) ([]ListEnrollmentTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentTokensRow
	for rows.Next() {
		var i ListEnrollmentTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedByNode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsSince = `-- name: ListEventsSince :many
SELECT id, ts, type, node_id, payload FROM events
WHERE id > ? ORDER BY id ASC LIMIT ?
`

type ListEventsSinceParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

func (q *Queries) ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsSince, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Type,
			&i.NodeID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFabrics = `-- name: ListFabrics :many
SELECT id, name, transport, interface_name, address, rdma_device, members,
       state, diagnostics, version, created_at, updated_at
FROM fabrics ORDER BY name
`

func (q *Queries) ListFabrics(ctx context.Context) ([]Fabric, error) {
	rows, err := q.db.QueryContext(ctx, listFabrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fabric
	for rows.Next() {
		var i Fabric
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Transport,
			&i.InterfaceName,
			&i.Address,
			&i.RdmaDevice,
			&i.Members,
			&i.State,
			&i.Diagnostics,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, display_name, labels, agent_version, status, last_heartbeat, inventory,
       certificate_expires_at, created_at
FROM nodes ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Labels,
			&i.AgentVersion,
			&i.Status,
			&i.LastHeartbeat,
			&i.Inventory,
			&i.CertificateExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonTerminalRuns = `-- name: ListNonTerminalRuns :many
SELECT id, module, kind, state, resources, input, output, error_code,
       error_message, deployment_id, legacy_identity, created_at, started_at,
       finished_at
FROM runs
WHERE state NOT IN ('succeeded', 'failed', 'cancelled', 'interrupted')
`

func (q *Queries) ListNonTerminalRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listNonTerminalRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Kind,
			&i.State,
			&i.Resources,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.DeploymentID,
			&i.LegacyIdentity,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNodes = `-- name: ListPendingNodes :many
SELECT id, display_name, labels, agent_version, status, last_heartbeat, inventory,
       certificate_expires_at, created_at
FROM nodes WHERE status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listPendingNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Labels,
			&i.AgentVersion,
			&i.Status,
			&i.LastHeartbeat,
			&i.Inventory,
			&i.CertificateExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacements = `-- name: ListPlacements :many
SELECT id, artifact_id, node_id, path, state, verified_at, diagnostics, size_bytes
FROM artifact_placements WHERE artifact_id = ?
`

func (q *Queries) ListPlacements(ctx context.Context, artifactID string) ([]ArtifactPlacement, error) {
	rows, err := q.db.QueryContext(ctx, listPlacements, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactPlacement
	for rows.Next() {
		var i ArtifactPlacement
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.NodeID,
			&i.Path,
			&i.State,
			&i.VerifiedAt,
			&i.Diagnostics,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacementsOnNode = `-- name: ListPlacementsOnNode :many
SELECT id, artifact_id, node_id, path, state, verified_at, diagnostics, size_bytes
FROM artifact_placements WHERE node_id = ?
`

func (q *Queries) ListPlacementsOnNode(ctx context.Context, nodeID string) ([]ArtifactPlacement, error) {
	rows, err := q.db.QueryContext(ctx, listPlacementsOnNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactPlacement
	for rows.Next() {
		var i ArtifactPlacement
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.NodeID,
			&i.Path,
			&i.State,
			&i.VerifiedAt,
			&i.Diagnostics,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeVersions = `-- name: ListRecipeVersions :many
SELECT digest, name, version, display_name, description, license, source,
       trust_state, manifest, installed_at
FROM recipes WHERE name = ? ORDER BY installed_at DESC
`

func (q *Queries) ListRecipeVersions(ctx context.Context, name string) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeVersions, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.Digest,
			&i.Name,
			&i.Version,
			&i.DisplayName,
			&i.Description,
			&i.License,
			&i.Source,
			&i.TrustState,
			&i.Manifest,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT digest, name, version, display_name, description, license, source,
       trust_state, manifest, installed_at
FROM recipes ORDER BY installed_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.Digest,
			&i.Name,
			&i.Version,
			&i.DisplayName,
			&i.Description,
			&i.License,
			&i.Source,
			&i.TrustState,
			&i.Manifest,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, module, kind, state, resources, input, output, error_code,
       error_message, deployment_id, legacy_identity, created_at, started_at,
       finished_at
FROM runs
WHERE (?1 IS NULL OR module = ?1)
  AND (?2 IS NULL OR state = ?2)
  AND (?3 IS NULL OR created_at < ?3)
ORDER BY created_at DESC
LIMIT ?4
`

type ListRunsParams struct {
	Module        interface{} `json:"module"`
	State         interface{} `json:"state"`
	CreatedBefore interface{} `json:"created_before"`
	Limit         int64       `json:"limit"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns,
		arg.Module,
		arg.State,
		arg.CreatedBefore,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Kind,
			&i.State,
			&i.Resources,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.DeploymentID,
			&i.LegacyIdentity,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, name, purpose, nonce, ciphertext, created_at, updated_at
FROM secrets ORDER BY name
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Purpose,
			&i.Nonce,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, artifact_id, source_node, dest_node, dest_path, credential_hash,
       state, bytes_total, bytes_done, diagnostic, created_at, updated_at
FROM transfers ORDER BY created_at DESC
`

func (q *Queries) ListTransfers(ctx context.Context) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.SourceNode,
			&i.DestNode,
			&i.DestPath,
			&i.CredentialHash,
			&i.State,
			&i.BytesTotal,
			&i.BytesDone,
			&i.Diagnostic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxEventID = `-- name: MaxEventID :one
SELECT COALESCE(MAX(id), 0) FROM events
`

func (q *Queries) MaxEventID(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxEventID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const putModuleSettings = `-- name: PutModuleSettings :exec
INSERT INTO module_settings (module, settings, version)
VALUES (?, ?, ?)
ON CONFLICT (module)
DO UPDATE SET settings = excluded.settings,
              version = excluded.version,
              updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE module_settings.version = ?
`

type PutModuleSettingsParams struct {
	Module   string `json:"module"`
	Settings string `json:"settings"`
	Version  string `json:"version"`
}

func (q *Queries) PutModuleSettings(ctx context.Context, arg PutModuleSettingsParams) error {
	_, err := q.db.ExecContext(ctx, putModuleSettings, arg.Module, arg.Settings, arg.Version)
	return err
}

const recipeReferencedByDeployments = `-- name: RecipeReferencedByDeployments :one
SELECT COUNT(*) FROM deployments WHERE recipe_digest = ?
`

func (q *Queries) RecipeReferencedByDeployments(ctx context.Context, recipeDigest string) (int64, error) {
	row := q.db.QueryRowContext(ctx, recipeReferencedByDeployments, recipeDigest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recipeReferencedByRuns = `-- name: RecipeReferencedByRuns :one
SELECT COUNT(*) FROM runs r
JOIN deployments d ON d.id = r.deployment_id
WHERE d.recipe_digest = ?
`

func (q *Queries) RecipeReferencedByRuns(ctx context.Context, recipeDigest string) (int64, error) {
	row := q.db.QueryRowContext(ctx, recipeReferencedByRuns, recipeDigest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const releaseLeases = `-- name: ReleaseLeases :exec
UPDATE leases SET state = 'released',
                  released_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE owner_kind = ? AND owner_id = ? AND state = 'active'
`

type ReleaseLeasesParams struct {
	OwnerKind string `json:"owner_kind"`
	OwnerID   string `json:"owner_id"`
}

func (q *Queries) ReleaseLeases(ctx context.Context, arg ReleaseLeasesParams) error {
	_, err := q.db.ExecContext(ctx, releaseLeases, arg.OwnerKind, arg.OwnerID)
	return err
}

const saveMigrationPlan = `-- name: SaveMigrationPlan :exec
INSERT INTO migration_plans (plan_digest, request, plan) VALUES (?, ?, ?)
`

type SaveMigrationPlanParams struct {
	PlanDigest string `json:"plan_digest"`
	Request    string `json:"request"`
	Plan       string `json:"plan"`
}

func (q *Queries) SaveMigrationPlan(ctx context.Context, arg SaveMigrationPlanParams) error {
	_, err := q.db.ExecContext(ctx, saveMigrationPlan, arg.PlanDigest, arg.Request, arg.Plan)
	return err
}

const setArtifactValidation = `-- name: SetArtifactValidation :exec
UPDATE artifacts SET validation_state = ? WHERE id = ?
`

type SetArtifactValidationParams struct {
	ValidationState string `json:"validation_state"`
	ID              string `json:"id"`
}

func (q *Queries) SetArtifactValidation(ctx context.Context, arg SetArtifactValidationParams) error {
	_, err := q.db.ExecContext(ctx, setArtifactValidation, arg.ValidationState, arg.ID)
	return err
}

const setDeploymentDispatch = `-- name: SetDeploymentDispatch :exec
UPDATE deployments SET dispatch = ?,
 updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetDeploymentDispatchParams struct {
	Dispatch string `json:"dispatch"`
	ID       string `json:"id"`
}

func (q *Queries) SetDeploymentDispatch(ctx context.Context, arg SetDeploymentDispatchParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentDispatch, arg.Dispatch, arg.ID)
	return err
}

const setNodeCertificate = `-- name: SetNodeCertificate :exec
UPDATE nodes SET certificate_expires_at = ? WHERE id = ?
`

type SetNodeCertificateParams struct {
	CertificateExpiresAt sql.NullString `json:"certificate_expires_at"`
	ID                   string         `json:"id"`
}

func (q *Queries) SetNodeCertificate(ctx context.Context, arg SetNodeCertificateParams) error {
	_, err := q.db.ExecContext(ctx, setNodeCertificate, arg.CertificateExpiresAt, arg.ID)
	return err
}

const setNodeInventory = `-- name: SetNodeInventory :exec
UPDATE nodes SET inventory = ?, agent_version = COALESCE(?, agent_version) WHERE id = ?
`

type SetNodeInventoryParams struct {
	Inventory    sql.NullString `json:"inventory"`
	AgentVersion sql.NullString `json:"agent_version"`
	ID           string         `json:"id"`
}

func (q *Queries) SetNodeInventory(ctx context.Context, arg SetNodeInventoryParams) error {
	_, err := q.db.ExecContext(ctx, setNodeInventory, arg.Inventory, arg.AgentVersion, arg.ID)
	return err
}

const setNodeStatus = `-- name: SetNodeStatus :exec
UPDATE nodes SET status = ?, last_heartbeat = COALESCE(?, last_heartbeat) WHERE id = ?
`

type SetNodeStatusParams struct {
	Status        string         `json:"status"`
	LastHeartbeat sql.NullString `json:"last_heartbeat"`
	ID            string         `json:"id"`
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, setNodeStatus, arg.Status, arg.LastHeartbeat, arg.ID)
	return err
}

const setNodeVersion = `-- name: SetNodeVersion :exec
UPDATE nodes SET agent_version = ? WHERE id = ?
`

type SetNodeVersionParams struct {
	AgentVersion sql.NullString `json:"agent_version"`
	ID           string         `json:"id"`
}

func (q *Queries) SetNodeVersion(ctx context.Context, arg SetNodeVersionParams) error {
	_, err := q.db.ExecContext(ctx, setNodeVersion, arg.AgentVersion, arg.ID)
	return err
}

const setRunOutput = `-- name: SetRunOutput :exec
UPDATE runs SET output = ? WHERE id = ?
`

type SetRunOutputParams struct {
	Output sql.NullString `json:"output"`
	ID     string         `json:"id"`
}

func (q *Queries) SetRunOutput(ctx context.Context, arg SetRunOutputParams) error {
	_, err := q.db.ExecContext(ctx, setRunOutput, arg.Output, arg.ID)
	return err
}

const updateDeploymentEndpointMetadata = `-- name: UpdateDeploymentEndpointMetadata :exec
UPDATE deployments SET endpoint_model = ?, endpoint_path = ?,
                       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateDeploymentEndpointMetadataParams struct {
	EndpointModel sql.NullString `json:"endpoint_model"`
	EndpointPath  sql.NullString `json:"endpoint_path"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateDeploymentEndpointMetadata(ctx context.Context, arg UpdateDeploymentEndpointMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentEndpointMetadata, arg.EndpointModel, arg.EndpointPath, arg.ID)
	return err
}

const updateDeploymentFabric = `-- name: UpdateDeploymentFabric :exec
UPDATE deployments SET fabric = ? WHERE id = ?
`

type UpdateDeploymentFabricParams struct {
	Fabric sql.NullString `json:"fabric"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateDeploymentFabric(ctx context.Context, arg UpdateDeploymentFabricParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentFabric, arg.Fabric, arg.ID)
	return err
}

const updateDeploymentObserved = `-- name: UpdateDeploymentObserved :exec
UPDATE deployments SET observed_state = ?,
                       endpoint = COALESCE(?, endpoint),
                       model_capabilities = COALESCE(?, model_capabilities),
                       diagnostics = COALESCE(?, diagnostics),
                       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateDeploymentObservedParams struct {
	ObservedState     string         `json:"observed_state"`
	Endpoint          sql.NullString `json:"endpoint"`
	ModelCapabilities sql.NullString `json:"model_capabilities"`
	Diagnostics       string         `json:"diagnostics"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateDeploymentObserved(ctx context.Context, arg UpdateDeploymentObservedParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentObserved,
		arg.ObservedState,
		arg.Endpoint,
		arg.ModelCapabilities,
		arg.Diagnostics,
		arg.ID,
	)
	return err
}

const updateDeploymentRunID = `-- name: UpdateDeploymentRunID :exec
UPDATE deployments SET run_id = ?,
                       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateDeploymentRunIDParams struct {
	RunID sql.NullString `json:"run_id"`
	ID    string         `json:"id"`
}

func (q *Queries) UpdateDeploymentRunID(ctx context.Context, arg UpdateDeploymentRunIDParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentRunID, arg.RunID, arg.ID)
	return err
}

const updateDeploymentState = `-- name: UpdateDeploymentState :exec
UPDATE deployments SET desired_state = ?,
                       updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateDeploymentStateParams struct {
	DesiredState string `json:"desired_state"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateDeploymentState(ctx context.Context, arg UpdateDeploymentStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentState, arg.DesiredState, arg.ID)
	return err
}

const updateFabric = `-- name: UpdateFabric :exec
UPDATE fabrics SET transport = ?, interface_name = ?, address = ?, rdma_device = ?,
                   members = ?, state = ?, diagnostics = ?, version = ?,
                   updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND version = ?
`

type UpdateFabricParams struct {
	Transport     string         `json:"transport"`
	InterfaceName sql.NullString `json:"interface_name"`
	Address       sql.NullString `json:"address"`
	RdmaDevice    sql.NullString `json:"rdma_device"`
	Members       string         `json:"members"`
	State         string         `json:"state"`
	Diagnostics   string         `json:"diagnostics"`
	Version       string         `json:"version"`
	ID            string         `json:"id"`
	Version_2     string         `json:"version_2"`
}

func (q *Queries) UpdateFabric(ctx context.Context, arg UpdateFabricParams) error {
	_, err := q.db.ExecContext(ctx, updateFabric,
		arg.Transport,
		arg.InterfaceName,
		arg.Address,
		arg.RdmaDevice,
		arg.Members,
		arg.State,
		arg.Diagnostics,
		arg.Version,
		arg.ID,
		arg.Version_2,
	)
	return err
}

const updateFabricState = `-- name: UpdateFabricState :exec
UPDATE fabrics SET state = ?, diagnostics = ?,
 updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateFabricStateParams struct {
	State       string `json:"state"`
	Diagnostics string `json:"diagnostics"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateFabricState(ctx context.Context, arg UpdateFabricStateParams) error {
	_, err := q.db.ExecContext(ctx, updateFabricState, arg.State, arg.Diagnostics, arg.ID)
	return err
}

const updateNodeMeta = `-- name: UpdateNodeMeta :exec
UPDATE nodes SET display_name = ?, labels = ? WHERE id = ?
`

type UpdateNodeMetaParams struct {
	DisplayName string `json:"display_name"`
	Labels      string `json:"labels"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateNodeMeta(ctx context.Context, arg UpdateNodeMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeMeta, arg.DisplayName, arg.Labels, arg.ID)
	return err
}

const updateRecipeTrust = `-- name: UpdateRecipeTrust :exec
UPDATE recipes SET trust_state = ? WHERE digest = ?
`

type UpdateRecipeTrustParams struct {
	TrustState string `json:"trust_state"`
	Digest     string `json:"digest"`
}

func (q *Queries) UpdateRecipeTrust(ctx context.Context, arg UpdateRecipeTrustParams) error {
	_, err := q.db.ExecContext(ctx, updateRecipeTrust, arg.TrustState, arg.Digest)
	return err
}

const updateRunState = `-- name: UpdateRunState :exec
UPDATE runs SET state = ?,
                started_at = COALESCE(?, started_at),
                finished_at = COALESCE(?, finished_at),
                error_code = COALESCE(?, error_code),
                error_message = COALESCE(?, error_message)
WHERE id = ?
`

type UpdateRunStateParams struct {
	State        string         `json:"state"`
	StartedAt    sql.NullString `json:"started_at"`
	FinishedAt   sql.NullString `json:"finished_at"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateRunState(ctx context.Context, arg UpdateRunStateParams) error {
	_, err := q.db.ExecContext(ctx, updateRunState,
		arg.State,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updateTransferProgress = `-- name: UpdateTransferProgress :exec
UPDATE transfers SET bytes_done = ?, bytes_total = COALESCE(?, bytes_total),
                     state = 'transferring',
                     updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateTransferProgressParams struct {
	BytesDone  int64  `json:"bytes_done"`
	BytesTotal int64  `json:"bytes_total"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateTransferProgress(ctx context.Context, arg UpdateTransferProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateTransferProgress, arg.BytesDone, arg.BytesTotal, arg.ID)
	return err
}

const updateTransferState = `-- name: UpdateTransferState :exec
UPDATE transfers SET state = ?, diagnostic = ?,
                     updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateTransferStateParams struct {
	State      string         `json:"state"`
	Diagnostic sql.NullString `json:"diagnostic"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTransferState(ctx context.Context, arg UpdateTransferStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTransferState, arg.State, arg.Diagnostic, arg.ID)
	return err
}

const upsertNodeCredential = `-- name: UpsertNodeCredential :exec
INSERT INTO node_credentials (node_id, public_key_pem, serial, issued_at, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (node_id)
DO UPDATE SET public_key_pem = excluded.public_key_pem,
              serial = excluded.serial,
              issued_at = excluded.issued_at,
              expires_at = excluded.expires_at
`

type UpsertNodeCredentialParams struct {
	NodeID       string `json:"node_id"`
	PublicKeyPem string `json:"public_key_pem"`
	Serial       string `json:"serial"`
	IssuedAt     string `json:"issued_at"`
	ExpiresAt    string `json:"expires_at"`
}

func (q *Queries) UpsertNodeCredential(ctx context.Context, arg UpsertNodeCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeCredential,
		arg.NodeID,
		arg.PublicKeyPem,
		arg.Serial,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const upsertPlacement = `-- name: UpsertPlacement :exec
INSERT INTO artifact_placements (artifact_id, node_id, path, state, verified_at, diagnostics, size_bytes)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (artifact_id, node_id, path)
DO UPDATE SET state = excluded.state,
              verified_at = excluded.verified_at,
              diagnostics = excluded.diagnostics,
              size_bytes = excluded.size_bytes
`

type UpsertPlacementParams struct {
	ArtifactID  string         `json:"artifact_id"`
	NodeID      string         `json:"node_id"`
	Path        string         `json:"path"`
	State       string         `json:"state"`
	VerifiedAt  sql.NullString `json:"verified_at"`
	Diagnostics string         `json:"diagnostics"`
	SizeBytes   int64          `json:"size_bytes"`
}

func (q *Queries) UpsertPlacement(ctx context.Context, arg UpsertPlacementParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlacement,
		arg.ArtifactID,
		arg.NodeID,
		arg.Path,
		arg.State,
		arg.VerifiedAt,
		arg.Diagnostics,
		arg.SizeBytes,
	)
	return err
}

const useEnrollmentToken = `-- name: UseEnrollmentToken :one
UPDATE enrollment_tokens
SET used_at = ?, used_by_node = ?
WHERE id = ? AND used_at IS NULL AND expires_at > ?
RETURNING id
`

type UseEnrollmentTokenParams struct {
	UsedAt     sql.NullString `json:"used_at"`
	UsedByNode sql.NullString `json:"used_by_node"`
	ID         string         `json:"id"`
	ExpiresAt  string         `json:"expires_at"`
}

func (q *Queries) UseEnrollmentToken(ctx context.Context, arg UseEnrollmentTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, useEnrollmentToken,
		arg.UsedAt,
		arg.UsedByNode,
		arg.ID,
		arg.ExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
