// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traces.sql

package db

import (
	"context"
	"database/sql"
)

const advanceCodingTraceStream = `-- name: AdvanceCodingTraceStream :execrows
UPDATE coding_trace_streams
SET byte_offset = ?, next_event_sequence = ?, final_offset = ?,
    eof_acknowledged = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE trace_id = ? AND node_id = ? AND rank = ? AND source = ?
  AND byte_offset = ? AND next_event_sequence = ?
`

type AdvanceCodingTraceStreamParams struct {
	ByteOffset          int64         `json:"byte_offset"`
	NextEventSequence   int64         `json:"next_event_sequence"`
	FinalOffset         sql.NullInt64 `json:"final_offset"`
	EofAcknowledged     int64         `json:"eof_acknowledged"`
	TraceID             string        `json:"trace_id"`
	NodeID              string        `json:"node_id"`
	Rank                int64         `json:"rank"`
	Source              string        `json:"source"`
	ByteOffset_2        int64         `json:"byte_offset_2"`
	NextEventSequence_2 int64         `json:"next_event_sequence_2"`
}

func (q *Queries) AdvanceCodingTraceStream(ctx context.Context, arg AdvanceCodingTraceStreamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceCodingTraceStream,
		arg.ByteOffset,
		arg.NextEventSequence,
		arg.FinalOffset,
		arg.EofAcknowledged,
		arg.TraceID,
		arg.NodeID,
		arg.Rank,
		arg.Source,
		arg.ByteOffset_2,
		arg.NextEventSequence_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimSweGymWorkItem = `-- name: ClaimSweGymWorkItem :execrows
UPDATE swe_gym_work_items
SET state = 'running', attempt = attempt + 1, child_run_id = ?, node_id = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state IN ('queued','infrastructure_error')
`

type ClaimSweGymWorkItemParams struct {
	ChildRunID sql.NullString `json:"child_run_id"`
	NodeID     sql.NullString `json:"node_id"`
	ID         string         `json:"id"`
}

func (q *Queries) ClaimSweGymWorkItem(ctx context.Context, arg ClaimSweGymWorkItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimSweGymWorkItem, arg.ChildRunID, arg.NodeID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeCodingTrace = `-- name: CompleteCodingTrace :execrows
UPDATE coding_traces
SET state = 'completed', final_diff = ?, verification_id = ?, success_label = ?,
    failure_kind = ?, token_count = ?, turn_count = ?, redaction_count = ?,
    digest = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'recording'
`

type CompleteCodingTraceParams struct {
	FinalDiff      sql.NullString `json:"final_diff"`
	VerificationID sql.NullString `json:"verification_id"`
	SuccessLabel   sql.NullInt64  `json:"success_label"`
	FailureKind    sql.NullString `json:"failure_kind"`
	TokenCount     int64          `json:"token_count"`
	TurnCount      int64          `json:"turn_count"`
	RedactionCount int64          `json:"redaction_count"`
	Digest         sql.NullString `json:"digest"`
	ID             string         `json:"id"`
}

func (q *Queries) CompleteCodingTrace(ctx context.Context, arg CompleteCodingTraceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeCodingTrace,
		arg.FinalDiff,
		arg.VerificationID,
		arg.SuccessLabel,
		arg.FailureKind,
		arg.TokenCount,
		arg.TurnCount,
		arg.RedactionCount,
		arg.Digest,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCodingTrace = `-- name: CreateCodingTrace :exec
INSERT INTO coding_traces (
    id, run_id, experiment_id, task_id, problem, repository, base_revision,
    model_source, model, scaffold, sampling, state, schema_version,
    redaction_version, retain_until
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'recording', ?, ?, ?)
`

type CreateCodingTraceParams struct {
	ID               string         `json:"id"`
	RunID            string         `json:"run_id"`
	ExperimentID     sql.NullString `json:"experiment_id"`
	TaskID           string         `json:"task_id"`
	Problem          string         `json:"problem"`
	Repository       string         `json:"repository"`
	BaseRevision     string         `json:"base_revision"`
	ModelSource      string         `json:"model_source"`
	Model            string         `json:"model"`
	Scaffold         string         `json:"scaffold"`
	Sampling         string         `json:"sampling"`
	SchemaVersion    string         `json:"schema_version"`
	RedactionVersion string         `json:"redaction_version"`
	RetainUntil      sql.NullString `json:"retain_until"`
}

func (q *Queries) CreateCodingTrace(ctx context.Context, arg CreateCodingTraceParams) error {
	_, err := q.db.ExecContext(ctx, createCodingTrace,
		arg.ID,
		arg.RunID,
		arg.ExperimentID,
		arg.TaskID,
		arg.Problem,
		arg.Repository,
		arg.BaseRevision,
		arg.ModelSource,
		arg.Model,
		arg.Scaffold,
		arg.Sampling,
		arg.SchemaVersion,
		arg.RedactionVersion,
		arg.RetainUntil,
	)
	return err
}

const createCodingTraceExport = `-- name: CreateCodingTraceExport :exec
INSERT INTO coding_trace_exports (id, run_id, state, selection, seed)
VALUES (?, ?, 'queued', ?, ?)
`

type CreateCodingTraceExportParams struct {
	ID        string `json:"id"`
	RunID     string `json:"run_id"`
	Selection string `json:"selection"`
	Seed      int64  `json:"seed"`
}

func (q *Queries) CreateCodingTraceExport(ctx context.Context, arg CreateCodingTraceExportParams) error {
	_, err := q.db.ExecContext(ctx, createCodingTraceExport,
		arg.ID,
		arg.RunID,
		arg.Selection,
		arg.Seed,
	)
	return err
}

const createCodingTraceStream = `-- name: CreateCodingTraceStream :exec
INSERT INTO coding_trace_streams (
    trace_id, node_id, rank, source, byte_offset, next_event_sequence
) VALUES (?, ?, ?, ?, 0, 0)
`

type CreateCodingTraceStreamParams struct {
	TraceID string `json:"trace_id"`
	NodeID  string `json:"node_id"`
	Rank    int64  `json:"rank"`
	Source  string `json:"source"`
}

func (q *Queries) CreateCodingTraceStream(ctx context.Context, arg CreateCodingTraceStreamParams) error {
	_, err := q.db.ExecContext(ctx, createCodingTraceStream,
		arg.TraceID,
		arg.NodeID,
		arg.Rank,
		arg.Source,
	)
	return err
}

const createCodingTraceVerification = `-- name: CreateCodingTraceVerification :exec
INSERT INTO coding_trace_verifications (
    id, trace_id, command, timeout_seconds, exit_status, stdout, stderr,
    fail_to_pass_report, pass_to_pass_report, status, failure_kind
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCodingTraceVerificationParams struct {
	ID               string         `json:"id"`
	TraceID          string         `json:"trace_id"`
	Command          string         `json:"command"`
	TimeoutSeconds   int64          `json:"timeout_seconds"`
	ExitStatus       sql.NullInt64  `json:"exit_status"`
	Stdout           string         `json:"stdout"`
	Stderr           string         `json:"stderr"`
	FailToPassReport string         `json:"fail_to_pass_report"`
	PassToPassReport string         `json:"pass_to_pass_report"`
	Status           string         `json:"status"`
	FailureKind      sql.NullString `json:"failure_kind"`
}

func (q *Queries) CreateCodingTraceVerification(ctx context.Context, arg CreateCodingTraceVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createCodingTraceVerification,
		arg.ID,
		arg.TraceID,
		arg.Command,
		arg.TimeoutSeconds,
		arg.ExitStatus,
		arg.Stdout,
		arg.Stderr,
		arg.FailToPassReport,
		arg.PassToPassReport,
		arg.Status,
		arg.FailureKind,
	)
	return err
}

const createSweGymExperiment = `-- name: CreateSweGymExperiment :exec
INSERT INTO swe_gym_experiments (
    id, state, config, config_digest, plan, plan_digest, manifest, total_items
) VALUES (?, 'planned', ?, ?, ?, ?, ?, ?)
`

type CreateSweGymExperimentParams struct {
	ID           string `json:"id"`
	Config       string `json:"config"`
	ConfigDigest string `json:"config_digest"`
	Plan         string `json:"plan"`
	PlanDigest   string `json:"plan_digest"`
	Manifest     string `json:"manifest"`
	TotalItems   int64  `json:"total_items"`
}

func (q *Queries) CreateSweGymExperiment(ctx context.Context, arg CreateSweGymExperimentParams) error {
	_, err := q.db.ExecContext(ctx, createSweGymExperiment,
		arg.ID,
		arg.Config,
		arg.ConfigDigest,
		arg.Plan,
		arg.PlanDigest,
		arg.Manifest,
		arg.TotalItems,
	)
	return err
}

const createSweGymWorkItem = `-- name: CreateSweGymWorkItem :exec
INSERT INTO swe_gym_work_items (id, experiment_id, task_id, rollout_index, state)
VALUES (?, ?, ?, ?, 'queued')
`

type CreateSweGymWorkItemParams struct {
	ID           string `json:"id"`
	ExperimentID string `json:"experiment_id"`
	TaskID       string `json:"task_id"`
	RolloutIndex int64  `json:"rollout_index"`
}

func (q *Queries) CreateSweGymWorkItem(ctx context.Context, arg CreateSweGymWorkItemParams) error {
	_, err := q.db.ExecContext(ctx, createSweGymWorkItem,
		arg.ID,
		arg.ExperimentID,
		arg.TaskID,
		arg.RolloutIndex,
	)
	return err
}

const deleteCodingTrace = `-- name: DeleteCodingTrace :execrows
DELETE FROM coding_traces WHERE id = ? AND state != 'recording'
`

func (q *Queries) DeleteCodingTrace(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCodingTrace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredCodingTraces = `-- name: DeleteExpiredCodingTraces :execrows
DELETE FROM coding_traces
WHERE pinned = 0 AND state != 'recording' AND retain_until IS NOT NULL AND retain_until < ?
`

func (q *Queries) DeleteExpiredCodingTraces(ctx context.Context, retainUntil sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredCodingTraces, retainUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishCodingTraceExport = `-- name: FinishCodingTraceExport :execrows
UPDATE coding_trace_exports
SET state = ?, artifact_path = ?, manifest_digest = ?, canonical_count = ?,
    policy_count = ?, verifier_count = ?, excluded_count = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type FinishCodingTraceExportParams struct {
	State          string         `json:"state"`
	ArtifactPath   sql.NullString `json:"artifact_path"`
	ManifestDigest sql.NullString `json:"manifest_digest"`
	CanonicalCount int64          `json:"canonical_count"`
	PolicyCount    int64          `json:"policy_count"`
	VerifierCount  int64          `json:"verifier_count"`
	ExcludedCount  int64          `json:"excluded_count"`
	ID             string         `json:"id"`
}

func (q *Queries) FinishCodingTraceExport(ctx context.Context, arg FinishCodingTraceExportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishCodingTraceExport,
		arg.State,
		arg.ArtifactPath,
		arg.ManifestDigest,
		arg.CanonicalCount,
		arg.PolicyCount,
		arg.VerifierCount,
		arg.ExcludedCount,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishSweGymExperiment = `-- name: FinishSweGymExperiment :execrows
UPDATE swe_gym_experiments
SET state = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type FinishSweGymExperimentParams struct {
	State string `json:"state"`
	ID    string `json:"id"`
}

func (q *Queries) FinishSweGymExperiment(ctx context.Context, arg FinishSweGymExperimentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishSweGymExperiment, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishSweGymWorkItem = `-- name: FinishSweGymWorkItem :execrows
UPDATE swe_gym_work_items
SET state = ?, trace_id = ?, output = ?, error_code = ?, error_message = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type FinishSweGymWorkItemParams struct {
	State        string         `json:"state"`
	TraceID      sql.NullString `json:"trace_id"`
	Output       sql.NullString `json:"output"`
	ErrorCode    sql.NullString `json:"error_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) FinishSweGymWorkItem(ctx context.Context, arg FinishSweGymWorkItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishSweGymWorkItem,
		arg.State,
		arg.TraceID,
		arg.Output,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCodingTrace = `-- name: GetCodingTrace :one
SELECT id, run_id, experiment_id, task_id, problem, repository, base_revision, model_source, model, scaffold, sampling, state, final_diff, verification_id, success_label, failure_kind, token_count, turn_count, pinned, retain_until, schema_version, redaction_version, redaction_count, digest, created_at, updated_at, finished_at FROM coding_traces WHERE id = ?
`

func (q *Queries) GetCodingTrace(ctx context.Context, id string) (CodingTrace, error) {
	row := q.db.QueryRowContext(ctx, getCodingTrace, id)
	var i CodingTrace
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ExperimentID,
		&i.TaskID,
		&i.Problem,
		&i.Repository,
		&i.BaseRevision,
		&i.ModelSource,
		&i.Model,
		&i.Scaffold,
		&i.Sampling,
		&i.State,
		&i.FinalDiff,
		&i.VerificationID,
		&i.SuccessLabel,
		&i.FailureKind,
		&i.TokenCount,
		&i.TurnCount,
		&i.Pinned,
		&i.RetainUntil,
		&i.SchemaVersion,
		&i.RedactionVersion,
		&i.RedactionCount,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getCodingTraceByRunID = `-- name: GetCodingTraceByRunID :one
SELECT id, run_id, experiment_id, task_id, problem, repository, base_revision, model_source, model, scaffold, sampling, state, final_diff, verification_id, success_label, failure_kind, token_count, turn_count, pinned, retain_until, schema_version, redaction_version, redaction_count, digest, created_at, updated_at, finished_at FROM coding_traces WHERE run_id = ?
`

func (q *Queries) GetCodingTraceByRunID(ctx context.Context, runID string) (CodingTrace, error) {
	row := q.db.QueryRowContext(ctx, getCodingTraceByRunID, runID)
	var i CodingTrace
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ExperimentID,
		&i.TaskID,
		&i.Problem,
		&i.Repository,
		&i.BaseRevision,
		&i.ModelSource,
		&i.Model,
		&i.Scaffold,
		&i.Sampling,
		&i.State,
		&i.FinalDiff,
		&i.VerificationID,
		&i.SuccessLabel,
		&i.FailureKind,
		&i.TokenCount,
		&i.TurnCount,
		&i.Pinned,
		&i.RetainUntil,
		&i.SchemaVersion,
		&i.RedactionVersion,
		&i.RedactionCount,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getCodingTraceEvent = `-- name: GetCodingTraceEvent :one
SELECT trace_id, sequence, event_id, agent_id, parent_agent_id, occurred_at, kind, payload, input_tokens, output_tokens, redaction_count FROM coding_trace_events WHERE trace_id = ? AND sequence = ?
`

type GetCodingTraceEventParams struct {
	TraceID  string `json:"trace_id"`
	Sequence int64  `json:"sequence"`
}

func (q *Queries) GetCodingTraceEvent(ctx context.Context, arg GetCodingTraceEventParams) (CodingTraceEvent, error) {
	row := q.db.QueryRowContext(ctx, getCodingTraceEvent, arg.TraceID, arg.Sequence)
	var i CodingTraceEvent
	err := row.Scan(
		&i.TraceID,
		&i.Sequence,
		&i.EventID,
		&i.AgentID,
		&i.ParentAgentID,
		&i.OccurredAt,
		&i.Kind,
		&i.Payload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.RedactionCount,
	)
	return i, err
}

const getCodingTraceExport = `-- name: GetCodingTraceExport :one
SELECT id, run_id, state, selection, seed, artifact_path, manifest_digest, canonical_count, policy_count, verifier_count, excluded_count, created_at, updated_at, finished_at FROM coding_trace_exports WHERE id = ?
`

func (q *Queries) GetCodingTraceExport(ctx context.Context, id string) (CodingTraceExport, error) {
	row := q.db.QueryRowContext(ctx, getCodingTraceExport, id)
	var i CodingTraceExport
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.State,
		&i.Selection,
		&i.Seed,
		&i.ArtifactPath,
		&i.ManifestDigest,
		&i.CanonicalCount,
		&i.PolicyCount,
		&i.VerifierCount,
		&i.ExcludedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getCodingTraceStream = `-- name: GetCodingTraceStream :one
SELECT trace_id, node_id, rank, source, byte_offset, next_event_sequence, final_offset, eof_acknowledged, updated_at FROM coding_trace_streams
WHERE trace_id = ? AND node_id = ? AND rank = ? AND source = ?
`

type GetCodingTraceStreamParams struct {
	TraceID string `json:"trace_id"`
	NodeID  string `json:"node_id"`
	Rank    int64  `json:"rank"`
	Source  string `json:"source"`
}

func (q *Queries) GetCodingTraceStream(ctx context.Context, arg GetCodingTraceStreamParams) (CodingTraceStream, error) {
	row := q.db.QueryRowContext(ctx, getCodingTraceStream,
		arg.TraceID,
		arg.NodeID,
		arg.Rank,
		arg.Source,
	)
	var i CodingTraceStream
	err := row.Scan(
		&i.TraceID,
		&i.NodeID,
		&i.Rank,
		&i.Source,
		&i.ByteOffset,
		&i.NextEventSequence,
		&i.FinalOffset,
		&i.EofAcknowledged,
		&i.UpdatedAt,
	)
	return i, err
}

const getCodingTraceVerification = `-- name: GetCodingTraceVerification :one
SELECT id, trace_id, command, timeout_seconds, exit_status, stdout, stderr, fail_to_pass_report, pass_to_pass_report, status, failure_kind, created_at FROM coding_trace_verifications WHERE trace_id = ?
`

func (q *Queries) GetCodingTraceVerification(ctx context.Context, traceID string) (CodingTraceVerification, error) {
	row := q.db.QueryRowContext(ctx, getCodingTraceVerification, traceID)
	var i CodingTraceVerification
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.Command,
		&i.TimeoutSeconds,
		&i.ExitStatus,
		&i.Stdout,
		&i.Stderr,
		&i.FailToPassReport,
		&i.PassToPassReport,
		&i.Status,
		&i.FailureKind,
		&i.CreatedAt,
	)
	return i, err
}

const getSweGymExperiment = `-- name: GetSweGymExperiment :one
SELECT id, run_id, state, config, config_digest, "plan", plan_digest, manifest, total_items, completed_items, resolved_items, unresolved_items, infrastructure_errors, created_at, updated_at, finished_at FROM swe_gym_experiments WHERE id = ?
`

func (q *Queries) GetSweGymExperiment(ctx context.Context, id string) (SweGymExperiment, error) {
	row := q.db.QueryRowContext(ctx, getSweGymExperiment, id)
	var i SweGymExperiment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.State,
		&i.Config,
		&i.ConfigDigest,
		&i.Plan,
		&i.PlanDigest,
		&i.Manifest,
		&i.TotalItems,
		&i.CompletedItems,
		&i.ResolvedItems,
		&i.UnresolvedItems,
		&i.InfrastructureErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertCodingTraceEvent = `-- name: InsertCodingTraceEvent :exec
INSERT INTO coding_trace_events (
    trace_id, sequence, event_id, agent_id, parent_agent_id, occurred_at,
    kind, payload, input_tokens, output_tokens, redaction_count
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCodingTraceEventParams struct {
	TraceID        string `json:"trace_id"`
	Sequence       int64  `json:"sequence"`
	EventID        string `json:"event_id"`
	AgentID        string `json:"agent_id"`
	ParentAgentID  string `json:"parent_agent_id"`
	OccurredAt     string `json:"occurred_at"`
	Kind           string `json:"kind"`
	Payload        string `json:"payload"`
	InputTokens    int64  `json:"input_tokens"`
	OutputTokens   int64  `json:"output_tokens"`
	RedactionCount int64  `json:"redaction_count"`
}

func (q *Queries) InsertCodingTraceEvent(ctx context.Context, arg InsertCodingTraceEventParams) error {
	_, err := q.db.ExecContext(ctx, insertCodingTraceEvent,
		arg.TraceID,
		arg.Sequence,
		arg.EventID,
		arg.AgentID,
		arg.ParentAgentID,
		arg.OccurredAt,
		arg.Kind,
		arg.Payload,
		arg.InputTokens,
		arg.OutputTokens,
		arg.RedactionCount,
	)
	return err
}

const interruptCodingTrace = `-- name: InterruptCodingTrace :execrows
UPDATE coding_traces
SET state = 'interrupted', failure_kind = ?, token_count = ?, turn_count = ?,
    redaction_count = ?, digest = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    finished_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'recording'
`

type InterruptCodingTraceParams struct {
	FailureKind    sql.NullString `json:"failure_kind"`
	TokenCount     int64          `json:"token_count"`
	TurnCount      int64          `json:"turn_count"`
	RedactionCount int64          `json:"redaction_count"`
	Digest         sql.NullString `json:"digest"`
	ID             string         `json:"id"`
}

func (q *Queries) InterruptCodingTrace(ctx context.Context, arg InterruptCodingTraceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, interruptCodingTrace,
		arg.FailureKind,
		arg.TokenCount,
		arg.TurnCount,
		arg.RedactionCount,
		arg.Digest,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAllCodingTraceEvents = `-- name: ListAllCodingTraceEvents :many
SELECT trace_id, sequence, event_id, agent_id, parent_agent_id, occurred_at, kind, payload, input_tokens, output_tokens, redaction_count FROM coding_trace_events
WHERE trace_id = ?
ORDER BY sequence
`

func (q *Queries) ListAllCodingTraceEvents(ctx context.Context, traceID string) ([]CodingTraceEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAllCodingTraceEvents, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodingTraceEvent
	for rows.Next() {
		var i CodingTraceEvent
		if err := rows.Scan(
			&i.TraceID,
			&i.Sequence,
			&i.EventID,
			&i.AgentID,
			&i.ParentAgentID,
			&i.OccurredAt,
			&i.Kind,
			&i.Payload,
			&i.InputTokens,
			&i.OutputTokens,
			&i.RedactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodingTraceEvents = `-- name: ListCodingTraceEvents :many
SELECT trace_id, sequence, event_id, agent_id, parent_agent_id, occurred_at, kind, payload, input_tokens, output_tokens, redaction_count FROM coding_trace_events
WHERE trace_id = ? AND sequence >= ?
ORDER BY sequence
LIMIT ?
`

type ListCodingTraceEventsParams struct {
	TraceID  string `json:"trace_id"`
	Sequence int64  `json:"sequence"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListCodingTraceEvents(ctx context.Context, arg ListCodingTraceEventsParams) ([]CodingTraceEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCodingTraceEvents, arg.TraceID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodingTraceEvent
	for rows.Next() {
		var i CodingTraceEvent
		if err := rows.Scan(
			&i.TraceID,
			&i.Sequence,
			&i.EventID,
			&i.AgentID,
			&i.ParentAgentID,
			&i.OccurredAt,
			&i.Kind,
			&i.Payload,
			&i.InputTokens,
			&i.OutputTokens,
			&i.RedactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodingTraceExports = `-- name: ListCodingTraceExports :many
SELECT id, run_id, state, selection, seed, artifact_path, manifest_digest, canonical_count, policy_count, verifier_count, excluded_count, created_at, updated_at, finished_at FROM coding_trace_exports ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListCodingTraceExports(ctx context.Context, limit int64) ([]CodingTraceExport, error) {
	rows, err := q.db.QueryContext(ctx, listCodingTraceExports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodingTraceExport
	for rows.Next() {
		var i CodingTraceExport
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.State,
			&i.Selection,
			&i.Seed,
			&i.ArtifactPath,
			&i.ManifestDigest,
			&i.CanonicalCount,
			&i.PolicyCount,
			&i.VerifierCount,
			&i.ExcludedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodingTraces = `-- name: ListCodingTraces :many
SELECT id, run_id, experiment_id, task_id, problem, repository, base_revision, model_source, model, scaffold, sampling, state, final_diff, verification_id, success_label, failure_kind, token_count, turn_count, pinned, retain_until, schema_version, redaction_version, redaction_count, digest, created_at, updated_at, finished_at FROM coding_traces
WHERE (?1 IS NULL OR state = ?1)
  AND (?2 IS NULL OR task_id = ?2)
  AND (?3 IS NULL OR success_label = ?3)
  AND (?4 IS NULL OR created_at < ?4)
ORDER BY created_at DESC, id DESC
LIMIT ?5
`

type ListCodingTracesParams struct {
	State         interface{} `json:"state"`
	TaskID        interface{} `json:"task_id"`
	SuccessLabel  interface{} `json:"success_label"`
	CreatedBefore interface{} `json:"created_before"`
	Limit         int64       `json:"limit"`
}

func (q *Queries) ListCodingTraces(ctx context.Context, arg ListCodingTracesParams) ([]CodingTrace, error) {
	rows, err := q.db.QueryContext(ctx, listCodingTraces,
		arg.State,
		arg.TaskID,
		arg.SuccessLabel,
		arg.CreatedBefore,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodingTrace
	for rows.Next() {
		var i CodingTrace
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ExperimentID,
			&i.TaskID,
			&i.Problem,
			&i.Repository,
			&i.BaseRevision,
			&i.ModelSource,
			&i.Model,
			&i.Scaffold,
			&i.Sampling,
			&i.State,
			&i.FinalDiff,
			&i.VerificationID,
			&i.SuccessLabel,
			&i.FailureKind,
			&i.TokenCount,
			&i.TurnCount,
			&i.Pinned,
			&i.RetainUntil,
			&i.SchemaVersion,
			&i.RedactionVersion,
			&i.RedactionCount,
			&i.Digest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodingTracesForExport = `-- name: ListCodingTracesForExport :many
SELECT id, run_id, experiment_id, task_id, problem, repository, base_revision, model_source, model, scaffold, sampling, state, final_diff, verification_id, success_label, failure_kind, token_count, turn_count, pinned, retain_until, schema_version, redaction_version, redaction_count, digest, created_at, updated_at, finished_at FROM coding_traces
WHERE (?1 IS NULL OR experiment_id = ?1)
  AND state != 'recording'
ORDER BY task_id, turn_count, id
`

func (q *Queries) ListCodingTracesForExport(ctx context.Context, experimentID interface{}) ([]CodingTrace, error) {
	rows, err := q.db.QueryContext(ctx, listCodingTracesForExport, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodingTrace
	for rows.Next() {
		var i CodingTrace
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ExperimentID,
			&i.TaskID,
			&i.Problem,
			&i.Repository,
			&i.BaseRevision,
			&i.ModelSource,
			&i.Model,
			&i.Scaffold,
			&i.Sampling,
			&i.State,
			&i.FinalDiff,
			&i.VerificationID,
			&i.SuccessLabel,
			&i.FailureKind,
			&i.TokenCount,
			&i.TurnCount,
			&i.Pinned,
			&i.RetainUntil,
			&i.SchemaVersion,
			&i.RedactionVersion,
			&i.RedactionCount,
			&i.Digest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweGymExperiments = `-- name: ListSweGymExperiments :many
SELECT id, run_id, state, config, config_digest, "plan", plan_digest, manifest, total_items, completed_items, resolved_items, unresolved_items, infrastructure_errors, created_at, updated_at, finished_at FROM swe_gym_experiments
WHERE (?1 IS NULL OR created_at < ?1)
ORDER BY created_at DESC, id DESC LIMIT ?2
`

type ListSweGymExperimentsParams struct {
	CreatedBefore interface{} `json:"created_before"`
	Limit         int64       `json:"limit"`
}

func (q *Queries) ListSweGymExperiments(ctx context.Context, arg ListSweGymExperimentsParams) ([]SweGymExperiment, error) {
	rows, err := q.db.QueryContext(ctx, listSweGymExperiments, arg.CreatedBefore, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweGymExperiment
	for rows.Next() {
		var i SweGymExperiment
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.State,
			&i.Config,
			&i.ConfigDigest,
			&i.Plan,
			&i.PlanDigest,
			&i.Manifest,
			&i.TotalItems,
			&i.CompletedItems,
			&i.ResolvedItems,
			&i.UnresolvedItems,
			&i.InfrastructureErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweGymWorkItems = `-- name: ListSweGymWorkItems :many
SELECT id, experiment_id, task_id, rollout_index, attempt, state, child_run_id, trace_id, node_id, output, error_code, error_message, created_at, updated_at, finished_at FROM swe_gym_work_items WHERE experiment_id = ? ORDER BY task_id, rollout_index
`

func (q *Queries) ListSweGymWorkItems(ctx context.Context, experimentID string) ([]SweGymWorkItem, error) {
	rows, err := q.db.QueryContext(ctx, listSweGymWorkItems, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweGymWorkItem
	for rows.Next() {
		var i SweGymWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.TaskID,
			&i.RolloutIndex,
			&i.Attempt,
			&i.State,
			&i.ChildRunID,
			&i.TraceID,
			&i.NodeID,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recountSweGymExperiment = `-- name: RecountSweGymExperiment :exec
UPDATE swe_gym_experiments SET
    completed_items = (SELECT COUNT(*) FROM swe_gym_work_items wi WHERE wi.experiment_id = ?1 AND wi.state IN ('resolved','unresolved','infrastructure_error','cancelled')),
    resolved_items = (SELECT COUNT(*) FROM swe_gym_work_items wi WHERE wi.experiment_id = ?1 AND wi.state = 'resolved'),
    unresolved_items = (SELECT COUNT(*) FROM swe_gym_work_items wi WHERE wi.experiment_id = ?1 AND wi.state = 'unresolved'),
    infrastructure_errors = (SELECT COUNT(*) FROM swe_gym_work_items wi WHERE wi.experiment_id = ?1 AND wi.state = 'infrastructure_error'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?1
`

func (q *Queries) RecountSweGymExperiment(ctx context.Context, experimentID string) error {
	_, err := q.db.ExecContext(ctx, recountSweGymExperiment, experimentID)
	return err
}

const setCodingTracePinned = `-- name: SetCodingTracePinned :execrows
UPDATE coding_traces
SET pinned = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type SetCodingTracePinnedParams struct {
	Pinned int64  `json:"pinned"`
	ID     string `json:"id"`
}

func (q *Queries) SetCodingTracePinned(ctx context.Context, arg SetCodingTracePinnedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCodingTracePinned, arg.Pinned, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSweGymExperimentRun = `-- name: SetSweGymExperimentRun :execrows
UPDATE swe_gym_experiments
SET run_id = ?, state = 'queued', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND state = 'planned' AND plan_digest = ?
`

type SetSweGymExperimentRunParams struct {
	RunID      sql.NullString `json:"run_id"`
	ID         string         `json:"id"`
	PlanDigest string         `json:"plan_digest"`
}

func (q *Queries) SetSweGymExperimentRun(ctx context.Context, arg SetSweGymExperimentRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSweGymExperimentRun, arg.RunID, arg.ID, arg.PlanDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSweGymWorkItemQueued = `-- name: SetSweGymWorkItemQueued :execrows
UPDATE swe_gym_work_items
SET state = 'queued', child_run_id = NULL, node_id = NULL, error_code = NULL,
    error_message = NULL, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    finished_at = NULL
WHERE id = ? AND state IN ('cancelled','infrastructure_error')
`

func (q *Queries) SetSweGymWorkItemQueued(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSweGymWorkItemQueued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCodingTraceExport = `-- name: UpdateCodingTraceExport :execrows
UPDATE coding_trace_exports
SET state = ?1, artifact_path = ?2, manifest_digest = ?3, canonical_count = ?4,
    policy_count = ?5, verifier_count = ?6, excluded_count = ?7,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?8
`

type UpdateCodingTraceExportParams struct {
	State          string         `json:"state"`
	ArtifactPath   sql.NullString `json:"artifact_path"`
	ManifestDigest sql.NullString `json:"manifest_digest"`
	CanonicalCount int64          `json:"canonical_count"`
	PolicyCount    int64          `json:"policy_count"`
	VerifierCount  int64          `json:"verifier_count"`
	ExcludedCount  int64          `json:"excluded_count"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateCodingTraceExport(ctx context.Context, arg UpdateCodingTraceExportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCodingTraceExport,
		arg.State,
		arg.ArtifactPath,
		arg.ManifestDigest,
		arg.CanonicalCount,
		arg.PolicyCount,
		arg.VerifierCount,
		arg.ExcludedCount,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSweGymExperimentState = `-- name: UpdateSweGymExperimentState :execrows
UPDATE swe_gym_experiments
SET state = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?2
`

type UpdateSweGymExperimentStateParams struct {
	State string `json:"state"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateSweGymExperimentState(ctx context.Context, arg UpdateSweGymExperimentStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSweGymExperimentState, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
