// Package backend provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package backend

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CodingTraceModelSource.
const (
	CodingTraceModelSourceExternalApi   CodingTraceModelSource = "external_api"
	CodingTraceModelSourceLmwDeployment CodingTraceModelSource = "lmw_deployment"
)

// Valid indicates whether the value is a known member of the CodingTraceModelSource enum.
func (e CodingTraceModelSource) Valid() bool {
	switch e {
	case CodingTraceModelSourceExternalApi:
		return true
	case CodingTraceModelSourceLmwDeployment:
		return true
	default:
		return false
	}
}

// Defines values for CodingTraceState.
const (
	CodingTraceStateCompleted   CodingTraceState = "completed"
	CodingTraceStateInterrupted CodingTraceState = "interrupted"
	CodingTraceStateRecording   CodingTraceState = "recording"
)

// Valid indicates whether the value is a known member of the CodingTraceState enum.
func (e CodingTraceState) Valid() bool {
	switch e {
	case CodingTraceStateCompleted:
		return true
	case CodingTraceStateInterrupted:
		return true
	case CodingTraceStateRecording:
		return true
	default:
		return false
	}
}

// Defines values for CodingTraceDetailModelSource.
const (
	CodingTraceDetailModelSourceExternalApi   CodingTraceDetailModelSource = "external_api"
	CodingTraceDetailModelSourceLmwDeployment CodingTraceDetailModelSource = "lmw_deployment"
)

// Valid indicates whether the value is a known member of the CodingTraceDetailModelSource enum.
func (e CodingTraceDetailModelSource) Valid() bool {
	switch e {
	case CodingTraceDetailModelSourceExternalApi:
		return true
	case CodingTraceDetailModelSourceLmwDeployment:
		return true
	default:
		return false
	}
}

// Defines values for CodingTraceDetailState.
const (
	CodingTraceDetailStateCompleted   CodingTraceDetailState = "completed"
	CodingTraceDetailStateInterrupted CodingTraceDetailState = "interrupted"
	CodingTraceDetailStateRecording   CodingTraceDetailState = "recording"
)

// Valid indicates whether the value is a known member of the CodingTraceDetailState enum.
func (e CodingTraceDetailState) Valid() bool {
	switch e {
	case CodingTraceDetailStateCompleted:
		return true
	case CodingTraceDetailStateInterrupted:
		return true
	case CodingTraceDetailStateRecording:
		return true
	default:
		return false
	}
}

// Defines values for RunState.
const (
	RunStateCancelled   RunState = "cancelled"
	RunStateCancelling  RunState = "cancelling"
	RunStateFailed      RunState = "failed"
	RunStateInterrupted RunState = "interrupted"
	RunStatePlanning    RunState = "planning"
	RunStateQueued      RunState = "queued"
	RunStateRunning     RunState = "running"
	RunStateSucceeded   RunState = "succeeded"
	RunStateVerifying   RunState = "verifying"
	RunStateWaiting     RunState = "waiting"
)

// Valid indicates whether the value is a known member of the RunState enum.
func (e RunState) Valid() bool {
	switch e {
	case RunStateCancelled:
		return true
	case RunStateCancelling:
		return true
	case RunStateFailed:
		return true
	case RunStateInterrupted:
		return true
	case RunStatePlanning:
		return true
	case RunStateQueued:
		return true
	case RunStateRunning:
		return true
	case RunStateSucceeded:
		return true
	case RunStateVerifying:
		return true
	case RunStateWaiting:
		return true
	default:
		return false
	}
}

// Defines values for SweGymConfigDataset.
const (
	Full SweGymConfigDataset = "full"
	Lite SweGymConfigDataset = "lite"
)

// Valid indicates whether the value is a known member of the SweGymConfigDataset enum.
func (e SweGymConfigDataset) Valid() bool {
	switch e {
	case Full:
		return true
	case Lite:
		return true
	default:
		return false
	}
}

// Defines values for SweGymConfigModelSource.
const (
	SweGymConfigModelSourceExternalApi   SweGymConfigModelSource = "external_api"
	SweGymConfigModelSourceLmwDeployment SweGymConfigModelSource = "lmw_deployment"
)

// Valid indicates whether the value is a known member of the SweGymConfigModelSource enum.
func (e SweGymConfigModelSource) Valid() bool {
	switch e {
	case SweGymConfigModelSourceExternalApi:
		return true
	case SweGymConfigModelSourceLmwDeployment:
		return true
	default:
		return false
	}
}

// Defines values for SweGymConfigPreset.
const (
	Custom  SweGymConfigPreset = "custom"
	PaperD0 SweGymConfigPreset = "paper-d0"
	PaperD1 SweGymConfigPreset = "paper-d1"
	PaperD2 SweGymConfigPreset = "paper-d2"
)

// Valid indicates whether the value is a known member of the SweGymConfigPreset enum.
func (e SweGymConfigPreset) Valid() bool {
	switch e {
	case Custom:
		return true
	case PaperD0:
		return true
	case PaperD1:
		return true
	case PaperD2:
		return true
	default:
		return false
	}
}

// Defines values for SweGymConfigRuntime.
const (
	LmwLocal        SweGymConfigRuntime = "lmw_local"
	OpenhandsRemote SweGymConfigRuntime = "openhands_remote"
)

// Valid indicates whether the value is a known member of the SweGymConfigRuntime enum.
func (e SweGymConfigRuntime) Valid() bool {
	switch e {
	case LmwLocal:
		return true
	case OpenhandsRemote:
		return true
	default:
		return false
	}
}

// Defines values for TraceVerificationStatus.
const (
	InfrastructureError TraceVerificationStatus = "infrastructure_error"
	Resolved            TraceVerificationStatus = "resolved"
	Unresolved          TraceVerificationStatus = "unresolved"
)

// Valid indicates whether the value is a known member of the TraceVerificationStatus enum.
func (e TraceVerificationStatus) Valid() bool {
	switch e {
	case InfrastructureError:
		return true
	case Resolved:
		return true
	case Unresolved:
		return true
	default:
		return false
	}
}

// CodingTrace defines model for CodingTrace.
type CodingTrace struct {
	BaseRevision     string                  `json:"base_revision"`
	CreatedAt        time.Time               `json:"created_at"`
	Digest           *string                 `json:"digest,omitempty"`
	ExperimentId     *string                 `json:"experiment_id,omitempty"`
	FailureKind      *string                 `json:"failure_kind,omitempty"`
	FinalDiff        *string                 `json:"final_diff,omitempty"`
	FinishedAt       *time.Time              `json:"finished_at,omitempty"`
	Id               string                  `json:"id"`
	Model            string                  `json:"model"`
	ModelSource      CodingTraceModelSource  `json:"model_source"`
	Pinned           bool                    `json:"pinned"`
	Problem          string                  `json:"problem"`
	RedactionCount   int                     `json:"redaction_count"`
	RedactionVersion string                  `json:"redaction_version"`
	Repository       string                  `json:"repository"`
	RunId            string                  `json:"run_id"`
	Sampling         *map[string]interface{} `json:"sampling,omitempty"`
	Scaffold         *string                 `json:"scaffold,omitempty"`
	SchemaVersion    string                  `json:"schema_version"`
	State            CodingTraceState        `json:"state"`
	SuccessLabel     *bool                   `json:"success_label,omitempty"`
	TaskId           string                  `json:"task_id"`
	TokenCount       int                     `json:"token_count"`
	TurnCount        int                     `json:"turn_count"`
}

// CodingTraceModelSource defines model for CodingTrace.ModelSource.
type CodingTraceModelSource string

// CodingTraceState defines model for CodingTrace.State.
type CodingTraceState string

// CodingTraceDetail defines model for CodingTraceDetail.
type CodingTraceDetail struct {
	BaseRevision     string                       `json:"base_revision"`
	CreatedAt        time.Time                    `json:"created_at"`
	Digest           *string                      `json:"digest,omitempty"`
	ExperimentId     *string                      `json:"experiment_id,omitempty"`
	FailureKind      *string                      `json:"failure_kind,omitempty"`
	FinalDiff        *string                      `json:"final_diff,omitempty"`
	FinishedAt       *time.Time                   `json:"finished_at,omitempty"`
	Id               string                       `json:"id"`
	Model            string                       `json:"model"`
	ModelSource      CodingTraceDetailModelSource `json:"model_source"`
	Pinned           bool                         `json:"pinned"`
	Problem          string                       `json:"problem"`
	RedactionCount   int                          `json:"redaction_count"`
	RedactionVersion string                       `json:"redaction_version"`
	Repository       string                       `json:"repository"`
	RunId            string                       `json:"run_id"`
	Sampling         *map[string]interface{}      `json:"sampling,omitempty"`
	Scaffold         *string                      `json:"scaffold,omitempty"`
	SchemaVersion    string                       `json:"schema_version"`
	State            CodingTraceDetailState       `json:"state"`
	SuccessLabel     *bool                        `json:"success_label,omitempty"`
	TaskId           string                       `json:"task_id"`
	TokenCount       int                          `json:"token_count"`
	TurnCount        int                          `json:"turn_count"`
	Verification     *TraceVerification           `json:"verification,omitempty"`
}

// CodingTraceDetailModelSource defines model for CodingTraceDetail.ModelSource.
type CodingTraceDetailModelSource string

// CodingTraceDetailState defines model for CodingTraceDetail.State.
type CodingTraceDetailState string

// CodingTracePage defines model for CodingTracePage.
type CodingTracePage struct {
	Items      []CodingTrace `json:"items"`
	NextCursor string        `json:"next_cursor"`
}

// CodingTraceSettings defines model for CodingTraceSettings.
type CodingTraceSettings struct {
	CaptureReasoning        bool `json:"capture_reasoning"`
	ExportMaxContextTokens  int  `json:"export_max_context_tokens"`
	ExportSuccessCapPerTask int  `json:"export_success_cap_per_task"`
	RetentionDays           int  `json:"retention_days"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable error code, e.g. node.occupied, plan.incompatible
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// Run defines model for Run.
type Run struct {
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	DeploymentId   *openapi_types.UUID     `json:"deployment_id,omitempty"`
	ErrorCode      *string                 `json:"error_code,omitempty"`
	ErrorMessage   *string                 `json:"error_message,omitempty"`
	FinishedAt     *time.Time              `json:"finished_at,omitempty"`
	Id             openapi_types.UUID      `json:"id"`
	Input          *map[string]interface{} `json:"input,omitempty"`
	Kind           string                  `json:"kind"`
	LegacyIdentity *string                 `json:"legacy_identity,omitempty"`
	Module         string                  `json:"module"`
	Output         *map[string]interface{} `json:"output,omitempty"`
	Resources      *struct {
		Accelerators *[]string `json:"accelerators,omitempty"`
		Fabrics      *[]string `json:"fabrics,omitempty"`
		Nodes        *[]string `json:"nodes,omitempty"`
	} `json:"resources,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
	State     RunState   `json:"state"`
}

// RunState defines model for RunState.
type RunState string

// SweGymConfig defines model for SweGymConfig.
type SweGymConfig struct {
	CaptureReasoning       *bool                   `json:"capture_reasoning,omitempty"`
	ContextLimit           *int                    `json:"context_limit,omitempty"`
	Dataset                SweGymConfigDataset     `json:"dataset"`
	DeploymentId           *string                 `json:"deployment_id,omitempty"`
	EligibleNodes          *[]string               `json:"eligible_nodes,omitempty"`
	Endpoint               *string                 `json:"endpoint,omitempty"`
	ImagePrefix            *string                 `json:"image_prefix,omitempty"`
	Limit                  *int                    `json:"limit,omitempty"`
	MaxTurns               int                     `json:"max_turns"`
	Model                  string                  `json:"model"`
	ModelSource            SweGymConfigModelSource `json:"model_source"`
	OutputLimit            *int                    `json:"output_limit,omitempty"`
	PerNodeWorkers         *int                    `json:"per_node_workers,omitempty"`
	Preset                 *SweGymConfigPreset     `json:"preset,omitempty"`
	Repositories           *[]string               `json:"repositories,omitempty"`
	RetryLimit             *int                    `json:"retry_limit,omitempty"`
	RolloutsPerTask        int                     `json:"rollouts_per_task"`
	Runtime                SweGymConfigRuntime     `json:"runtime"`
	RuntimeEndpoint        *string                 `json:"runtime_endpoint,omitempty"`
	RuntimeSecretReference *string                 `json:"runtime_secret_reference,omitempty"`
	SecretReference        *string                 `json:"secret_reference,omitempty"`
	Seed                   *int                    `json:"seed,omitempty"`
	TaskIds                *[]string               `json:"task_ids,omitempty"`
	Temperatures           []float32               `json:"temperatures"`
	TimeoutSeconds         *int                    `json:"timeout_seconds,omitempty"`
	Workers                int                     `json:"workers"`
}

// SweGymConfigDataset defines model for SweGymConfig.Dataset.
type SweGymConfigDataset string

// SweGymConfigModelSource defines model for SweGymConfig.ModelSource.
type SweGymConfigModelSource string

// SweGymConfigPreset defines model for SweGymConfig.Preset.
type SweGymConfigPreset string

// SweGymConfigRuntime defines model for SweGymConfig.Runtime.
type SweGymConfigRuntime string

// SweGymCreate defines model for SweGymCreate.
type SweGymCreate struct {
	Plan SweGymPlan `json:"plan"`
}

// SweGymExperiment defines model for SweGymExperiment.
type SweGymExperiment struct {
	CompletedItems       *int                    `json:"completed_items,omitempty"`
	Config               *SweGymConfig           `json:"config,omitempty"`
	ConfigDigest         *string                 `json:"config_digest,omitempty"`
	CreatedAt            *time.Time              `json:"created_at,omitempty"`
	Id                   *string                 `json:"id,omitempty"`
	InfrastructureErrors *int                    `json:"infrastructure_errors,omitempty"`
	Manifest             *map[string]interface{} `json:"manifest,omitempty"`
	Plan                 *SweGymPlan             `json:"plan,omitempty"`
	PlanDigest           *string                 `json:"plan_digest,omitempty"`
	ResolvedItems        *int                    `json:"resolved_items,omitempty"`
	RunId                *string                 `json:"run_id,omitempty"`
	State                *string                 `json:"state,omitempty"`
	TotalItems           *int                    `json:"total_items,omitempty"`
	UnresolvedItems      *int                    `json:"unresolved_items,omitempty"`
}

// SweGymExperimentDetail defines model for SweGymExperimentDetail.
type SweGymExperimentDetail struct {
	CompletedItems       *int                      `json:"completed_items,omitempty"`
	Config               *SweGymConfig             `json:"config,omitempty"`
	ConfigDigest         *string                   `json:"config_digest,omitempty"`
	CreatedAt            *time.Time                `json:"created_at,omitempty"`
	Id                   *string                   `json:"id,omitempty"`
	InfrastructureErrors *int                      `json:"infrastructure_errors,omitempty"`
	Manifest             *map[string]interface{}   `json:"manifest,omitempty"`
	Plan                 *SweGymPlan               `json:"plan,omitempty"`
	PlanDigest           *string                   `json:"plan_digest,omitempty"`
	ResolvedItems        *int                      `json:"resolved_items,omitempty"`
	RunId                *string                   `json:"run_id,omitempty"`
	State                *string                   `json:"state,omitempty"`
	TotalItems           *int                      `json:"total_items,omitempty"`
	UnresolvedItems      *int                      `json:"unresolved_items,omitempty"`
	WorkItems            *[]map[string]interface{} `json:"work_items,omitempty"`
}

// SweGymExperimentPage defines model for SweGymExperimentPage.
type SweGymExperimentPage struct {
	Items      []SweGymExperiment `json:"items"`
	NextCursor string             `json:"next_cursor"`
}

// SweGymPlan defines model for SweGymPlan.
type SweGymPlan struct {
	Config         SweGymConfig            `json:"config"`
	ConfigDigest   string                  `json:"config_digest"`
	NodeCapacity   *map[string]interface{} `json:"node_capacity,omitempty"`
	PlanDigest     string                  `json:"plan_digest"`
	SamplingMatrix []struct {
		MaxTurns    int     `json:"max_turns"`
		Model       string  `json:"model"`
		Name        string  `json:"name"`
		Rollouts    int     `json:"rollouts"`
		Temperature float32 `json:"temperature"`
	} `json:"sampling_matrix"`
	Sources       map[string]interface{} `json:"sources"`
	Tasks         []SweGymTask           `json:"tasks"`
	TotalRollouts int                    `json:"total_rollouts"`
	Warnings      []string               `json:"warnings"`
}

// SweGymTask defines model for SweGymTask.
type SweGymTask struct {
	BaseCommit       string   `json:"base_commit"`
	FailToPass       []string `json:"fail_to_pass"`
	Image            string   `json:"image"`
	ImageDigest      string   `json:"image_digest"`
	InstanceId       string   `json:"instance_id"`
	PassToPass       []string `json:"pass_to_pass"`
	ProblemStatement string   `json:"problem_statement"`
	Repo             string   `json:"repo"`
	TestPatch        string   `json:"test_patch"`
	Version          *string  `json:"version,omitempty"`
}

// TraceEvent defines model for TraceEvent.
type TraceEvent struct {
	AgentId        *string                `json:"agent_id,omitempty"`
	EventId        string                 `json:"event_id"`
	InputTokens    int                    `json:"input_tokens"`
	Kind           string                 `json:"kind"`
	OccurredAt     time.Time              `json:"occurred_at"`
	OutputTokens   int                    `json:"output_tokens"`
	ParentAgentId  *string                `json:"parent_agent_id,omitempty"`
	Payload        map[string]interface{} `json:"payload"`
	RedactionCount int                    `json:"redaction_count"`
	Sequence       int                    `json:"sequence"`
	TraceId        string                 `json:"trace_id"`
}

// TraceEventPage defines model for TraceEventPage.
type TraceEventPage struct {
	Items      []TraceEvent `json:"items"`
	NextCursor string       `json:"next_cursor"`
}

// TraceExport defines model for TraceExport.
type TraceExport struct {
	ArtifactPath   *string                 `json:"artifact_path,omitempty"`
	CanonicalCount *int                    `json:"canonical_count,omitempty"`
	CreatedAt      *time.Time              `json:"created_at,omitempty"`
	ExcludedCount  *int                    `json:"excluded_count,omitempty"`
	Id             *string                 `json:"id,omitempty"`
	ManifestDigest *string                 `json:"manifest_digest,omitempty"`
	PolicyCount    *int                    `json:"policy_count,omitempty"`
	RunId          *string                 `json:"run_id,omitempty"`
	Seed           *int                    `json:"seed,omitempty"`
	Selection      *map[string]interface{} `json:"selection,omitempty"`
	State          *string                 `json:"state,omitempty"`
	VerifierCount  *int                    `json:"verifier_count,omitempty"`
}

// TraceExportCreate defines model for TraceExportCreate.
type TraceExportCreate struct {
	MaxContextTokens  *int      `json:"max_context_tokens,omitempty"`
	Model             *string   `json:"model,omitempty"`
	Seed              *int      `json:"seed,omitempty"`
	State             *string   `json:"state,omitempty"`
	SuccessCapPerTask *int      `json:"success_cap_per_task,omitempty"`
	TaskIds           *[]string `json:"task_ids,omitempty"`
	Tokenizer         *string   `json:"tokenizer,omitempty"`
	TraceIds          *[]string `json:"trace_ids,omitempty"`
}

// TraceVerification defines model for TraceVerification.
type TraceVerification struct {
	Command          *string                  `json:"command,omitempty"`
	ExitStatus       *int                     `json:"exit_status,omitempty"`
	FailToPassReport *map[string]interface{}  `json:"fail_to_pass_report,omitempty"`
	FailureKind      *string                  `json:"failure_kind,omitempty"`
	Id               *string                  `json:"id,omitempty"`
	PassToPassReport *map[string]interface{}  `json:"pass_to_pass_report,omitempty"`
	Status           *TraceVerificationStatus `json:"status,omitempty"`
	Stderr           *string                  `json:"stderr,omitempty"`
	Stdout           *string                  `json:"stdout,omitempty"`
	TimeoutSeconds   *int                     `json:"timeout_seconds,omitempty"`
}

// TraceVerificationStatus defines model for TraceVerification.Status.
type TraceVerificationStatus string

// ExperimentID defines model for ExperimentID.
type ExperimentID = string

// ExportID defines model for ExportID.
type ExportID = string

// TraceID defines model for TraceID.
type TraceID = string

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// ListCodingTracesParams defines parameters for ListCodingTraces.
type ListCodingTracesParams struct {
	State   *string `form:"state,omitempty" json:"state,omitempty"`
	TaskId  *string `form:"task_id,omitempty" json:"task_id,omitempty"`
	Success *bool   `form:"success,omitempty" json:"success,omitempty"`
	Cursor  *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit   *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PutCodingTraceSettingsParams defines parameters for PutCodingTraceSettings.
type PutCodingTraceSettingsParams struct {
	IfMatch string `json:"If-Match"`
}

// ListCodingTraceEventsParams defines parameters for ListCodingTraceEvents.
type ListCodingTraceEventsParams struct {
	From  *int `form:"from,omitempty" json:"from,omitempty"`
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PinCodingTraceJSONBody defines parameters for PinCodingTrace.
type PinCodingTraceJSONBody struct {
	Pinned bool `json:"pinned"`
}

// CreateCodingTraceExportJSONRequestBody defines body for CreateCodingTraceExport for application/json ContentType.
type CreateCodingTraceExportJSONRequestBody = TraceExportCreate

// PutCodingTraceSettingsJSONRequestBody defines body for PutCodingTraceSettings for application/json ContentType.
type PutCodingTraceSettingsJSONRequestBody = CodingTraceSettings

// CreateSweGymExperimentJSONRequestBody defines body for CreateSweGymExperiment for application/json ContentType.
type CreateSweGymExperimentJSONRequestBody = SweGymCreate

// PlanSweGymExperimentJSONRequestBody defines body for PlanSweGymExperiment for application/json ContentType.
type PlanSweGymExperimentJSONRequestBody = SweGymConfig

// PinCodingTraceJSONRequestBody defines body for PinCodingTrace for application/json ContentType.
type PinCodingTraceJSONRequestBody PinCodingTraceJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /coding-traces)
	ListCodingTraces(w http.ResponseWriter, r *http.Request, params ListCodingTracesParams)

	// (GET /coding-traces/exports)
	ListCodingTraceExports(w http.ResponseWriter, r *http.Request)

	// (POST /coding-traces/exports)
	CreateCodingTraceExport(w http.ResponseWriter, r *http.Request)

	// (GET /coding-traces/exports/{id}/download)
	DownloadCodingTraceExport(w http.ResponseWriter, r *http.Request, id ExportID)

	// (GET /coding-traces/settings)
	GetCodingTraceSettings(w http.ResponseWriter, r *http.Request)

	// (PUT /coding-traces/settings)
	PutCodingTraceSettings(w http.ResponseWriter, r *http.Request, params PutCodingTraceSettingsParams)

	// (GET /coding-traces/swe-gym/experiments)
	ListSweGymExperiments(w http.ResponseWriter, r *http.Request)

	// (POST /coding-traces/swe-gym/experiments)
	CreateSweGymExperiment(w http.ResponseWriter, r *http.Request)

	// (GET /coding-traces/swe-gym/experiments/{id})
	GetSweGymExperiment(w http.ResponseWriter, r *http.Request, id ExperimentID)

	// (POST /coding-traces/swe-gym/experiments/{id}/cancel)
	CancelSweGymExperiment(w http.ResponseWriter, r *http.Request, id ExperimentID)

	// (POST /coding-traces/swe-gym/experiments/{id}/resume)
	ResumeSweGymExperiment(w http.ResponseWriter, r *http.Request, id ExperimentID)

	// (POST /coding-traces/swe-gym/plan)
	PlanSweGymExperiment(w http.ResponseWriter, r *http.Request)

	// (DELETE /coding-traces/{id})
	DeleteCodingTrace(w http.ResponseWriter, r *http.Request, id TraceID)

	// (GET /coding-traces/{id})
	GetCodingTrace(w http.ResponseWriter, r *http.Request, id TraceID)

	// (GET /coding-traces/{id}/events)
	ListCodingTraceEvents(w http.ResponseWriter, r *http.Request, id TraceID, params ListCodingTraceEventsParams)

	// (POST /coding-traces/{id}/pin)
	PinCodingTrace(w http.ResponseWriter, r *http.Request, id TraceID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /coding-traces)
func (_ Unimplemented) ListCodingTraces(w http.ResponseWriter, r *http.Request, params ListCodingTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coding-traces/exports)
func (_ Unimplemented) ListCodingTraceExports(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /coding-traces/exports)
func (_ Unimplemented) CreateCodingTraceExport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coding-traces/exports/{id}/download)
func (_ Unimplemented) DownloadCodingTraceExport(w http.ResponseWriter, r *http.Request, id ExportID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coding-traces/settings)
func (_ Unimplemented) GetCodingTraceSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /coding-traces/settings)
func (_ Unimplemented) PutCodingTraceSettings(w http.ResponseWriter, r *http.Request, params PutCodingTraceSettingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coding-traces/swe-gym/experiments)
func (_ Unimplemented) ListSweGymExperiments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /coding-traces/swe-gym/experiments)
func (_ Unimplemented) CreateSweGymExperiment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coding-traces/swe-gym/experiments/{id})
func (_ Unimplemented) GetSweGymExperiment(w http.ResponseWriter, r *http.Request, id ExperimentID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /coding-traces/swe-gym/experiments/{id}/cancel)
func (_ Unimplemented) CancelSweGymExperiment(w http.ResponseWriter, r *http.Request, id ExperimentID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /coding-traces/swe-gym/experiments/{id}/resume)
func (_ Unimplemented) ResumeSweGymExperiment(w http.ResponseWriter, r *http.Request, id ExperimentID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /coding-traces/swe-gym/plan)
func (_ Unimplemented) PlanSweGymExperiment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /coding-traces/{id})
func (_ Unimplemented) DeleteCodingTrace(w http.ResponseWriter, r *http.Request, id TraceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coding-traces/{id})
func (_ Unimplemented) GetCodingTrace(w http.ResponseWriter, r *http.Request, id TraceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /coding-traces/{id}/events)
func (_ Unimplemented) ListCodingTraceEvents(w http.ResponseWriter, r *http.Request, id TraceID, params ListCodingTraceEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /coding-traces/{id}/pin)
func (_ Unimplemented) PinCodingTrace(w http.ResponseWriter, r *http.Request, id TraceID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCodingTraces operation middleware
func (siw *ServerInterfaceWrapper) ListCodingTraces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCodingTracesParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "task_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "task_id", r.URL.Query(), &params.TaskId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "task_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "task_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "success" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "success", r.URL.Query(), &params.Success, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "success"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "success", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCodingTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCodingTraceExports operation middleware
func (siw *ServerInterfaceWrapper) ListCodingTraceExports(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCodingTraceExports(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCodingTraceExport operation middleware
func (siw *ServerInterfaceWrapper) CreateCodingTraceExport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCodingTraceExport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadCodingTraceExport operation middleware
func (siw *ServerInterfaceWrapper) DownloadCodingTraceExport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExportID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadCodingTraceExport(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCodingTraceSettings operation middleware
func (siw *ServerInterfaceWrapper) GetCodingTraceSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCodingTraceSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutCodingTraceSettings operation middleware
func (siw *ServerInterfaceWrapper) PutCodingTraceSettings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PutCodingTraceSettingsParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutCodingTraceSettings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSweGymExperiments operation middleware
func (siw *ServerInterfaceWrapper) ListSweGymExperiments(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSweGymExperiments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSweGymExperiment operation middleware
func (siw *ServerInterfaceWrapper) CreateSweGymExperiment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSweGymExperiment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSweGymExperiment operation middleware
func (siw *ServerInterfaceWrapper) GetSweGymExperiment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExperimentID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSweGymExperiment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelSweGymExperiment operation middleware
func (siw *ServerInterfaceWrapper) CancelSweGymExperiment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExperimentID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelSweGymExperiment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResumeSweGymExperiment operation middleware
func (siw *ServerInterfaceWrapper) ResumeSweGymExperiment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExperimentID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeSweGymExperiment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlanSweGymExperiment operation middleware
func (siw *ServerInterfaceWrapper) PlanSweGymExperiment(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlanSweGymExperiment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCodingTrace operation middleware
func (siw *ServerInterfaceWrapper) DeleteCodingTrace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TraceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCodingTrace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCodingTrace operation middleware
func (siw *ServerInterfaceWrapper) GetCodingTrace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TraceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCodingTrace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCodingTraceEvents operation middleware
func (siw *ServerInterfaceWrapper) ListCodingTraceEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TraceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCodingTraceEventsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCodingTraceEvents(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PinCodingTrace operation middleware
func (siw *ServerInterfaceWrapper) PinCodingTrace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id TraceID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PinCodingTrace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces", wrapper.ListCodingTraces)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/coding-traces/{id}", wrapper.DeleteCodingTrace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces/{id}", wrapper.GetCodingTrace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces/{id}/events", wrapper.ListCodingTraceEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/coding-traces/{id}/pin", wrapper.PinCodingTrace)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces/exports", wrapper.ListCodingTraceExports)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/coding-traces/exports", wrapper.CreateCodingTraceExport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces/exports/{id}/download", wrapper.DownloadCodingTraceExport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces/settings", wrapper.GetCodingTraceSettings)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/coding-traces/settings", wrapper.PutCodingTraceSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces/swe-gym/experiments", wrapper.ListSweGymExperiments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/coding-traces/swe-gym/experiments", wrapper.CreateSweGymExperiment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/coding-traces/swe-gym/experiments/{id}", wrapper.GetSweGymExperiment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/coding-traces/swe-gym/experiments/{id}/cancel", wrapper.CancelSweGymExperiment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/coding-traces/swe-gym/experiments/{id}/resume", wrapper.ResumeSweGymExperiment)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/coding-traces/swe-gym/plan", wrapper.PlanSweGymExperiment)
	})

	return r
}
