// Code generated by "go run ./internal/generate/modules gen". DO NOT EDIT.
// Source: modules/coding-traces/module.yaml

package backend

import (
	"encoding/json"

	"github.com/jj-link/local-model-works/internal/moduleapi"
)

// descriptor is this module's frozen manifest.
var descriptor = moduleapi.Descriptor{APIVersion: "localmodelworks/v1alpha1", Kind: "Module", ID: "coding-traces", Title: "Coding Traces", Route: "/coding-traces", Nav: moduleapi.Nav{Label: "Coding Traces", Order: 60, Icon: "coding-traces"}, SettingsSchema: json.RawMessage("{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"additionalProperties\":false,\"properties\":{\"capture_reasoning\":{\"default\":true,\"type\":\"boolean\"},\"export_max_context_tokens\":{\"default\":32768,\"maximum\":1048576,\"minimum\":1024,\"type\":\"integer\"},\"export_success_cap_per_task\":{\"default\":2,\"maximum\":100,\"minimum\":1,\"type\":\"integer\"},\"retention_days\":{\"default\":0,\"maximum\":3650,\"minimum\":0,\"type\":\"integer\"}},\"type\":\"object\"}"), JobKinds: []string{"trace-tokenize", "trace-export", "trace-retention", "swe-gym-orchestrate", "swe-gym-rollout", "swe-gym-grade"}, ArtifactKinds: []string{"coding-trace-dataset", "swe-gym-report"}, APIFragment: "api.yaml", Capabilities: []string{"runs.create", "runs.read", "nodes.read", "deployments.read", "artifacts.publish", "settings.read", "settings.write", "secrets.read", "events.publish"}}
